components/PageHero/PageHero.vue

The purpose of this PR is to fix a bad merge and add missing closing bracket. This will fix a build issue.
- Running `yarn dev` should run successfully and you should see the homepage.

Fix bad merge - Add missing closing bracket

---

components/FeaturedData/FeaturedData.vue
pages/index.vue
yarn.lock

The purpose of this PR is to hook up the featured data section of the homepage to Contentful.
On the homepage, the featured data should match the screenshot. You can adjust this featured data on the "Homepage" content in Contentful, and it should update.

Add homepage featured data #406rbf

---

assets/_variables.scss
components/FeaturedData/FeaturedData.vue

The purpose of this PR is to make the suggested changes to the featured data section of the homepage as detailed in this [ticket](https://app.clickup.com/t/467frm)
Verify the design changes outlined in the clickup ticket.

Homepage Featured Data Updates #467frm

---

assets/components/_el-tag.scss
assets/element-variables.scss
components/SearchFilters/SearchFilters.vue
components/SearchForm/SearchForm.vue
components/SearchResults/EventSearchResults.vue
components/SearchResults/ProjectSearchResults.vue
pages/data/index.vue

The purpose of this PR add the design revisions for the Find Data page.
See screenshot above.

Find data - design revisions #44bvwu

---

assets/_layout.scss
components/SearchResults/DatasetSearchResults.vue
mixins/format-date/index.js
package.json
pages/data/index.vue

The purpose of this PR is to create a system to load data from different sources. We have two sources for the Find Data page: Contentful and the Blackfynn API.
In addition, I created the component to render Datasets.
**Note:** Filters do not work at the moment and will be in a separate PR when [the endpoint](https://app.clickup.com/t/4a7n77) is available
- Datasets should be loaded (this is from the Blackfynn API)
- Use the pagination, and datasets should be loading
- Search for something like "Rat"
- Filtered datasets should be shown
- Go to the Projects tab and Projects should be loaded (this is from Contentful)
- Go to the Datasets tab and Datasets should be loaded

Find Data - Load data from different sources #4a9p42 #4a7q6p

---

components/CookieNotice/CookieNotice.vue
layouts/default.vue
middleware/cookie.js
nuxt.config.js
package.json
store/index.js
yarn.lock

The purpose of this PR is to add a GDPR cookie notice to the app. 
- You should see a banner at the bottom of the site notifying you that we use cookies.
- Click on the "Accept" button
- Banner should disappear
- Reload the page
- Banner should not be present
- Open devtools and find the cookie `GDPR:accepted` and make sure it's `true`
- devtools -> Application-> Cookies -> http://localhost:3000
- Delete this cookie
- Reload the page
- You should see the banner
- Click on the X icon in the top right of the banner
- Banner should disappear
- Reload the page
- Banner should not be present
- Open devtools and find the cookie `GDPR:accepted` and make sure it's `true`
- devtools -> Application-> Cookies -> http://localhost:3000

GDPR Cookie notice #4g6ky3

---

components/HomepageTwitter/HomepageTwitter.vue

The purpose of this PR is to fix the Twitter feed on the homepage. There was an issue where the script embedded was being removed during the build. To resolve this issue, and to keep the optimized lazy loading experience, I opted for a solution to add the script tag for the Twitter widget on load of the component.
- Run `yarn build` to build the app
- Run `yarn start` to run the built version of the app
- Scroll down on the homepage to see the Twitter feed
- Go to the About page and refresh the app (this will simulate a direct load on a page that is not the homepage)
- Go to the homepage
- Scroll down on the homepage to see the Twitter feed

Fix Twitter feed issue

---

components/footer/Footer.vue
components/header/Header.vue

The purpose of this PR is to do the following
- Add link for "Contact Us" in the header
- Remove the "Report a bug" link in the footer
- Click on "Contact Us" in the header's aux nav
- You should be taken to a Wrike form
- Scroll to the footer of the site
- "Report a bug" should not be in the footer

Address footer and header links #407yg9 #4jbr10

---

components/MarkdownPage/MarkdownPage.vue
components/MarkdownPage/asyncMarkdown.ts
nuxt.config.js
pages/privacy/index.vue
pages/terms-of-service/index.vue
vue-shim.d.ts

Fetch the content for Terms of Service and Privacy Policy pages from contentful.
Scroll to the bottom of the portal and click of the Terms of Service and Privacy Policy pages.  In each case the content should be loaded based on the content in contentful.

Terms and privacy #4g74pc

---

components/HomepageNews/HomepageNews.vue
components/SparcCard/SparcCard.vue

Address the responsiveness of the events in the home page by using some fixed sizes for the images and allowing the copy to grow.  
Use the developer tools to make sure the events content in the home page look good on desktop, tablet (both portrait and landscape), and mobile.

News events design #4jbren

---

pages/data/index.vue

The purpose of this PR is to add filter functionality to the Find Data section. This is for content from both contentful and the Blackfynn API
- On the Datasets tab, click on the "Filters" button
- Select "Stomach" and hit apply
- The search should update and show results for datasets tagged "Stomach"
- Click on the "Filters" button. Select "Tag1" and hit apply
- The search should update and show no results
- Using the tags above the table, click on the X next to "Tag1"
- The search should update and show results for datasets tagged "Stomach"
- Click on the "Filters" button. Click the "Clear All" button
- The search should update and show you all results for Datasets
- Go to the Find Data Page
- On the Organs tab, click on the "Filters" button
- Select "Tag1"
- …

Find data filter functionality #4jbra0

---

components/SearchResults/DatasetSearchResults.vue
pages/datasets/_datasetId.vue

The purpose of this PR is to resolve the issue where data wasn't being reflected properly whenever a dataset detail or simulation detail page was refreshed. I have also adjusted the `asyncData()` call to include all required endpoint requests.
1. Navigate to the Find Data > Simulations page and visit a simulation detail page. All data should be rendered as expected. 
2. Refresh the page. All data should still be consistent.
3. Navigate to the Find Data > Datasets page and visit a simulation detail page. All data should be rendered as expected.
4. Refresh the page. All data should still be consistent.
5. Navigate back to a simulation detail page. You should still the expected simulation data.

Resolve Async Issue on Simulations Page #4jbdyq

---

components/SearchMapPopup/SearchMapPopup.vue
components/bf-dialog-header/BfDialogHeader.vue
yarn.lock

Add the rat scaffold to the 2d flatmap and provide a toggle
There should be a toggle to switch between human and rat.  Right now, it won't change the scaffold.  We need changes to the FlatmapVuer for that to work.

Add rat scaffold to 2d flatmap popup.

---

assets/_variables.scss
components/Breadcrumb/Breadcrumb.vue
components/Resources/PlatformSearchResults.vue
components/Resources/ResourcesSearchResults.vue
components/Resources/ToolSearchResults.vue
nuxt.config.js
pages/resources/_resourceId.vue
pages/resources/index.vue

The purpose of this PR is to create the resources page and wire it up to contentful. Please note that the `platforms` and `tools` tab is not yet connected yet. This is an initial PR to get a review before those tabs are wired up.
Navigate to the resources page. All data should be displayed and function as expected, with exception to the platform and tools tabs. Responsive design should function and look as expected as well, according to the [designs](https://app.abstract.com/projects/e709ca90-5ba9-11e9-9eaa-59df656d954a/branches/7ff6a970-9a3d-4f46-ae0a-d10925710fc1/commits/54ca8d150f62f1c89749af03e457144394d0e8fa/files/a878d736-29fb-4fd2-b67e-dbb681e9f1d9/layers/6BB64ED7-AD5C-4390-BA8D-3661D3ECFE78?collectionId=d5de4d2e-adfe-4b72-966a-f7b31da49aed).

Resources Landing Page #4jbtfd

---

components/header/Header.vue

The purpose of this PR is to do the following:
- Add mobile menu icons
- Fix mobile menu contact us link
- Open mobile menu
- "About SPARC", "Contactu Us", "Need Help?" should have an icon
- Click on the Contact Us link. You should be taken to the wrike form

Mobile menu fixes #4jcub2

---

components/HomepageTwitter/HomepageTwitter.vue
components/footer/Footer.vue
components/header/Header.vue
nuxt.config.js
package.json
pages/index.vue
pages/projects/_projectId.vue
pages/workflows/_datasetId.vue
plugins/bootstrap.js
yarn.lock

The purpose of this PR is to fix the site's main title from `sparc-portal` to `SPARC Portal` and to have all external links open in a new tab.
Verify that the site's title is now `SPARC Portal` on all pages. Also verify that external links are now opening in new tabs instead of the same tab.

Fix Site's Title and Open External Links in New Tabs #4m8v71 #4mdfz8

---

components/HelpHero/HelpHero.vue
components/PageHero/PageHero.vue
pages/about/index.vue
pages/data/index.vue
pages/resources/index.vue

The purpose of this PR is to add the redesigns for the page hero. This is _without_ the images and homepage redesign.
Visit the subpages and ensure that the heroes look consistent with the new design.

Page hero redesign #4m8vtx

---

components/SearchMapPopup/SearchMapPopup.vue
package.json
yarn.lock

Update to the latest versions per Alan, adjust the 2D Human/Rat toggle per his feedback.
Pull up the anatomical map in find data.  You should be able to switch between human and rat.  The anatomical selections should be behind a hamburger menu and should match the purple color of the rest of the site.
The 3D Scaffold tab should have similar style changes.

update the versions of flatmapvuer and scaffoldvuer

---

assets/_base.scss
components/ContributorItem/ContributorItem.vue
components/DownloadDataset/DownloadDataset.vue
components/HomepageTestimonials/HomepageTestimonials.vue
components/SearchResults/DatasetSearchResults.vue
components/SearchResults/EventSearchResults.vue
components/SearchResults/OrganSearchResults.vue
components/SearchResults/ProjectSearchResults.vue
components/footer/Footer.vue
components/header/Header.vue
pages/about/index.vue
pages/data/index.vue
pages/help/_helpId.vue
pages/index.vue

The purpose of this PR is to address the following issues that were discovered during QA:
- Change the placeholder for header search
- Add breadcrumbs to pages
- Remove copy left of Terms of Service link
- Remove anatomical map
- Find Data "No results" copy
- Find Data - hide pagination if needed
- Fix bug where Find Data main link would error if on data page
- Link to help section in Download Dataset dialog
- Fix breadcrumb positioning on help page
- Fix issue when loading contributor ORCID
- Header search: Allow enter key to search
- Fix issue with testimonial author spacing
- Fix testimonial end double quote
- Fix homepage hero heading 
See the list above for all issues fixed.

QA Round 1 #4m8ejt

---

components/DatasetDetails/DatasetAboutInfo.vue
components/HomepageTestimonials/HomepageTestimonials.vue
components/Resources/ResourcesSearchResults.vue
components/SearchResults/ProjectSearchResults.vue
pages/projects/_projectId.vue

The purpose of this PR is to address the following issues that were discovered during QA:
- Change heading to "Principal Investigator" on project details page
- Change copy to "NIH Award" throughout the app
- Resources page - Align text and title, even without image
- Change heading to "Protocol Links"
- Change homepage heading to "Connecting the Research Community"
See above list

QA Round 2 #4m8ejt

---

components/ContributorItem/ContributorItem.vue
components/HomepageNews/HomepageNews.vue
pages/help/_helpId.vue
pages/help/index.vue

The purpose of this PR is to address the following QA issues:
- Fix issue with images on help articles
- Remove paragraph around homepage news button
- Add breadcrumb to help page
- Fix person's name in ORCID tooltip 
See list above.

QA #4m8ejt

---

pages/organs/_organId.vue

The purpose of this PR is to change how the Projects tab for an Organ is populated. Before, we were looking up what projects were linked to an organ. Now the project section is part of the organ, so we are using that field.
- Visit the [heart page](http://localhost:3000/organs/2MyjbZVNRrJjLtRrpQ8DXc)
- This page should have projects
- Visit any other organ
- (Chances are) this page won't have projects. The projects tab should not be visible.

Account for new project relationships

---

components/HelpCard/HelpCard.vue
components/HomepageNews/HomepageNews.vue
nuxt.config.js
package.json
yarn.lock

The purpose of this PR is to address the following QA issues:
- Account for missing Contentful fields
- Add google analytics 
Most of these fixes are prod issues, but we can test if the changes don't break current functionality.
- Homepage
- The news and events items should display images
- Help 
- The help documents should show their titles and summaries
- This is currently disabled in dev mode.

QA #4yd5t2

---

package.json
yarn.lock

The purpose of this PR is to resolve [security issues](https://github.com/nih-sparc/sparc-app/network/alerts) found in some of the dependencies. The hope was that upgrading Nuxt to its latest version, 2.12.1, would resolve this and it turns out it did.
After upgrading to Nuxt 2.12.1, I got the info of the dependencies with vulnerabilities. All of these dependencies were upgraded to at least the recommended version. 
In addition, I ran the app locally and all functionality still works as expected.
Upgrade minimist to version 1.2.2 or later. For example:
```
minimist@^1.2.2:
version "1.2.2"
```
```
➜  sparc-app git:(resolve-security-issues-dependencies-#5mgckt) yarn info minimist
yarn info v1.22.4
{
name: 'minimist',
description: 'parse argument options',
'dist-tags': {
latest: '1.2.5'
}, …
```

Upgrade Nuxt to 2.12.1

---

components/PageHero/PageHero.vue
pages/index.vue

Reverts nih-sparc/sparc-app#105. These changes were not to go to staging yet and will be part of the next sprint.

Revert "Add video to homepage hero"

---

CONTRIBUTING.md

change to documentation to point to the right wiki article for contributing
N/A

pointing to the right page on the wiki

---

components/HelpHero/HelpHero.vue
components/SearchControlsContentful/SearchControlsContentful.vue
pages/data/index.vue
pages/news-and-events/index.vue
pages/news-and-events/model.ts
pages/resources/index.vue
pages/resources/model.ts
vue-shim.d.ts

Adds a search bar to the resources and news/events pages.  
Navigate to the resources and news/events pages, respectively.
You should be able to enter a search term and have the results filtered accordingly.

Add search to resources and news #72dmvc

---

pages/data/index.vue
pages/organs/_organId.vue

The purpose of this PR is to default to the organ's name if there is no project 
- Navigate to [Colon and Large Intestine](http://localhost:3000/organs/3pbQ69rH6PqxtNuE1DWov5)
- You should see datasets
- Navigate to [Male Reproductive System](http://localhost:3000/organs/2jl09aPluKNlyK4weN995R) 
- No datasets will appear, but in the Network tab, it should have a query of `Male Reproductive System`

Fix organ details page - Datasets 

---

components/DatasetDetails/DatasetAboutInfo.vue
package.json
plugins/bootstrap.js
yarn.lock

- Added Bibtex as possible citation option.
- Updated citation links style.
- Added copy citation button.
- Added publication date and platform.
[Designs](https://app.abstract.com/share/f93d41ce-bfd5-4b25-b8f6-18afd7f06036?collectionId=f84035c5-d019-4b9e-8188-df369a4f12af&collectionLayerId=c0e49d31-31f0-46f3-be55-cdde421e5a3c&present=true&preview=false&sha=83a3dc752dcbedfca3c5214ba98144f47c890509)
[Clickup](https://app.clickup.com/t/7pga9w)
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#/inbox/task/489477895)
2. Click on any dataset.
3. Navigate to About tab.
4. Citation links style will be updated according to designs.
5. Click on Copy Citation button.
6. Citation will copy to your clipboard.

Format data citations #CU-7pga9w

---

components/footer/Footer.vue

Simply adds a missing link in mobile version. Note that the content of this page comes from Contentful and should probably be reviewed and published there first.
Code fix + content addition (in Contentful)
Manual

Added 'Terms of Service' link also in non-mobile version

---

nuxt.config.js

The purpose of this PR is to add a redirect from `/submit_data.html` to `/help/7k8nEPuw3FjOq2HuS8OVsd`.
- Navigate to http://localhost:3000/submit_data.html
- You should be redirected to http://localhost:3000/help/7k8nEPuw3FjOq2HuS8OVsd

Add redirect for submit_data.html

---

assets/_base.scss
mixins/highlight-text/index.js

The purpose of this PR is to adjust the styles of the highlighted text.
- Click on the "Need Help?" link in the header
- Enter a search term like "SPARC"
- All instances matching your search term should be bold.

Highlighted text styles

---

pages/datasets/_datasetId.vue

The purpose of this PR is to update 'DC.publisher' to 'Blackynn Discover'.
- Open a dataset
- Open up the devtools and go to the Elements tab
- Do a find for `ldjson-schema`
- Copy the content of the script tag
- Use the [Google structured data testing](https://search.google.com/structured-data/testing-tool/u/0/) tool to paste the schema into it and validate it
- You should see the publisher is set to `Blackfynn Discover`

Update 'DC.publisher' to 'Blackynn Discover' CU-90j6t5

---

package.json
yarn.lock

Fix checkboxes not updated with a map reset.
Check on site on successfully ran the test.

Fix checkboxes not updating after map reset

---

pages/data/index.vue

Reverts nih-sparc/sparc-app#172
This will add the heading back to staging now that the release is out.

Revert "Remove Find Data heading"

---

components/CookieNotice/CookieNotice.vue

Set a 30 day expiration date to the GDPR cookie.
[ayqued](https://app.clickup.com/t/ayqued)
[wrike](https://www.wrike.com/open.htm?id=491218002)
**Chrome (for easy viewing of the cookie information, but it works in all browsers)** 
1. Quit out of all Chrome pages (cmd + Q).
2. Open Chrome.
3. Go to http://localhost:3000/
4. Click on the Accept button in the cookies notification.
5. Click on the three dots on the top right of the browser.
6. Click settings.
7. In the search bar of the settings page search cookies.
8. Click on this option:
9. ![Screen Shot 2020-08-27 at 10 39 04 AM](https://user-images.githubusercontent.com/55994045/91456696-918aa900-e851-11ea-8134-e702d26d5a92.png)
10. Scroll down and select:
11. ![Screen Shot 2020-08-27 at 10 39 58 …

fix(cookies): Set 30 day expiration date to GDPR cookie

---

components/SearchResults/ProjectSearchResults.vue
pages/data/index.vue

1. Fix incorrect font size in description column of Project listing page.
* This issue does not appear when using the mobile device view in chrome dev tools. To see this issue, use an actual mobile device and navigate to `https://staging.sparc.science`, where you will see the description column with incorrect font size in the project listing section.
2. Fix pagination sizing.
* The pagination is tough to resize, Element offers a `small` property, but it is not customizable past their preset width and for mobile devices, it still goes past the edge of the screen. Additionally, Element does not allow for a page count less than 5, so it is not possible to just show less page numbers (technically it works but it throws a lot of errors in console when resizing, so no good). I ended up moving …

Mobile Sizing for Project Description and Pagination

---

nuxt.config.js
package.json
pages/datasets/scaffoldviewer/_id.vue
pages/maps/index.vue
yarn.lock

This update removes the css  imported into global scope from map app. 
Test runs succesfully. An instance is running [here](https://mapcore-demo.org/current/sparc-app/) and it is looking fine.

Map css fix

---

components/HomepageNews/HomepageNews.spec.js
components/HomepageNews/HomepageNews.vue
components/HomepageNews/mockNews.js
package.json
yarn.lock

The purpose of this PR is to show future news on the homepage, or if it doesn't have a date. 
The news added to contentful are all in the past, but I wrote a test for this functionality.

feat(Homepage): Show news that doesn't have a date

---

pages/resources/index.vue
pages/resources/model.ts

The purpose of this PR is to update categories on the Tools and Resources page. Unfortunately, nothing is updated yet on Contentful so it isn't showing any results.
Unfortunately, nothing is updated yet on Contentful so it isn't showing any results. Clicking on these categories, you can see that the proper network call is being made.

feat(Resources): Update categories

---

components/AccessibilityDialog/AccessibilityDialog.vue
components/CookieNotice/CookieNotice.vue
components/DownloadDataset/DownloadDataset.vue

The purpose of this PR is to add a popup to the cookies banner with details regarding the accessibility standards.
[Clickup Ticket](https://app.clickup.com/t/guvugx)
Click on the `Accessibility Standards` link in the cookies banner. The modal should come up and function as expected.

Minimum Accessibility Popup CU-guvugx

---

mixins/request-download-file/index.js

This reverts commit f12c4cb13c7c7ea155b1276f67432119d7962510.

Revert "using ZipIt for downloading files"

---

pages/resources/index.vue

The purpose of this PR is to add support for long hero field. This is to allow the addition of "Tools & Resources developed by SPARC are indicated with a badge" in the hero.
- Go to the Tools and Resources page
- The hero should have the following copy
> Check out these tools & resources to help enhance how you access, visualize and run simulations on SPARC data. Tools & Resources developed by SPARC are indicated with a badge. To suggest additional tools and resources, please submit a [request](https://forms.gle/RRN9JHZUUgRkaGNL6).

feat(Resources):  Add support for long hero field

---

pages/maps/index.vue

There was a bug causing certain endpoints do not work properly.
This has been tested in the mapcore-demo instance and it passes the unit test.

Make sure the endpoint used in map always have a trailing slash.

---

components/FeaturedData/FeaturedData.spec.js
components/FeaturedData/FeaturedData.vue
components/FeaturedData/mock-featured-data.js

The purpose of this PR is to add a "view more" functionality to for featured data on the homepage. This will show six items until the user clicks on the "View more" button.
Unit tests were created for the following situations:
- Should only show 6 items and a View more button
- Should only show 4 items and no View more button
- Should should all 8 items and no View more button

feat(Homepage): View more functionality for featured data

---

components/AccessibilityDialog/AccessibilityDialog.vue

@JeremyLecoeur - at the risk of breaking some coding style, is this all that is needed to fix this ticket? (and so I can feel like I'm contributing to the Portal ;-)
Fixing a typo in the accessibility statement.

Fix typo in accessibility statement.

---

components/footer/Footer.vue
components/footer/FooterLink.spec.js
components/footer/FooterLink.vue

The purpose of this PR is to add a Policies section to the footer, and adjust the layout to match [the new design](https://share.goabstract.com/e17695cc-fc3c-4007-8814-4012547a2efe?collectionLayerId=e89c262d-a009-4d4d-a1c4-b71409388bc6&mode=design&present=true)
https://app.clickup.com/t/m12v8n
https://www.wrike.com/open.htm?id=529909970
Compare the footer with [the new design](https://share.goabstract.com/e17695cc-fc3c-4007-8814-4012547a2efe?collectionLayerId=e89c262d-a009-4d4d-a1c4-b71409388bc6&mode=design&present=true) on all breakpoints.
Tests were written for the new `FooterLink` component

Feat policies in footer cu m12v8n

---

assets/components/_el-button.scss
components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ContactUsForms/NewsletterMixin.js
components/ContactUsForms/questions.js
components/header/Header.vue
nuxt.config.js
pages/contact-us/index.vue

The purpose of this PR is to add contact forms to the portal. These two forms are for general inquiries and for reporting a bug. For general inquiries, it will send an email to SPARC. For bugs, it will create a wrike ticket.
https://app.clickup.com/t/jjvezd
https://www.wrike.com/open.htm?id=467362300
- In the header, click on "Contact Us'
- You should be taken to the contact us page
- Select `I couldn’t find the information in Help` from the dropdown
- The general form should be shown
- Clicking submit should notify you what fields are required
- Fill out the form and click "submit"
- Checking "Subscribe to the SPARC Newsletter" should add that email to the Mailchimp list. Ask Leo for access to verify.
- You should now see a success message with your first name displayed
- Click on …

Contact form - cu-jjvezd

---

components/footer/Footer.vue

The youtube link should redirect to the SPARC youtube channel

changing youtube URL

---

package.json
pages/datasets/plotviewer/_id.vue
yarn.lock

Update plot viewer to use gazelle's ui controls design. This will also bring it to match the version currently being used in [`mapintegratedvuer`](https://github.com/ABI-Software/mapintegratedvuer) and [`simulationvuer`](https://github.com/ABI-Software/simulationvuer)
View it [here](https://jesses-dev-sparc-science.herokuapp.com/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv&plot_type=heatmap)
Tested in the apps that use it as a dependency, mapintegratedvuer and simulationvuer. 
Tested in a [heroku clone of sparc-app](https://jesses-dev-sparc-science.herokuapp.com/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv&plot_type=hea …

Update plotvuer with gazelle's ui controls

---

components/CitationDetails/CitationDetails.vue
components/VersionHistory/VersionHistory.vue
pages/datasets/_datasetId.vue

Currently, we are using the wrong "Publication Date" in citation details and the wrong "last published" in version history.
This PR is fixing this

use published date

---

components/HomepageNews/HomepageNews.spec.js
components/HomepageNews/HomepageNews.vue
components/HomepageNews/mockNews.js

The purpose of this PR is to fix events on the homepage not linking to their detail page.
Added unit tests

Fix homepage events not linking to details

---

.gitignore
components/DatasetDetails/DatasetAboutInfo.vue

This PR aims to show a primary publication if en external publication with the relationship Type `IsDescribedBy` is present

Is described by primary publication

---

package.json
pages/datasets/scaffoldviewer/_id.vue
pages/maps/index.vue
yarn.lock

Add UI and method to save and restore state of the scaffold using data stored in the database. See the API implementation here - https://github.com/nih-sparc/sparc-api/pull/46
The following link should restored the scaffold to a specific viewport
https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=105%2F2%2Ffiles%2Fderivative%2FScaffold%2FratStomach_metadata.json&id=ea8add74
New link will also be copied when the share link button is pressed at the top right corner of the scaffold viewer.

Scaffoldstate

---

pages/datasets/scaffoldviewer/_id.vue
pages/maps/index.vue

Add viewURL and region query parameters to dataset scaffold viewer page. This provide an option to specify an anatomical region of interests.
Related wrike ticket can be found here: https://www.wrike.com/open.htm?id=666660985
An example of this can be found here:
https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=76%2F3%2Ffiles%2Fderivative%2FScaffold%2FmouseColon_metadata.json&viewURL=https%3A%2F%2Fmapcore-bucket1.s3-us-west-2.amazonaws.com%2FGeneric%2BScaffold%2FColon%2Fmouse%2FproximalColon_view.json
https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=76%2F3%2Ffiles%2Fderivative%2FScaffold%2FmouseColon_metadata.json&viewURL=https%3A%2F%2Fmapcore-bucket1.s3-us-west-2.amazonaws.com%2FGeneric%2BScaffold%2FColon%2Fmou …

Scaffold view url

---

package.json
pages/datasets/scaffoldviewer/_id.vue
yarn.lock

Make sure the time slider style is matching with the designs. Users would not be able to see the markers text on the time sliderwithout this fix,
It is deployed and can be checked here - alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=34%2F3%2Ffiles%2Fderivative%2FScaffolds%2Fsub-all_direct-stim_proximal-colon%2Fmotility_v3_metadata.json

Fix styles on time slider for scaffold viewer

---

components/SearchResults/DatasetSearchResults.vue
pages/data/index.vue

Added additional metadata to the dataset results to match the wireframes found here: https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403. Just a heads up, I ran the linter on the index file and it formatted a fair amount of extraneous stuff that I did not touch
In order to run locally you must have the following env variables set:
ALGOLIA_API_KEY=9f55092cb37c3896a8bfc48ef87206d6
ALGOLIA_APP_ID=04WW1V1O0F
Ran changes locally and navigated to the 'Datasets' and 'Simulations' tabs to verify that metadata is displayed properly:

Added metadata properties

---

components/HelpCard/HelpCard.vue
components/SearchForm/SearchForm.vue
components/header/Header.vue
pages/data/index.vue
pages/help/_helpId.vue
pages/news-and-events/events/_id.vue
pages/news-and-events/events/index.vue
pages/news-and-events/index.vue
pages/news-and-events/model.ts

I've gone through the Portal Development backlog on wrike and putting them into a single pull request here. 
The tickets included and the way to check the fixes are below:
> Description:
Using the search functionality i entered text when I clicked the 'x' to clear nothing happened, the search text remained. 
go to: https://sprint-13-bug-fixes.herokuapp.com/data?type=dataset
> Acceptance Criteria: 
Update the newsletter widget from "Sign up to the SPARC Newsletter" to "Sign up for the SPARC Newsletter" 
Capitalize "Portal" in the sentence "Keep up to date with all the latest news and events from the SPARC portal."
go to: https://sprint-13-bug-fixes.herokuapp.com/news-and-events
> Acceptance Criteria:
Clicking on the image within an Event Details page brings user to external URL provided in …

Spint 13 bug fixes

---

mixins/marked/index.js
package.json
pages/data/index.vue
pages/news-and-events/community-spotlight/index.vue
pages/news-and-events/community-spotlight/success-stories/_id.vue
pages/news-and-events/community-spotlight/success-stories/index.vue
pages/news-and-events/model.ts
yarn.lock

View these changes at:
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight/success-stories/developer-testing
Charles Horn (Main contenful platform editor) requested a few changes that were different to Gazelle's original design
Discussion on it is available at this ticket:
https://www.wrike.com/open.htm?id=678414135
Changes are:
- Main story is now markdown (no longer rich text)
- Switched a lot of the success stories page fields to markdown, giving more control to contentful editors
- Added youtube embedded video support to the markdown image processing, it is used like so:
`![Ascension Bowl](https://youtu.be/dj7N6czFbuQ)`
Resources for inspired changes: 
`marked` embedded youtube video:
https://gist.github.com/Snugug/9203fd0dc5e00d8ce799
Fluid width video: …

Charles' requested contenful changes (more markdown fields and no rich text)

---

components/CookieNotice/CookieNotice.vue
nuxt.config.js
package.json
yarn.lock

This map app updates include many changes including:
- [Dynamic flatmap markers](https://www.wrike.com/open.htm?id=700776036)
[Pull request](https://github.com/ABI-Software/flatmapvuer/pull/51)
- All new simulation viewer. [Ticket 1](https://www.wrike.com/open.htm?id=544758705)  [Ticket 2](https://www.wrike.com/open.htm?id=544758707) 
- [Splitscreen](https://www.wrike.com/open.htm?id=703734751)
[Pull request](https://github.com/ABI-Software/mapintegratedvuer/pull/85)
- Sidebar improvements based on UI/UX testing.
[Pull request](https://github.com/ABI-Software/map-sidebar/pull/19)
Majority of the features have gone through UI/UX testing and a demo site has been setup [here](https://mapcore-demo.org/current/sparc-app/maps/).

Major Map app update 0.2.1

---

package.json
yarn.lock

This new update fix a problem with state not restoring correctly on the flatmap using the permalink.
Test on the [page](https://mapcore-demo.org/current/sparc-app/maps/?id=8e83af83).

Use the latest version of flatmapvuer and map app.

---

components/ImagesGallery/ImagesGallery.vue

Fix for the image gallery trying to download too many images to use as thumbnails in the image gallery.  Also limit the number of attempts a thumbnail is fetched from biolucida.
With the relative link: datasets/137?type=dataset&tab=images
This dataset can now be loaded without crashing the server.

Disable loading generic images into the gallery thumbnail.

---

components/FacetMenu/DatasetFacetMenu.vue
nuxt.config.js

Let an environment variable to determine the visibility of facet filter/menu on dataset page.
I have ran some internal testing and everything is working as intended.

Add an environment variable to control the facet menu visibility.

---

pages/resources/index.vue
pages/resources/model.ts

This pull request addresses the bug reported [here](https://www.wrike.com/open.htm?id=641431224).
This has been manually tested on this [page](https://alan-wu-sparc-app.herokuapp.com/resources?type=Devices).

Fix Devices category not displaying any item.

---

components/FacetMenu/DatasetFacetMenu.vue
components/FacetMenu/FacetCategory.vue
components/FacetMenu/FacetLabel.vue
components/FacetMenu/FacetMenu.vue
components/FacetMenu/TagsContainer.vue
components/FeaturedData/FeaturedData.vue
components/SearchResults/DatasetSearchResults.vue
pages/data/index.vue
pages/data/utils.ts

I addressed most tickets that came out of the datasets facet menu feedback which are being tracked by this epic:
https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=756365538
List of fixes:
-deselect all for datasets facet menu
-dataset title and desription
-style fixes
-replaced technique facet/metadata with modalities
-made facet text clickable
-removed publication date from datasets metadata
-added help icon for facet categories
-updated emabargoed facet category
-clicking organ icon on home page automatically selects facet
-hiding number of facet results next to facet if it is (0)
I ran through different scenarios for each fix and confirmed functionality

Datasets Facet Menu Feedback Fixes

---

components/FilesTable/FilesTable.vue

Fixed the download link not working as well as the copy link
Ran locally and verified. I had to temporarily add the PORTAL_API_HOST with the value for staging to my local env variables in order to verify the copy functionality

Fix download corrupt file

---

components/header/Header.vue
pages/help/_helpId.vue

Change text to Help in several places. Help page's hero title and summary has also been updated on Contentful to match the changes. The corresponding ticket can be found [here](https://www.wrike.com/open.htm?id=599670006).
The changes can be viewed here - https://alan-wu-sparc-app.herokuapp.com/help

Retitle Need Help to Help.

---

package.json
yarn.lock

Use the latest version of mapvuer - the latest update addresses two issues -
https://www.wrike.com/open.htm?id=685879834 
and
https://www.wrike.com/open.htm?id=788290021
The changes have been tested manually here - https://alan-wu-sparc-app.herokuapp.com/

Use the latest version of mapvuer and scaffoldvuer.

---

assets/components/_el-tag.scss
assets/components/_pagination.scss
components/FeaturedData/FeaturedData.vue
components/HomepageNews/HomepageNews.vue
components/Paper/Paper.vue
components/Resources/FeaturedResource.vue
components/header/Header.vue
nuxt.config.js
package.json
pages/about/index.vue
pages/data/index.vue
pages/index.vue
plugins/system-design-components.js
yarn.lock

Imported components and styles from System Design Components library
I tested by using a couple different components from the library and verifying that they worked/looked correct

Added plugin for sparc design system components

---

components/FeaturedData/FeaturedData.vue

For adding the featured data "Nerves", the corresponding button in the Home Page needs to link to a search with several facetIds selected.
- New feature (non-breaking change which adds functionality)
Manual test

A featured organ can search with several facetIds

---

nuxt.config.js
pages/data/index.vue
pages/resources/index.vue

Modifications in the code to respond to the schema changes for Resources in Contentful.
* ``resourceTypes`` is now an array of strings, making it possible for a resource to hold several resourceTypes.
* Old resource types were migrated in Contentful to the new array property, then deleted, then the new property was renamed to have the original name.
* Front end code was updated to the new property type.
Manual testing. Please further test functionality that might have broken taking into account the changes made.
* Resources search
* Resources detail pages
* Tools & Resources page

Resource types

---

assets/components/_pagination.scss

wrike case https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=508028063&pid=467258635&cid=441356195
Making the pagination closer to the design. https://app.abstract.com/share/e17695cc-fc3c-4007-8814-4012547a2efe?collectionId=ed37ad59-75c5-496f-8bc4-2b7066d0bbd9&collectionLayerId=9d4b4729-86f4-4a67-bbf8-130cc73a8c0a&mode=build&selected=root-0BE79A82-9A10-48DE-BDA3-D39606569941&sha=92427f12423b85935ee687c53c8f0ce24e7cccae
Manual testing

Pagination

---

components/DatasetDetails/DatasetCitationsInfo.vue

Added preprints section to citations tab for bio archive datasets
Locally

add preprint section for bioarchive

---

docs/pull_request_template.md

Added an item to the PR checklist to  remind developers to utilize the Design System components library

added to checklist

---

components/VersionHistory/VersionHistory.vue

fixed typo

---

components/DatasetBannerImage/DatasetBannerImage.vue

safari image stretch fix.
Locally by using BrowserStack

Fixed image stretching for safari

---

components/Breadcrumb/Breadcrumb.vue
components/DatasetDetails/DatasetDescriptionInfo.vue
components/SearchForm/SearchForm.vue
components/VersionHistory/VersionHistory.vue
components/header/Header.vue
pages/news-and-events/community-spotlight/index.vue

Addressed a few different wrike tickets. Mainly removed the formatting for a breadcrumb so that titles dont get truncated
Locally

Miscellaneous wrike ticket fixes

---

components/PageHero/PageHero.vue
components/header/Header.vue
nuxt.config.js
pages/maps/index.vue
pages/news-and-events/news/index.vue

Addressed the following two tickets: 
https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=790444932&c=list&vid=-1&p=589157244&a=3203588&t=519264320&so=2&bso=10&sd=0&f=assigned%3DUz5KkG0ZeO1Q&st=space-441356195
https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=790444932&c=list&vid=-1&p=589157244&a=3203588&t=574678930&so=2&bso=10&sd=0&f=assigned%3DUz5KkG0ZeO1Q&st=space-441356195
Locally

Added tags and fixed header

---

components/NewsletterForm/NewsletterForm.vue

Would close [this ticket](https://www.wrike.com/open.htm?id=773985506) if proposed solution is approved.
URL of the form is changed to the new https://mailchi.mp/199fe3626d97/signup and the form on the front end is removed. **This must be approved [here](https://www.wrike.com/open.htm?id=773985506) before merging.**
| Before      | After       |
| ----------- | ----------- |
| ![Screenshot from 2022-01-18 13-47-23](https://user-images.githubusercontent.com/4764217/149940316-c7e626b5-f519-48d5-ad0e-5d9ab3adbb8b.png) | ![Screenshot from 2022-01-18 13-47-08](https://user-images.githubusercontent.com/4764217/149940346-dbb2e589-0fe8-493d-81fd-312fc1f37335.png) |
Manual test

Changed newsletter URL and removed form inputs

---

package.json
yarn.lock

Uses the latest versions of map vuer and components which fix the issue with disappearing icons.
Manually tested here - https://mapcore-demo.org/current/sparc-app/

Update dependencies which fixes issue with icons disappearing.

---

components/DatasetDetails/DatasetFilesInfo.vue
components/FacetMenu/FacetLabel.vue
components/FacetMenu/FacetRadioButtonDateCategory.vue
components/FacetMenu/NewsAndEventsFacetMenu.vue
package.json
pages/data/index.vue
pages/datasets/_datasetId.vue
yarn.lock

Added the ability to filter events by type to the events tab
Locally

Filter events by type

---

package.json
pages/maps/index.vue
yarn.lock

Now integrated with mapvuer 0.2.5 which uses alogolia for knowledge  query.
It has been internally tested and the feature can be tested on the following link - https://mapcore-demo.org/current/sparc-app/maps/

Use version 0.2.5 of mapvuer which uses algoloia for knowledge query.

---

pages/maps/index.vue

A quick fix on setting the sparc api location on mapvuer.
Manually tested.

Fix map vuer API location.

---

components/FilesTable/FilesTable.vue
components/PageHero/PageHero.vue

Reverting back to starting the files tab in the files folder in order to adhere to the Dataset SDS
Locally

Remove home folder from files tab

---

components/CommunitySpotlight/CommunitySpotlightListings.vue
components/DatasetCitations/ApaCitation.vue
components/DatasetDetails/DatasetCitationsInfo.vue
components/Resources/ResourcesSearchResults.vue
components/SearchForm/SearchForm.vue
components/SearchResults/EventSearchResults.vue
pages/data/index.vue

Created full citations for citations tab. Also fixed bug in filtering tools and resources as well as added text for when no results are returned for a search query
Locally

Create full citations

---

components/DatasetCitations/ApaCitation.vue

Fixed bug where a single author would be pre-pended with an 'and '. Also capitalized the first letter of authors names
Locally

Fixed author citation bug

---

components/FacetMenu/DatasetFacetMenu.vue
components/FacetMenu/FacetCategory.vue
components/FacetMenu/FacetLabel.vue
components/FacetMenu/FacetRadioButtonCategory.vue
components/FacetMenu/NewsAndEventsFacetMenu.vue
components/FacetMenu/SparcInfoFacetMenu.vue
components/FacetMenu/ToolsAndResourcesFacetMenu.vue
components/SearchResults/DatasetSearchResults.vue
components/footer/Footer.vue
components/header/Header.vue
package.json
yarn.lock

Close facet menu by default and add publication date to datasets metadata
Locally

Sprint 18 wrike tickets

---

package.json
yarn.lock

Update the map viewer and flatmap viewer packages which contain fix on the name of the icon class from icon* to mapicon-icon*
This is deployed and tested on https://mapcore-demo.org/current/sparc-app/

Fix clashing class name with updated Map and flatmap viewer.

---

components/CommunityAnnouncements/CommunityAnnouncementItem.vue
components/CommunityAnnouncements/CommunityAnnouncementListings.vue
components/CommunitySpotlight/CommunitySpotlightItem.vue
components/CommunitySpotlight/CommunitySpotlightListings.vue
pages/news-and-events/community-spotlight/community-announcements/index.vue
pages/news-and-events/community-spotlight/fireside-chats/index.vue
pages/news-and-events/community-spotlight/index.vue
pages/news-and-events/community-spotlight/success-stories/_id.vue
pages/news-and-events/community-spotlight/success-stories/index.vue
pages/news-and-events/index.vue

This is a sprint 17 ticket defined here:
https://www.wrike.com/open.htm?id=678413958
A preview of this branch can be viewed here:
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight
Changes:
- Split community spotlight into fireside chats, success stories and community spotlights
- Added the success stories page back 
- Created a 'Fireside chats' page, which displays all available fireside chats. This is a new content model called 'Fireside Chats' on contentful
- Created a 'Community Announcements' page, which displays news items. This pulls content from the 'news' content model on contentful
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight/fireside- …

Sprint 17 success stories

---

components/DatasetCitations/ApaCitation.vue
components/DatasetDetails/DatasetHeader.vue

Updated dataset details header primary publication to be apa style citation
Locally

updated header citation to be apa style

---

components/DatasetDetails/DatasetDescriptionInfo.vue
components/EventCard/EventCard.vue
components/SparcPill/SparcPill.vue

Wrike ticket fixes for dataset details metadata and sparc pill being truncated
Locally

Wrike ticket fixes

---

components/ImagesGallery/ImagesGallery.vue

Map the modified thumbnail identifier for scaffold information.
Manually with dataset 76.

Map the modified thumbnail identifier for scaffold information.

---

components/ContactUsForms/GeneralForm/GeneralForm.vue

Attempts to close https://www.wrike.com/open.htm?id=656177298
* Adds * to email input to signal that it is required
* Small modifications in the labels
Manual testing

Added required * to email input in general feedback form

---

pages/index.vue

Added button linking to documentation hub on homepage
ran locally
verified the button opens the correct page

added button on homepage

---

pages/signup/index.vue

Added a missing / in url path in the hopes that this is the issue with redirect not working
Locally

made url path fix

---

package.json
yarn.lock

The latest map vuer includes update on the simulationvuer which now fetch the data from a dataset for UI customizations and other settings.
API update - https://github.com/nih-sparc/sparc-api/pull/67 is required for this to function properly.
Manually tested and can be tested using this link here - https://alan-wu-sparc-app.herokuapp.com/maps?id=3947c382

Use the latest version 0.2.6 of mapintegratedvuer.

---

package.json
yarn.lock

Design System Version Bump
Locally

updated design system version

---

components/FacetMenu/DatasetFacetMenu.vue
components/header/Header.vue
pages/data/index.vue

Fixed bug where clicking on 'find data' tab after being on it caused results to not show
Locally

fixed naviation error

---

components/header/Header.vue

Route was named incorrectly
Locally

fixed bug in named route

---

package.json
yarn.lock

Implemented /maps page sidbar feedback from gazelle:
- Added a help tooltip for how filters work
- Added a 'Data types' filter
Wrike ticket:
https://www.wrike.com/open.htm?id=867443442
This has been tested by myself and @alan-wu. 
I don't have a heroku-app running for this one but please test by running this branch locally. (Don't forget to run `yarn install` after pulling the branch!)

Update mapintegratedvuer with new version of sidebar

---

components/FilesTable/FilesTable.vue
pages/data/utils.ts
pages/help/index.vue
pages/news-and-events/model.ts

Adds term replacement for News & Events search too
- Bug fix (non-breaking change which fixes an issue)
Manual testing

Contentful term replacement

---

components/CitationDetails/CitationDetails.vue
components/ImagesGallery/ImagesGallery.vue
package.json
pages/datasets/_datasetId.vue
pages/datasets/flatmapviewer/_id.vue
yarn.lock

- Add text explaining citations
- Rename 'Citations' tab to 'References'
- When opening flatmaps from imageGallery, primary species of dataset is now used
A clone of this branch is available at:
https://jesse-sprint-19.herokuapp.com/
link:
https://www.wrike.com/open.htm?id=830385307
Added a body beneath the header with some text:
View at:
https://jesse-sprint-19.herokuapp.com/datasets/225?type=dataset&datasetDetailsTab=cite
link:
https://www.wrike.com/open.htm?id=854433155
Renamed 'Citations' tab on /dataset page to 'References'
link:
https://www.wrike.com/open.htm?id=844804093
- Updated imageGallery to only show cards with data
- Fix for imageGallery crashing when dataset has no uberon
- Pass Algolia filters into scicrunch data to know which species to use
View at: …

Sprint 19 jesse

---

pages/data/utils.ts

See title
- New feature (non-breaking change which adds functionality)
Manually

Added osparc -> o²S²PARC to the list of Contentful search replacements

---

components/ReadmeDoc/ReadmeDoc.vue
pages/help/index.vue

Added an additional help section for readme migration results when a user searches the help page
Locally

Added help search results for readme.io

---

components/header/Header.vue
nuxt.config.js

I forgot env variables are always interpreted as strings. Fixed logic to make feature flag work
Locally

check for string

---

components/header/Header.vue

Reversed logic and added flag for mobile view
Locally

fixed logic and added flag for mobile view

---

pages/datasets/_datasetId.vue

Fix a bug causing SciCrunch data not load correctly on dataset page as reported here - https://www.wrike.com/open.htm?id=546448956.
I have tested this locally.

Fix a bug causing scicrunch data to fail in dataset page.

---

pages/help/index.vue

Sprint 19 QA period fix, to be merged into master during the QA period.
Updated the tooltip and category wording from Readme to Documentation Hub
Locally

Updated wording for readme help results

---

components/ContributorItem/ContributorItem.vue

Display contributor name and orcid id when orcid service is down
Locally

Updated contributor tooltip

---

components/DatasetDetails/DatasetDescriptionInfo.vue
components/DatasetDetails/DatasetFilesInfo.vue
components/FilesTable/FilesTable.vue
nuxt.config.js
package.json
pages/file/_datasetId/_datasetVersion/index.vue
plugins/tsviewer.js
store/index.js
store/user/index.js
yarn.lock

Pull tsviewer library into sparc-app and allow a logged in user to view it
Locally via dataset 214

Ts viewer changes

---

components/SetupNewUser/SetupNewUser.vue
nuxt.config.js
services/auth.js

Updated env var to pull from .io which i missed in my last login change

Updated Env Var to pull from pennsieve.io

---

components/FilesTable/FilesTable.vue

Added the open timeseries viewer icaon action to the files table
Locally by updating env var: PENNSIEVE_DISCOVER_API_HOST = https://api.pennsieve.net/discover and using dataset 4982

Added open timeseries viewer icon to actions

---

components/header/Header.vue
pages/help/_helpId.vue
pages/help/index.vue

Removing the help page and redirecting any calls to /help to the documentation hub
Locally

removed help page and redirected to documentation hub

---

components/Tombstone/Tombstone.vue
pages/data/utils.ts
pages/datasets/_datasetId.vue

Now showing a tombstone page If a dataset has been uppublished
Locally via datasets 111 and 79

Created tombstone page for unpublished datasets

---

pages/file/_datasetId/_datasetVersion/index.vue

Fix for https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=926618960&pid=467258635&cid=441356195
Used the same way downloads are executed with the download file icon in the FilesTable, by adding an invisible zip form to the page
Locally

Fixed broken download links

---

components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ContactUsForms/NewsletterMixin.js
pages/user/profile/index.vue

Added the ability for a user to subscribe/un-subscribe from the SPARC newsletter via their profile page
Locally

Added subscribe option to profile page

---

pages/news-and-events/community-spotlight/community-announcements/index.vue
pages/news-and-events/community-spotlight/fireside-chats/index.vue
pages/news-and-events/community-spotlight/index.vue
pages/news-and-events/community-spotlight/success-stories/_id.vue
pages/news-and-events/community-spotlight/success-stories/index.vue
pages/news-and-events/model.ts

Sort items on community spotlight by their publishedDate. The ticket can be found here - https://www.wrike.com/open.htm?id=915420218
This has been tested and can be checked here - https://alan-wu-sparc-app.herokuapp.com/news-and-events/community-spotlight

Sort the items on the community-spotlight page by publishedDate order.

---

components/VersionHistory/VersionHistory.vue
pages/datasets/_datasetId.vue

We are now taking into account multiple versions when handling changelogs
Locally with dataset 247

fixed error in changelog request logic

---

mixins/fetch-pennsieve-file/index.js
pages/file/_datasetId/_datasetVersion/index.vue

Important!
There was typo in #500 where some parentheses are missing.
A lot of files on the /file page will crash without this change
Run locally will be available at:
https://context-cards-demo.herokuapp.com/file/221/3?path=files%2Fderivative%2Fsub-M16%2Fsam-pCm16%2Fdigital-traces%2FpC%20PHPS%20XFP%20M16%2020XZ%20180425_180524.xml
in 10 minutes

Add some missing brackets, add check for fileType

---

package.json
yarn.lock

Update mapintegratedvuer which now allows customisation on the latest changes message on the flatmap.
This has been tested locally and here https://alan-wu-sparc-app.herokuapp.com/maps

Update mapintegratedvuer with flatmap changes

---

components/CommunitySpotlightForm/CommunitySpotlightForm.vue
components/NewsAndEventsForm/NewsAndEventsForm.vue
mixins/file-upload/index.js
pages/news-and-events/community-spotlight/submit/index.vue
pages/news-and-events/submit/index.vue

Created submission forms for both news/events and success stories/fireside chats as per the wireframes here: https://app.abstract.com/share/80fd63dd-eee3-4bb6-9578-284f19eb868b
Locally

Create news and events submit page

---

components/header/Header.vue

Updated the search nav bar to work with the new news/event page refactor
Locally

Updated the search navigation

---

components/ImagesGallery/ImagesGallery.vue
pages/datasets/_datasetId.vue

Added the timeseries gallery item to the dataset gallery
Locally via dataset 214

Added timeseries gallery item

---

pages/datasets/timeseriesviewer/index.vue

Added breadcrumb for navigation purposes
Locally via dataset 214

added breadcrumb to timeseries viewer page

---

package.json
yarn.lock

Update scaffoldvuer and mapintegratedvuer which fixes a bug when rendering the 3D colon scaffold on dataset 259.
The scaffold on this test page should render correctly https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?dataset_id=259&dataset_version=3&file_path=files%2Fderivative%2Fcolon_hrm_metadata.json

Update scaffoldvuer and mapintegratedvuer

---

components/DataUseAgreementPopup/DataUseAgreementPopup.vue
components/DatasetDetails/DatasetActionBox.vue

Added the data use agreement for requesting embargoed data. A user must now accept the agreement before requesting access to embargoed data. 
Locally

Added data use agreement popup

---

components/FacetMenu/CommunitySpotlightFacetMenu.vue
pages/news-and-events/community-spotlight/index.vue

Added facets as per: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=964949103&pid=416152743&cid=415614298
Locally

Added facets for community spotlight page

---

components/FacetMenu/CommunitySpotlightFacetMenu.vue

Removed facet in order to be consistent with homepage facets
Locally

Removed Pancreas from facets

---

components/FacetMenu/FacetRadioButtonDateCategory.vue

Fixed invalid request being sent on firefox for news/events date facets
Locally

Fixed locale issue with Date constructor

---

components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
pages/news-and-events/events/_eventId/event-details/index.vue
pages/news-and-events/events/_id.vue

Fixed styling issues that appeared while migrating help documents to event/event details pages before promoting to prod
Locally

Fixed CSS for event and event details pages

---

components/FacetMenu/DatasetFacetMenu.vue

Fixed logic for showing categories in dataset facet menu
Locally

fixed visible categories bug

---

components/NewsAndEventsForm/NewsAndEventsForm.vue
components/ToolsAndResourcesForm/ToolsAndResourcesForm.vue
components/ToolsAndResourcesForm/questions.js
pages/resources/index.vue
pages/resources/submit/index.vue

Created submission page for tools and resources so that we no longer have to use: https://www.wrike.com/frontend/requestforms/index.html?token=eyJhY2NvdW50SWQiOjMyMDM1ODgsInRhc2tGb3JtSWQiOjQ1Mjg4MX0JNDc3NjMzODM2NzUxMAk3MThkYTgzMDA5NTA4OGE1YmQ1YzdiZmQzY2YyZTA4MTQ4ZDQyNDhkYWFjZTU0OTMxN2U0ZmQ5MTAzYmY0MWRh
Locally

Created tools and resources submission page

---

components/Resources/ResourcesSearchResults.vue

Centered the image for tools and resources search results
Locally

Updated image placement for T&R search results

---

components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ContactUsForms/questions.js
components/ResourcesGallery/ResourceCard.vue
components/ToolsAndResourcesForm/ToolsAndResourcesForm.vue
pages/contact-us/index.vue

Addressed the following backlog tickets:
- https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=935731409&pid=416152743&cid=415614298
- https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=939522880&pid=416152743&cid=415614298
Also updated t&r form to use validators for dynamic field validation
Locally

Backlog wrike tickets

---

components/SortMenu/SortMenu.vue
package.json
pages/news-and-events/index.vue
pages/resources/index.vue
yarn.lock

Updated font-weight for sort results menu and pagination menu
Updated news and events to use h2 headings instead of h1
Locally

Addressed Dominic's review comments

---

components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/DatasetDetails/DatasetActionBox.vue
components/DatasetDetails/DatasetFilesInfo.vue
pages/datasets/timeseriesviewer/index.vue

Updated requesting ebargoed dataset styling and functionality as well as contact us forms
Locally

Addressed last minute requests

---

components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ToolsAndResourcesForm/ToolsAndResourcesForm.vue

There appears to be an issue loading design system components on first load on staging when navigating directly to: https://staging.sparc.science/resources/submit
This is an attempt to patch the issue until I can figure out exactly why it is an issue. I believe it has something to do with the system design plugin being a client plugin and the app being served via SSR 
Could not reproduce the issue locally, so I will test on staging

Patch for design system issue

---

components/VersionHistory/VersionHistory.vue

Added a few details to the changelog to make it clearer
https://www.wrike.com/open.htm?id=947150591
Tested locally, will have herokuapp here soon:
https://jesse-sprint-23.herokuapp.com/maps

Implement feedback on changelog display

---

components/ContactUsForms/BugForm/BugForm.vue
components/DatasetDetails/DatasetFilesInfo.vue
components/header/Header.vue
pages/contact-us/index.vue

As per decisions made in the CCB Meeting, I made the following fixes:
-Opened Help page in new tab
-Prefill bug form 'problematic url' property with prior URL that navigated to the form from
-Remove the word 'raw' from download option 1 text
Locally

Addressed CCB Meeting fixes requests

---

components/VersionHistory/VersionHistory.vue

While implementing Hugh's feedback I accidentally forget the 'this' keyword
- [] I have added unit tests that prove my fix is effective or that my feature works

Add missing 'this'

---

components/DatasetDetails/DatasetActionBox.vue
components/DatasetDetails/DatasetFilesInfo.vue
components/FilesTable/FilesTable.vue
pages/contact-us/index.vue

Updated the workflow as per: https://www.wrike.com/workspace.htm?acc=3203588#/inbox/task/768983815
Locally

Updated embargo request workflow

---

components/FacetMenu/FacetLabel.vue
package.json
yarn.lock

Updated design system and date labels to have the category label clickable as per: https://www.wrike.com/open.htm?id=970448610
Locally

Made facet category label clickable

---

components/ContactUsForms/GeneralForm/GeneralForm.vue
components/DatasetDetails/DatasetFilesInfo.vue

Updated general form to mimic bug form and removed the word 'raw' from files
Locally

Wording fixes in preparation for promotion

---

components/DatasetDetails/DatasetAboutInfo.vue
components/DatasetDetails/SimilarDatasetsInfoBox.vue
pages/datasets/_datasetId.vue

Pulling award ID from Algolia field instead of from Pennsieve API
Locally via dataset 274 and 230

Award Id now getting pulled from Algolia

---

components/ContactUsForms/BugForm/BugForm.vue
mixins/file-upload/index.js

Added file selection component to bug form
Locally

Add ability to attach screenshot to bug form

---

nuxt.config.js
package.json
yarn.lock

Update to the latest Mapintegratedvuer with the following changes:
Update to the latest Flatmaps.
Greatly improved Scaffold Viewer performance.
This has been deployed on this instance: https://mapcore-demo.org/staging/flatmap-update-sparc-app/maps/

Mapintegratedvuer update

---

components/LoginModal/LoginModal.vue
nuxt.config.js
pages/resources/index.vue
pages/user/profile/index.vue

Updated login modal to match: https://docs.google.com/document/d/1z5u0BlFr91XWAnUcVgAvfervSbACnMqeVl5rd6Fvk-8/edit#
Fixed tools and resources page bug
fixed link to pennsieve
Locally

Update portal login and profile

---

components/DatasetDetails/DatasetDescriptionInfo.vue
components/DatasetDetails/DatasetFilesInfo.vue
pages/news-and-events/index.vue
pages/user/profile/index.vue

Updated newsletter link as per: https://www.wrike.com/open.htm?id=1012847449
Added Embargoed link as per: https://www.wrike.com/open.htm?id=949409292
Locally

Fixed past newsletter link and added embargo link

---

components/FeaturedData/FeaturedData.vue
components/LatestNewsAndEvents/LatestNewsAndEvents.vue
components/PortalFeatures/PortalFeatures.vue
components/ProjectsAndDatasets/ProjectsAndDatasets.vue
pages/index.vue

Updated styling to better match wireframes here: 
https://app.abstract.com/share/8fd9e602-3046-46b4-8bb2-aba8df60c4c9
Locally

QA Fix for homepage redesign

---

components/CommunitySpotlightForm/CommunitySpotlightForm.vue
components/ContactUsForms/BugForm/BugForm.vue
components/NewsAndEventsForm/NewsAndEventsForm.vue
components/ToolsAndResourcesForm/ToolsAndResourcesForm.vue

QA Fix: Updated form templates and request to use type identifier for /tasks endpoint to address comments on: https://www.wrike.com/open.htm?id=968626221
Locally

QA Fix: Update forms

---

components/NewsAndEventsForm/NewsAndEventsForm.vue

Updated the request sent to /tasks endpoint to be more specific for whether we should create a news or event ticket
Locally

QA Fix Updated news and events form request

---

components/CommunitySpotlight/CommunitySpotlightListings.vue
components/FacetMenu/RadioDateOption.vue
components/FacetMenu/ToolsAndResourcesFacetMenu.vue
components/FeaturedEvent/FeaturedEvent.vue
components/LatestNewsAndEvents/LatestNewsAndEvents.vue
components/SparcCard/SparcCard.vue
pages/news-and-events/index.vue
pages/resources/biological/index.vue
pages/resources/databases/index.vue
pages/resources/devices/index.vue
pages/resources/index.vue
pages/resources/information-services/index.vue
pages/resources/software/index.vue
pages/resources/utils.ts

These are fixes for the following tickets that were made and could not be merged in until completion of the QA period:
https://www.wrike.com/open.htm?id=1008784737
https://www.wrike.com/open.htm?id=983267788
https://www.wrike.com/open.htm?id=1015155108
https://www.wrike.com/open.htm?id=987473506
https://www.wrike.com/open.htm?id=966569789
Locally

Sprint 25 changes made during QA period

---

components/CommunitySpotlightForm/CommunitySpotlightForm.vue
components/ContactUsForms/BugForm/BugForm.vue
components/NewsAndEventsForm/NewsAndEventsForm.vue
components/ToolsAndResourcesForm/ToolsAndResourcesForm.vue
mixins/recaptcha/index.js
nuxt.config.js
package.json
yarn.lock

Added recaptcha to submission forms as requested by: https://www.wrike.com/open.htm?id=1014339519
Locally

Added google recaptcha to submission forms

---

package.json
yarn.lock

This update includes the following changes specified on the following tickets:
Flatmap provenance updates: https://www.wrike.com/open.htm?id=956430921
Simulation viewer updates: https://www.wrike.com/open.htm?id=688917633
Sidebar updates: https://www.wrike.com/open.htm?id=970446374
This has been tested locally and the following demo page  - 
https://mapcore-demo.org/current/sparc-app/maps
https://mapcore-demo.org/current/sparc-app/datasets/simulationviewer?id=135
https://mapcore-demo.org/current/sparc-app/datasets/simulationviewer?id=157

Flatmap viewer, Simulation viewer and map viewer update

---

components/StayConnected/StayConnected.vue

Tackles [this ticket](https://www.wrike.com/open.htm?id=1018012768)
The link to Open hours (help center) on the home page opens in a new tab
Manually

Open hours in main page opens in new tab

---

nuxt.config.js
pages/datasets/_datasetId.vue

Added seo tags for social cards as requested by: https://www.wrike.com/open.htm?id=988095518
Tested locally by installing the 'Social Share Preview' chrome plugin
Can be tested in prod via: https://developers.facebook.com/tools/debug

Added in tags for social cards

---

components/Paper/Paper.vue
components/Resources/SubmitToolSection.vue
pages/resources/biological/index.vue
pages/resources/databases/index.vue
pages/resources/devices/index.vue
pages/resources/information-services/index.vue
pages/resources/software/index.vue

Tackles [this ticket](https://www.wrike.com/open.htm?id=1014552144)
Adds a section/link to the submission form below the search results on every Tools & Resources search tab following [the design](https://share.goabstract.com/cedc18b8-68e3-4152-957b-8f25abf71f8d)
Manually

Submission section after Tools & Resources search

---

components/Resources/ResourcesSearchResults.vue
components/StayConnected/StayConnected.vue

Tackles [this ticket](https://www.wrike.com/open.htm?id=966743849)
* Shows owner (if present) on search result card
* Matches search terms to owner to return relevant results (was already working)
* Highlights owner if the there is a match against the search terms
* Extra: Removed icon from button as requested [here](https://www.wrike.com/open.htm?id=1018012768)
Manually

Tool author search

---

nuxt.config.js
pages/index.vue

Updated asset location for seo image header property and added secure image url property because Open Graph uses that for serving over HTTPS so it might be necessary for contentful images
Verified locally with Social Share Preview plugin, but to be verified on staging with FB debug tool

Updated seo headers

---

nuxt.config.js
pages/index.vue

Updated contentful image file to have a better aspect ratio for sharing images on social media
Locally via seo plugin

Updated social card image ratio

---

components/FacetMenu/FacetRadioButtonDateCategory.vue

Removed erroneous code in an effort to fix bug on safari where month is getting defined as NaN
Cannot test locally on Safari so I will test on staging

removed unnecessary code

---

components/Error/400.vue
components/Error/404.vue

Automatically populate the route in the bug form from the error page
For this ticket:
https://www.wrike.com/open.htm?id=1015147418
Ran locally

Add route to bug form on error pages

---

components/ContactUsForms/GeneralForm/GeneralForm.vue
nuxt.config.js
pages/index.vue

Added meta tags for twitter as per: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=988095518&pid=416152743&cid=415614298
And added recaptcha to help form as per: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=1014339519&pid=416152743&cid=415614298
Locally

Added metadata tag and recaptcha

---

components/NewsEventsResourcesPage/SubmitCommunitySection.vue
components/NewsEventsResourcesPage/SubmitNewsSection.vue
pages/news-and-events/community-spotlight/index.vue
pages/news-and-events/events/index.vue
pages/news-and-events/news/index.vue

Missing part of https://www.wrike.com/open.htm?id=1014552144
Manually

News&Events submission

---

components/NewsEventsResourcesPage/SubmitNewsSection.vue
components/Resources/ResourcesSearchResults.vue
components/SparcCard/SparcCard.vue
pages/resources/_resourceId.vue

QA fixes:
Added codethon pill as per: https://www.wrike.com/open.htm?id=966569789
and
Fixed featured event image as per: https://www.wrike.com/open.htm?id=1008784737
Locally

Sprint 25 CCB meeting QA fixes

---

components/NewsEventsResourcesPage/SubmitCommunitySection.vue

Fetches the text for the section from the new field in Contentful
Manually

Adding specific text to community spotlight search page section

---

components/SparcCard/SparcCard.vue

QA Fix for: https://www.wrike.com/open.htm?id=1008784737 
Locally

Fixed image resize on refresh

---

components/ProjectsAndDatasets/ProjectsAndDatasets.vue
components/ProjectsAndDatasets/ProjectsAndDatasetsCard/ProjectsAndDatasetsCard.vue

Fixed projects and datasets to accommodate resources as per: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=1014592446&pid=416152743&cid=415614298
Locally

Fixed projects and datasets components

---

pages/news-and-events/events/index.vue

Add upcoming sort option to events page as per: https://www.wrike.com/open.htm?id=1006654936
Locally

Added upcoming sort option

---

pages/news-and-events/events/index.vue

Added - to reverse direction for displayed 'upcoming' results
Locally

Reversed direction of displayed results

---

components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue

Also parsing markdown for title and summary (news page)

---

components/Breadcrumb/Breadcrumb.vue
components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
components/PageHero/PageHero.vue
mixins/marked/index.js

Handling of superindex in breadcrumbs + some styling for proper line height

Superindexes

---

components/FilesTable/FilesTable.vue
components/FilesTable/OsparcFileViewersDialog.vue
pages/file/_datasetId/_datasetVersion/index.vue

Handle opening/downloading files from buckets with different names
Locally

handle downloading from dynamic bucket names

---

components/EventListItem/EventListItem.vue
components/HomepageNews/HomepageNews.vue
components/SparcCard/SparcCard.vue
components/StayConnected/StayConnected.vue
nuxt.config.js
pages/index.vue
pages/news-and-events/events/index.vue

-Added a dividing line for past events as requested in: https://www.wrike.com/open.htm?id=1006654936
-Updated stay connected as requested in: https://www.wrike.com/open.htm?id=1064457928
-Updated featured news & events as requested in: https://www.wrike.com/open.htm?id=1014555865
Locally

QA fixes for sprint 26

---

components/EventListItem/EventListItem.vue

Updated Past Events opacity and fixed external url bug when one is not specified for the event
Locally

QA fix for event list item

---

components/footer/FooterLink.vue

Site feedback footer link now opens in new tab
Locally
- [ X] I have utilized components from the Design System Library where applicable

Fix footer link not opening in new tab

---

components/ContactUsForms/UserContactFormItem.vue

Auto-populate contact form item inputs with logged in user info
Locally

Auto populate contact form item

---

components/ContactUsForms/UserContactFormItem.vue

When auto populating input fields during log in we must emit a change event to update the parent upon initial render. Otherwise if the fields are not touched by the user then we submit the forms with empty contact info
Locally

Fixed contact form submission bug

---

components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/CommunitySpotlightForm/CommunitySpotlightForm.vue
components/ContactUsForms/FeedbackForm/FeedbackForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ContactUsForms/InterestForm/InterestForm.vue
components/ContactUsForms/NewsAndEventsForm/NewsAndEventsForm.vue
components/ContactUsForms/ResearchForm/ResearchForm.vue
components/ContactUsForms/ToolsAndResourcesForm/ToolsAndResourcesForm.vue
components/ContactUsForms/UserContactFormItem.vue
components/FacetMenu/NewsFacetMenu.vue
components/header/Header.vue
pages/about/sparc-portal/metrics/index.vue

Deselected subscribe by default for contact forms and swapped the order of metrics tabs
Locally

made updates requested from CCB

---

components/Metrics/UserBehaviors.vue

updated text from last 3 months to last quarter
Locally

Updated metrics text

---

components/DatasetDetails/DatasetDescriptionInfo.vue
components/DatasetDetails/SimilarDatasetsInfoBox.vue
components/FacetMenu/DatasetFacetMenu.vue
components/SetupNewUser/SetupNewUser.vue
middleware/verifyUserProfileComplete.js
mixins/marked/index.js
pages/index.vue
utils/awsExports.js

Addresses the following wrike tickets by opening a facet category when a tag facet is selected, opening help center hyperlinks in a new tab, and aligning contributers names correctly in firefox: 
https://www.wrike.com/open.htm?id=1051034019
https://www.wrike.com/open.htm?id=1053551028
https://www.wrike.com/open.htm?id=1062781871
Locally

Contributors name and dataset tag

---

components/FacetMenu/DatasetFacetMenu.vue
nuxt.config.js

Added SPECIES to available facets for computational and anatomical dataset searches
https://www.wrike.com/open.htm?id=1080628946
Manually

Added SPECIES to available facets for computational and anatomical dataset searches

---

components/DatasetDetails/DatasetAboutInfo.vue

About's tab DOI link opens in same tab
https://www.wrike.com/open.htm?id=1053565812
Manually

About's tab DOI link opens in same tab

---

components/DatasetDetails/SimilarDatasetsInfoBox.vue
components/FacetMenu/DatasetFacetMenu.vue
components/FacetMenu/TagsContainer.vue
package.json
pages/data/utils.ts
yarn.lock

Added hierarchal facets for the anatomy category as requested in: https://www.wrike.com/open.htm?id=1082362713
Locally via the k-core_curation algolia index

Heirarchal facets

---

nuxt.config.js
pages/resources/osparc-services/index.vue

Following CCB meeting requests
* Added pagination to service list
* Added empty results text
Manually (please test again)

oSPARC services - Pagination

---

package.json
yarn.lock

Update beta text display in Map viewer based on the following feedbacks. Hyperlinks have been added to some of the text.
I have tested this on locally deployed instance.
It can be tested here - https://alan-wu-sparc-app.herokuapp.com/

Update beta text in mapviewer.

---

package.json
yarn.lock

Update map-viewer with fixes on the beta texts do not disappear when it should in some occasion.
I have tested this on locally deployed instance.
It can be tested here - https://alan-wu-sparc-app.herokuapp.com/

Fix an issue with beta text not disappearing

---

package.json
pages/maps/index.vue
yarn.lock

Fix missing minimap for AC maps and use uberon id for highlighting organs part when going from the gallery viewer.
This is tested here - https://alan-wu-sparc-app.herokuapp.com/
Going to the flatmap using the gallery Pelvic splanchnic nerve item from dataset 206 should display the nerve only and not anything else.

Fix missing minimap and use uberon for gallery to flatmap

---

pages/about/get-involved/index.vue
pages/about/index.vue
pages/about/team-and-leadership/index.vue
pages/about/what-we-offer/index.vue

Updated styling for about pages to reflect the design system
Locally

Fixing about pages styling

---

components/Gallery/GalleryItems/MetricsCard.vue
pages/about/index.vue

Updated the about page metrics to reflect the wireframes here: https://app.abstract.com/share/6289d547-1ded-46c8-9e91-fd258af89577?collectionId=47ca6f29-a947-4809-ac1c-3f987863cf63&collectionLayerId=0c3a2780-08c5-4357-9d93-e8b3828e9601&present=true&preview=false&sha=2316f609bfb651b216c746de440d53890591442f
Locally

Updated about page metric to show total downloads

---

nuxt.config.js
pages/about/index.vue
pages/about/metrics/index.vue

Update metrics endpoint to use prod
Locally

Updated endpoint

---

components/VersionHistory/VersionHistory.vue

Missed this small ask after completing doi redirection work for https://www.wrike.com/open.htm?id=1064229437. Removed link from versions column
Locally

removed hyperlink from version column

---

components/FacetMenu/NewsFacetMenu.vue

Added portal update facet as requested in: https://www.wrike.com/open.htm?id=1064440707
Locally

Added portal update facet

---

components/FilesTable/FilesTable.vue

Fixed the file link mentioned in: https://www.wrike.com/open.htm?id=1022717404
Locally

add msword to content types

---

layouts/default.vue
nuxt.config.js
store/index.js
store/layouts/default.js

Add notification message as requested in: 
https://www.wrike.com/open.htm?id=1151922515
Locally

Added portal notification message

---

components/EventListItem/EventListItem.vue
components/HomepageNews/HomepageNews.vue
components/NewsListItem/NewsListItem.vue
components/footer/FooterLink.vue
mixins/marked/index.js
nuxt.config.js

Added bitly link checks so that bitly links behave correctly as requested in: https://www.wrike.com/open.htm?id=1146564215
Locally

Added check for bitly links in news and events

---

components/CommunitySpotlight/CommunitySpotlightItem.vue
components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
components/Resources/ResourcesSearchResults.vue
components/Resources/ServicesSearchResults.vue
components/SparcCard/SparcCard.vue
pages/datasets/timeseriesviewer/index.vue
pages/news-and-events/community-spotlight/index.vue
pages/news-and-events/events/_eventId/event-details/index.vue
pages/projects/_projectId.vue
pages/resources/biological/index.vue
pages/resources/databases/index.vue
pages/resources/devices/index.vue
pages/resources/information-services/index.vue
pages/resources/osparc-services/index.vue
pages/resources/software/index.vue

Addressed some image display issues voiced by Sue in reference to this ticket: https://www.wrike.com/open.htm?id=796365970
Also addressed some CSS issues for tools and resources search results
Locally via Chrome and Firefox

Fixed Images and CSS for different pages and components

---

package.json
pages/maps/index.vue
yarn.lock

This map-viewer update brings the following new features to the map app:
- [Use one single search for on display search.](https://github.com/ABI-Software/mapintegratedvuer/pull/167)
- [Open new FC/AC/Whole body map with new UI in the map display.](https://github.com/ABI-Software/mapintegratedvuer/pull/170)
- [Support dynamic markers on the FC map.](https://github.com/ABI-Software/mapintegratedvuer/pull/169)
- [Add hierarchical control (FC map) and species information (AC maps).](https://github.com/ABI-Software/flatmapvuer/pull/113)
[Cypress tests run successfully.](https://github.com/ABI-Software/mapintegratedvuer/actions/runs/5790975002)
New features can be tested [here](https://alan-wu-sparc-app.herokuapp.com/maps).

Update mapviewer to version 0.5.0.

---

components/FacetMenu/DatasetFacetMenu.vue
components/SparcCard/SparcCard.vue
pages/data/utils.ts
pages/user/profile/index.vue

Made changes to display the updated facets in algolia for heirarchal faceting. Also made a change to sparc card image and updated profile page request for published datasets
Locally

Heirarchal Facets changes and miscellaneous fixes

---

pages/data/utils.ts

Heirarchal facets bug fix
Locally

heirarchal facets fix

---

components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
pages/news-and-events/events/_eventId/event-details/index.vue
pages/news-and-events/news/_id.vue

Images for event details should only be as large as the uploaded dimensions
Locally

Event details page images fix

---

components/ToolAndResourcesPage/ToolsAndResourcesPage.vue
pages/projects/_projectId.vue

Centers and displays images at their uploaded size in the description fields as requested in: https://www.wrike.com/open.htm?id=796365970
Locally

Sprint 30 QA Fix

---

components/DatasetDetails/DatasetDescriptionInfo.vue
components/DatasetDetails/SimilarDatasetsInfoBox.vue
components/FacetMenu/DatasetFacetMenu.vue
package.json
yarn.lock

QA Fixes for the dataset details page metadata as well as facet selection for hierarchal facets
Locally

Heirarchal facets qa fix

---

components/DatasetDetails/SimilarDatasetsInfoBox.vue

Fixed bug found by Andre for determining the facet id for similar datasets
Locally

Fixed bug with getting facet id

---

components/DatasetDetails/DatasetActionBox.vue
components/DatasetDetails/DatasetFilesInfo.vue
nuxt.config.js

Added flag to hide sds viewer button as mentioned in: https://www.wrike.com/open.htm?id=1141951787
Locally

Added Env Var Flag for SDS Viewer

---

components/Gallery/Gallery.vue
pages/user/profile/index.vue

Populating the list of published datasets from Algolia instead of Pennsieve so that we are able to include all datasets that the user is a contributor on as requested in: https://www.wrike.com/open.htm?id=1176781755
Locally

Updated source for list of published datasets

---

components/FilesTable/OsparcFileViewersDialog.vue

Changes the text in the oSPARC file viewer dialog as described in https://www.wrike.com/open.htm?id=1183457890
Manually

oSPARC file viewers

---

pages/file/_datasetId/_datasetVersion/index.vue

The viewer (if available) is shown on top of the file's metadata as described [here](https://www.wrike.com/open.htm?id=955702860)

File details page: viewer on top

---

components/DataUseAgreementPopup/DataUseAgreementPopup.vue
components/DatasetDetails/DatasetFilesInfo.vue
pages/datasets/_datasetId.vue

Updated the data use agreement to pull from pennsieve instead of hardcoded and fixed the request being sent from the portal to request embargoed access as requested in: https://www.wrike.com/open.htm?id=1157523513
Locally

Updated Request Embargo Access Feature

---

pages/maps/index.vue

Update maps landing page's banner text - https://www.wrike.com/open.htm?id=1171291579
This has been tested in my local instance and the updated text can be found on this page - https://alan-wu-sparc-app.herokuapp.com/maps

Update maps page's banner text.

---

components/DatasetDetails/DatasetFilesInfo.vue

Fixed issue with dataset details page
Locally

removed unnecessary failure message

---

pages/user/profile/index.vue

Null check for no submissions being returned
Locally

Added null check for submissions response

---

package.json
yarn.lock

This update of map viewer include the following changes:
- [Context cards have now been moved to individual pane and remove from the sidebar.](https://github.com/ABI-Software/mapintegratedvuer/pull/171)
- [Region in scaffold can now be selected](https://github.com/ABI-Software/scaffoldvuer/pull/116)
- [Markers can now be set on scaffolds](https://github.com/ABI-Software/scaffoldvuer/pull/118)
- [Fix a bug with neuron search on flatmapvuer](https://github.com/ABI-Software/flatmapvuer/pull/117)
- [Display nerves option in flatmapvuer](https://github.com/ABI-Software/flatmapvuer/commit/60c315e4a9923d62e7a149ad50c00351915cdd3a)
This has been tested manually and automatically here - https://github.com/ABI-Software/mapintegratedvuer/actions/runs/6216683458 .
I …

Increment mapintegratedvuer to version 0.6.0

---

package.json
yarn.lock

Small patch of mapintegratedvuer to make the new scaffold markers from #736 clickable
Tested locally and passed the mapintegratedvuer tests

Small patch for mapintegratedvuer - Scaffold markers now clickable

---

package.json
yarn.lock

QA Fixes:
- Fix spelling of SCKAN
- Scaffold marker colour now matches the fatmap marker colour
- Scaffold markers now clickable
Ran locally and checked issues are fixed

Update mapintegratedvuer with QA fixes:

---

components/AlternativeSearchResults/AlternativeSearchResultsNews.vue
nuxt.config.js
package.json
yarn.lock

Added nuxtjs/gtm dependency for gtm tracking
Locally

Add gtm scripts

---

components/ContactUsForms/BugForm/BugForm.vue
components/ContactUsForms/CommunitySpotlightForm/CommunitySpotlightForm.vue
components/ContactUsForms/FeedbackForm/FeedbackForm.vue
components/ContactUsForms/GeneralForm/GeneralForm.vue
components/ContactUsForms/InterestForm/InterestForm.vue
components/ContactUsForms/NewsAndEventsForm/NewsAndEventsForm.vue
components/ContactUsForms/ResearchForm/ResearchForm.vue
components/ContactUsForms/ToolsAndResourcesForm/ToolsAndResourcesForm.vue
components/ContactUsForms/UserContactFormItem.vue
components/Url/UrlInput.vue
components/Url/UrlList.vue
pages/contact-us/index.vue
pages/data/utils.ts

tackling https://www.wrike.com/open.htm?id=1161704527
* To prefill the forms, there has been a refactor in the forms, specially the one that takes the user data that's used in all the others.
Manually. But I am not super familiar with the forms so more testing is welcomed.

Prefill contact forms

---

components/Gallery/Gallery.vue
components/ImagesGallery/ImagesGallery.vue

There is a ticket for this here:
https://www.wrike.com/open.htm?id=1205892938
The code change is just add a bit more context to the card descriptions

Fix confusing gallery titles

---

components/DatasetDetails/DatasetActionBox.vue

Updated text to reflect comments in: https://www.wrike.com/open.htm?id=1141951787
Locally

updated sds viewer text

---

pages/datasets/_datasetId.vue

Updated styling to match design system
Locally

updated content tab card styling

---

components/CitationDetails/CitationDetails.vue

Adding custom tracking event
Locally

adding custom gtm event

---

nuxt.config.js

Updated gtm config in an attempt to have custom event fire on staging
Locally, but need to verify on staging

updated gtm tag configuration

---

components/CallToAction/CallToAction.vue
pages/share-data/index.vue

Fixed some issues with the Share Data page after Ignacios initial changes
Locally

Fixed share data page

---

components/BfDownloadFile/BfDownloadFile.vue
components/CitationDetails/CitationDetails.vue
components/DatasetDetails/DatasetActionBox.vue
components/DatasetDetails/DatasetFilesInfo.vue
components/FilesTable/FilesTable.vue
pages/data/index.vue
pages/datasets/_datasetId.vue

Added remaining tags from: https://docs.google.com/spreadsheets/d/1wc4EZQmnlZkaEQ08rFxehsm_pLcdRTFP0sBQP0MClGE/edit#gid=0
Locally

Added remaining GTM tags

---

components/CallToAction/CallToAction.vue
components/LoginModal/LoginModal.vue
pages/index.vue
pages/share-data/index.vue
utils/homepageFields.js

Following [here](https://www.wrike.com/open.htm?id=1194150996)
* Added hero button to home page
* Added login modal from Share page call to action button
* Added `redirectUrl` to Login modal
Manually

Share page

---

components/header/Header.vue

Change in wording for the NavBar

Share Data -> Share with SPARC

---

components/DatasetDetails/DatasetFilesInfo.vue
components/header/Header.vue

Added custom download event and updated data and models tab route
Locally

added gtm custom event

---

components/ImagesGallery/ImagesGallery.vue

Small change to gallery card text
Requested here:
https://www.wrike.com/open.htm?id=1205892938

Rework flatmap card labels for QA feedbaack

---

pages/datasets/_datasetId.vue

Testing if resetting the dataLayer via reset() works for tracking metrics
Have to test on staging

test resetting dataLayer

---

pages/datasets/_datasetId.vue

Added a delay as requested by Tess
It will be tested by Tess on staging

Added delay to datalayer reset

---

package.json
pages/datasets/_datasetId.vue
pages/datasets/timeseriesviewer/index.vue
yarn.lock

Bumped package to include updated padding in content tabs
Locally

bumped sparc design system package

---

pages/datasets/_datasetId.vue

Test pushing to datalayer without event
Locally, to be checked by Tess on staging

testing datalayer push

---

components/BfDownloadFile/BfDownloadFile.vue
components/CitationDetails/CitationDetails.vue
components/DatasetDetails/DatasetActionBox.vue
components/DatasetDetails/DatasetFilesInfo.vue
components/FilesTable/FilesTable.vue
components/header/Header.vue
middleware/clearDatalayer.js
nuxt.config.js
pages/data/index.vue
pages/datasets/_datasetId.vue

Updated events to reflect what Tess wants. Added a middleware to clear the datalayer between page views
Locally via tag assistant

Updated gtm push events

---

components/BfDownloadFile/BfDownloadFile.vue
components/FilesTable/FilesTable.vue

Updated events to match: 
https://docs.google.com/spreadsheets/d/1wc4EZQmnlZkaEQ08rFxehsm_pLcdRTFP0sBQP0MClGE/edit#gid=0
Locally

Updated gtm event properties

---

package.json
yarn.lock

The changes are included in this pull request on map viewer repository- https://github.com/ABI-Software/mapintegratedvuer/pull/187
This has been tested extensively through the development cycle and also by the release process - https://github.com/ABI-Software/mapintegratedvuer/actions/runs/7162341253
This can also be tested on this site here - https://alan-wu-sparc-app.herokuapp.com/

Update map viewer to version 0.6.4

---

pages/datasets/file/_datasetId/_datasetVersion/index.vue

Added check in file page for if no biolucida data is returned when looking for the source package id
Locally via dataset 120 and 348

Added check for empty biolucida data

---

test/cypress/e2e/homepage.cy.js

Update the src link test assertion to avoid test failure caused by the difference of the generated src link.
Run locally with Cypress. Passed as expected.

fixed the homepage footer logo link test issue

---

package.json
yarn.lock

Update mapintegratedvuer with qa fix and updated 'whats new' text
Tested locally and is running here:
https://jesse-sprint-preview.herokuapp.com/

Update mapintegratedvuer with qa fix and updated 'whats new' text

---

components/FilesTable/FilesTable.vue
components/ImagesGallery/ImagesGallery.vue
components/PlotViewer/PlotViewer.vue
components/VersionHistory/VersionHistory.vue
components/ViewersMetadata/SegmentationViewerMetadata.vue
mixins/request-download-file/index.js
pages/datasets/file/_datasetId/_datasetVersion/index.vue
pages/datasets/imageviewer/_id.vue
pages/maps/index.vue
services/discover.js

Made changes to account for the s3 file path migration. s3 keys no longer include the version
Locally

Addressed changes required for s3 file path migration

---

test/cypress/e2e/userstories.cy.js

Fixed the failed tests [here](https://github.com/nih-sparc/sparc-app/pull/793#issuecomment-1878159228). Using specific datasets for each testing case to make sure tests still passed after new datasets have been added.
Updated tests are run by Cypress locally in MacOS.

using specific datasets for userstory testing

---

test/cypress/e2e/datasets.cy.js
test/cypress/e2e/finddata.cy.js
test/cypress/e2e/userstories.cy.js
test/cypress/support/commands.js

Testing is updated based on QC tickets from sprint 33.
- added gallery flatmap card check
- added field information check for abstract/about section
- optimised facet testing
- added new testing case (facet search when keyword search applied)
- merged single-facet search testing and multiple-facet search testing
- added redundant doi check for the reference section
- added contributor-related dataset check after clicking a contributor
Updated tests are run by Cypress locally in MacOS.

Update QC testing

---

components/FilesTable/FilesTable.vue
package.json
yarn.lock

Bumped design system to include fix for reset all and hid timeseries viewer icon on files table:
https://www.wrike.com/open.htm?id=1262170398
https://www.wrike.com/open.htm?id=1288216402
Locally

Bumped design system version and hid timeseries viewer icon

---

components/DatasetDetails/DatasetFilesInfo.vue
nuxt.config.js
pages/about/get-involved/index.vue
pages/about/index.vue
pages/about/team-and-leadership/index.vue
pages/about/what-we-offer/index.vue
pages/contact-us/index.vue
pages/index.vue
pages/news-and-events/community-spotlight/success-stories/_id.vue
pages/news-and-events/events/_eventId/event-details/index.vue
pages/news-and-events/events/_id.vue
pages/news-and-events/index.vue
pages/news-and-events/news/_id.vue
pages/resources/_resourceId.vue
pages/resources/index.vue
static/images/100013719.svg
test/cypress/e2e/datasets.cy.js

Ported over the following fixes from sparc-app-2:
https://www.wrike.com/open.htm?id=1265611047
https://www.wrike.com/open.htm?id=1267057344
https://www.wrike.com/open.htm?id=1241225415
Locally

Ported over Ignacio's fixes from sparc-app-2

---

package.json
pages/datasets/_datasetId.vue
yarn.lock

Bumped sparc-design-system version to incorporate a bug fix for categories with singular facets and updated the dataset details to get dataset info solely from the sparc-api endpoints in order to address: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=1326363804&pid=416152743&cid=415614298
Locally

HOTFIX: bumped version and updated dataset details endpoint

---

pages/about/index.vue
pages/about/metrics/index.vue
utils/common.js

Fix for the metrics page. Using the past 2 months instead of current and last since the current is always published at the end of the month
Locally

metrics page fix
