nih-sparc/sparc-app

- nuxt.config.js
- package.json
- yarn.lock
The purpose of this PR is to add robots.txt functionality to disallow all routes on all environments except for `production`.
- Run the app locally and visit http://localhost:3000/robots.txt
- You should see that everything is disallowed for all user agents.
> Add robots.txt functionality for environments

- components/PageHero/PageHero.vue
- components/header/Header.vue
During our PR merges yesterday, some of the `PageHero` styles got overwritten, specifically for the default styles. In addition, I removed the set height for the header as that was causing the body of the site to go under the header.
- Homepage hero should have large centered text, and a purple gradient background
- About page hero should be small left aligned text, and have a green gradient background
> Fix PageHero styles

- components/SearchFilters/SearchFilters.vue
- nuxt.config.js
- pages/data/index.vue
The purpose of this PR is to add functionality to dynamically load filters based on the search type. These filters are [in contentful as a Filter type](https://app.contentful.com/spaces/6bya4tyw8399/entries). I already created filters for each type, and we just need to fill in the categories and filters.
- The Datasets filters should be loaded
- Go to the Projects tab
- The Projects filters should be loaded
- Select some filters. They should show checked, and the checked filters should be displayed above the table.
- Go to the Organs tab
- Organs have no filters, so there should no nothing displayed (we don't have an empty state at the moment.)
> Dynamically load filters based on the search type

- components/header/Header.vue
- pages/data/index.vue
The purpose of this PR is to add the following for the header search component:
- Search functionality. This will take the user to the Find Data page, and search for datasets based on their input
- Hide on Find Data page
- Enter a search query in the header and click on the button
- You should be taken to the Find Data page, and you should be shown results for your query.
- The search form in the header should not be visible on the Find Data page
- Navigate to another page to reveal the search form in the header
> Header search - Search functionality, Hide on Find Data #4a7456 #4a9p8d

- components/SearchResults/FileSearchResults.vue
- pages/data/index.vue
The purpose of this PR is to add functionality for the images tab on the Find Data page.
Notable missing features:
- Empty state for no filters
- Ability to download a file
- Click on the Images tab
- You should see search results for the images, and all search functionality should work
- Click on a file's menu button, and select "Open Dataset"
- You should be taken to that dataset's landing page
> Find data - images #4a7q30

- assets/_base.scss
- assets/_layout.scss
- components/EventBannerImage/EventBannerImage.vue
- components/EventCard/EventCard.vue
- components/HelpCard/HelpCard.vue
- components/HelpSection/HelpSection.vue
- components/footer/Footer.vue
- pages/about/index.vue
- pages/data/index.vue
- pages/events/_eventId.vue
- pages/events/index.vue
- pages/help/_helpId.vue
- pages/help/index.vue
- pages/privacy/index.vue
- pages/resources/index.vue
- pages/terms-of-service/index.vue
The purpose of this PR is to fix and style the get help landing page and details pages. This functionality was broken due to some Contentful changes. 
- Go to the "Need Help" landing page by using the aux nav in the header
- You should see a list of help articles grouped by their sections.
- Click on one of the help article's headings to go to its details page
- You should see the help article's content wrapped in the Basic Page Layout.
> Help landing page and details page #4c6hvm

- pages/atlas/index.vue
The purpose of this PR is to have the atlas page use the basic page layout. This is an empty page and will be used for the Atlas component that the MAP Core is creating.
- Visit the Atlas page using the main navigation
- You should see the page in the basic page layout
> Atlas page use the basic page layout

- components/SearchResults/OrganSearchResults.vue
- nuxt.config.js
- pages/data/index.vue
- pages/organs/_organId.vue
The purpose of this PR is to add the logic for Find Data - Organs. Please note, the [columns for the search results are not yet defined](https://www.wrike.com/open.htm?id=452840115).
- Go to the Data page
- Go to the Organs tab
- One organ should load
- Click on the organ's name
- You should be taken to the organ's details page (this page has no functionality, and only serves as a dynamic route at the moment.)
> Find Data - Organs

- components/SearchFilters/SearchFilters.vue
- pages/data/index.vue
The purpose of this PR is to change where the active filters are displayed. This comes from the latest design changes.
- Click on the Filters button. Dialog should open.
- Select two of the filters.
- Click "Apply"
- Dialog should be closed
- Active filters should be displays above the table
- Click on one of the filter tags' X icon at the top to deselect it.
- The filters list should be updated, including the number of filters in the Filters button's label
- Click on thee Filters button
- Checked filters should be updated to reflect the filters you removed on the main page.
> Find data filters active filters change #4a9p4j

- pages/data/index.vue
The simulations tab uses the same DatasetSearchResults component as the Datasets tab.  It adjusts
the search url to search for datasets with the simcore tag instead of datasets in the
SPARC Consortium organization.
Closes #4a7r4t
The Find Data - Simulations tab should now work.
> feat(find data - simulations): add logic to handle Simulations tab

- .gitignore
- components/HelpCard/HelpCard.vue
- components/HelpSection/HelpSection.vue
- components/PageHero/PageHero.vue
- components/footer/Footer.vue
- components/help-search-controls/HelpSearchControls.vue
- nuxt.config.js
- package.json
- pages/help/index.vue
- pages/help/model.ts
- store/index.js
- tsconfig.json
- vue-shim.d.ts
- yarn.lock
This includes three commits, the first is a build change and the others are features.
1) Add typescript to the build process by following the nuxt documention.
2) Wire up the documentation search to filter all documentation based on the search term.
3) Wire up the footer to fetch copy from contentful.
You should be able to search for documentation, for instance if you type "Frequently Asked Questions" and then click go, all items other than the FAQ article will show.  If you click "Clear search", all articles should then come back.
> Typescript, Help Docs Search, Footer Copy

- components/header/Header.vue
The purpose of this PR is to remove the Atlas link from the main menu.
- Atlas should not be in the main menu on all viewports
> Remove Atlas from main menu

- components/Breadcrumb/Breadcrumb.vue
- components/DetailsHeader/DetailsHeader.vue
- components/HelpCard/HelpCard.vue
- components/HelpHero/HelpHero.vue
- components/help-search-controls/HelpSearchControls.vue
- pages/help/_helpId.vue
- pages/help/index.vue
- pages/help/model.ts
- pages/organs/_organId.vue
- pages/privacy/index.vue
- pages/terms-of-service/index.vue
The documentation detail page did not match the designs.  It was missing the page hero for searching documentation as well as a breadcrumb.
This PR creates a common Breadcrumb component to share with the Dataset detail page, and a common HelpHero component to share between the main help page and the documentation detail page.
For the HelpHero component, searches are executed by passing route query parameters instead of mutating component state.
The breadcrumb on the dataset detail page should still work.  The title for the Organ detail page should be fixed.
The documentation home page and detail pages should all have a functional search feature.  Please try navigating back/forward and make sure the content of the search box continues to match the route.
> Fix documentation detail header

- components/header/Header.vue
Adds an inline z-index to the `li` elements on the menu.  This isn't the most "correct" fix but it gets the job done.
Open the main page on a tablet screen width (1024px).  Make sure the "Events" part of the "News & Events" link is clickable.
> add z-index to menu links in case search bar overlays on tablet sizes

- components/FilesTable/FilesTable.vue
The purpose of this PR is to update the endpoint calls for the files table on the dataset details page, so that the starting point for displaying files is not `Root` but either `packages` or `files` depending on the schema version.
1. Navigate to Find Data > Datasets and select a dataset.
2. Navigate to the files tab. You should no longer see `Root` as the parent directory but `packages` or `files`, depending on whether the dataset schema version is less than 4.0 (display packages) or greater than 4.0 (display files).
3. Navigate through multiple datasets and test out the path functionality in the files table, making sure that the path is updated with the correct folder structure and that each individual path routes directly back to the right position in the folder hierarchy.
> Update Files Table Endpoint To Get Packages or Files #4gd1hz

- pages/data/index.vue
- pages/data/utils.ts
Refactors the filter transforms in typescript.  There are also lots of comments in the utils.ts file explaining some of the TS syntax which we can remove if we want.  I also left the original code commented out for comparison purposes.
The functionality should be exactly the same in all the Find Data pages.
> Clearer filter transforms

- pages/organs/_organId.vue
The purpose of this PR is to remove 3d-scaffold from organ details page.
- Go to an [organ detail page](http://localhost:3000/organs/2MyjbZVNRrJjLtRrpQ8DXc)
- The "3D Scaffold" tab should not be there
- The page should have no errors and functioning normally
> Remove 3d-scaffold from organ details page #4md0kb

- components/CookieNotice/CookieNotice.vue
The purpose of this PR is to fix a bug where the cookie notice wouldn't be overlaying the Find Data table.
- Delete the `GDPR:accepted` cookie
- Refresh the app and ensure the Cookie Notice is visible
- Go to Find Data
- The cookie notice should be overlaying all columns on the table
- Resize the viewport to go to the mobile version
- Open the mobile menu
- The mobile menu should overlay the cookie notice
> bugfix: cookie notice z-index

- pages/projects/_projectId.vue
The purpose of this PR is to fix the display issue with showing the organs on a project detail page. The way this content was stored on contentful was changed, and this PR addresses that.
- Click on "Projects"
- Visit a few projects and ensure that the organs are shown above the project's title. If there is no organ, this area should be empty.
> Show project section for project detail page

- pages/projects/_projectId.vue
The purpose of this PR is to add the banner image to the project details page from contentful. Please note that no images are in contentful yet and so there will be no images displayed on the pages until then.
Verify that the placeholder image on the project details page is no longer present and that the image data should now be coming from contenful.
> Project Details Header Image #4m8hjw

- components/Resources/ResourcesSearchResults.vue
The purpose of this PR is to fix the resources images to not stretch. In addition, I adjusted the bottom margin of the resource's heading to match the design.
- Go to the resources page
- All of the images should be a max of `128px` wide, with the height auto adjusting. The Protocols.io image was being stretched before.
> Resources - Fix resources images to not stretch

- pages/data/index.vue
The purpose of this PR is to preserve the search query when changing search types.
- Go to Find Data
- Search "heart"
- You should be seeing dataset results for "heart"
- Click on Filters
- Select a filter and apply filters
- Click on "Organs"
- You should be seeing organ results for "heart", and the filters should have been removed
> Find Data - preserve search query

- nuxt.config.js
- package.json
- yarn.lock
The purpose of this PR is to force HTTPS for production. This was done with the [redirect-ssl](https://github.com/nuxt-community/redirect-ssl) middleware.
`yarn nuxt` should run the devserver as normal. Testing for SSL will need to happen when deployed.
> Add redirect SSL middleware to force HTTPS

- components/DatasetDetails/DatasetAboutInfo.vue
- pages/datasets/_datasetId.vue
The purpose of this PR is to display the project Id associated with a dataset on the About tab of the dataset details page.
Navigate to a dataset details page. You should see the associated project Id/Sparc Award Id listed in the About Tab instead of the `Lorem Ipsum` text
> Dataset Details Sparc Award Id #4jczhk

- components/SearchResults/DatasetSearchResults.vue
- pages/datasets/_datasetId.vue
* Thumbnail and dataset title links in search page are now equal.
* Simulations and Dataset tabs are now the same.
* Made linter happy.
I tried both search results pages (datasets and simulations) and navigated to the detail pages to see that they work properly.
Tabs in simulations show the correct information.
> Simcore fixes

- components/DownloadDataset/DownloadDataset.vue
- components/shared/BfButton/BfButton.vue
- nuxt.config.js
The purpose of this PR is to update the `Get Dataset` dialog according to the [designs](https://app.abstract.com/projects/e709ca90-5ba9-11e9-9eaa-59df656d954a/branches/600d2375-3dd1-4940-97a6-bbec7a21f97e/collections/5e983fd9-e489-4e1a-a226-5bcc6679150d)
1. Navigate to a dataset that is less than 5 GB. 
2. Click on the `Get Dataset` button. The dialog that requests you to download the dataset should appear with the new designs. Click on `Download Dataset`. Dataset should be downloaded as expected.
3. Navigate to a dataset that is greater than 5 GB. 
4. Click on the `Get Dataset` button. The AWS dialog should appear with the new designs. Clicking on `Download to AWS bucket` should direct you to the help documentation related to this functionality.
> Get Dataset Dialog #4wawjx

- components/DownloadDataset/DownloadDataset.vue
- components/shared/BfButton/BfButton.vue
The purpose of this PR is to change the button language for the AWS version of the Download Dataset modal from `Download to AWS Bucket` and `Cancel` to `More Information` and `Okay`
Navigate to a dataset that is greater than 5GB. Click on the `Get Dataset` button. The buttons on the modal should reflect the changes above.
> Fix Download Dataset Buttons for AWS

- components/SearchResults/OrganSearchResults.vue
- components/header/Header.vue
- pages/data/index.vue
- pages/resources/index.vue
The purpose of this PR is to update the pagination limit to 10 for all search types on Find Data and for the Resources page.
- Go to Find Data
- Pages should be returning 10 results per page, for all types
- Go to Resources
- Pages should be returning 10 results per page, for all resource types.
> Update pagination limit to 10

- components/footer/Footer.vue
- nuxt.config.js
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
The purpose of this PR is to add the page hero to the news and events page. In addition, I removed the TOS link from the footer.
- Go to the [News and events page](http://localhost:3000/news-and-events)
- There should be a page hero at the top
> Add page hero to news and events page

- components/ImagesTable/ImagesTable.vue
- nuxt.config.js
- pages/datasets/_datasetId.vue
- pages/datasets/viewer/_id.vue
The purpose of this PR is to add the images tab to a dataset's page, as well as the new route for the image viewer.
Please note the following at in progress, and will be addressed in future PRs pending work that MBF will do:
- Show thumbnails of each image in the images tab on the dataset page
- Show more data on the image viewer page
- Have a combined route for file details and image viewer
- Open [a dataset that has images](http://localhost:3000/datasets/43?type=dataset)
- Go to the Images tab
- Click on one of the image's IDs
- You should be taken to a page that display that image's viewer
- Open [a dataset that does not have images](http://localhost:3000/datasets/24?type=dataset)
- You should not see the images tab
> Fetch and render images

- pages/index.vue
The purpose of this PR is to add the image to the homepage hero and adjust design styles according to tablet and mobile viewports. The PageHero component will be adjusted to default to this design in a separate PR.
Navigate to the homepage. The PageHero component should now contain the image from the About page and styles should be adjusted for mobile and tablet viewports.
> Add Image To Homepage Hero #4ydgdg

- components/Breadcrumb/Breadcrumb.vue
- components/Breadcrumb/model.ts
- components/DatasetDetails/DatasetAboutInfo.vue
- components/DetailsHeader/DetailsHeader.vue
- components/HomepageTwitter/HomepageTwitter.vue
- nuxt.config.js
- package.json
- pages/about/index.vue
- pages/data/index.vue
- pages/datasets/_datasetId.vue
- pages/help/_helpId.vue
- pages/help/index.vue
- pages/index.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
- pages/organs/_organId.vue
- pages/projects/_projectId.vue
- pages/resources/index.vue
- yarn.lock
The purpose of this PR is to address the following:
- Fix issue with homepage Twitter feed
- Account for `summary` or `award` model for NIH Award on a dataset page
- Allow breadcrumb to support multiple items 
- Go to the homepage
- Scroll to the bottom to see the Twitter feed
- Go to any other page
- Go to the homepage
- Scroll to the bottom to see the Twitter feed
- [Dataset with award model](http://localhost:3000/datasets/58?type=dataset)
- [Dataset with summary model](http://localhost:3000/datasets/26?type=dataset)
Breadcrumbs should work on every page. 
Pages multiple levels deep like an organ detail page should have multiple breadcrumbs.
- Go to an organ page
- Click on "Find Data" breadcrumb
- You should be taken to the Find Data page showing Organ results
> SPARC QA #4yd5t2

- pages/data/index.vue
- pages/news-and-events/index.vue
- pages/organs/_organId.vue
The purpose of this PR is to address the following QA issues:
- Fix issue with projects being empty
- Contentful doesn't return a field if it has no value, and the app logic wasn't accounting for this properly
- Remove hero image on Find Data
- Fix issue with missing hero image on news and events 
- This was using the incorrect field. There is currently no data in Contentful for this, but we are no longer seeing the error.
- Fix issue on organ page where projects aren't being displayed
- This was an issue with pulling the contentful data in a different way than it ultimately ended up being stored.
- Go to Find Data
- Go to Organ
- Go to Heart
- Projects tab should be visible, if that organ has projects
- Go to Find Data/Organ
- Projects tab should be visible, if that organ has projects
- …
> QA #4yd5t2

- components/DatasetDetails/DatasetAboutInfo.vue
- components/DetailsHeader/DetailsHeader.vue
- components/SearchForm/SearchForm.vue
- pages/data/index.vue
- pages/organs/_organId.vue
Add clickable element that clears a search and re-fetches the results.
Open Protocol Links in new tab.
Allow full Organ description.
Clickup: #5jbe0p, #5jbejq, #5jbe0p
- Organ details should not have their descriptions truncated, others should.
- Should NOT be truncated: http://localhost:3000/organs/2cp3rRmSexg0aOOF4LtXy2
- SHOULD be truncated: http://localhost:3000/projects/64KypKtpWOdxEqy9ZrTZ2W
- Protocol links should open in new tab.
- Go to the home page and execute a search in the top right corner.
- In the resulting search page, a "Clear Results" link should appear.
- Clicking the link should clear the search and re-execute
- After clearing search, the back button should go back to the home page (where you were prior to starting the first search)
- From the search page, the "Clear …
> feat(clear search results): add "Clear Search" link

- components/SearchForm/SearchForm.vue
- components/SearchResults/DatasetSearchResults.vue
- components/SearchResults/OrganSearchResults.vue
- components/SearchResults/ProjectSearchResults.vue
- pages/data/index.vue
- pages/data/utils.ts
- pages/resources/index.vue
Support sorting for all of the Find Data pages as well as the Resources listings.
Clickup: #5jbe4g,#5jbe6k
You should be able to sort all pages of Find Data by various columns.  Test sorting ascending, descending, as well as that the page number resets to 1 if you change a sort order.  NOTE: sorting by size will not work until changes to `discover-service` are merged to prod.
The Resources page should now list resources in ascending alphabetical order.
> feat(sort tables): support sorting of various lists throughout the app

- components/PageHero/PageHero.vue
- pages/index.vue
The purpose of this PR is to add a video to the homepage hero. The background of the video isn't the same as the hero's background, which is why you see the box around the video. I will bring this up in Wrike once it gets into staging for them to review it.
See screenshots below for it working on all supported browsers
> Add video to homepage hero

- components/HomepageNews/HomepageNews.vue
The 'News & Events' link in the middle of the homepage should now link to news-and-events appropriately.
> fix(homepage): fix news & events link

- pages/about/index.vue
Replaced the button with a sentence that says the following: 
"Visit the [NIH SPARC program website](https://commonfund.nih.gov/sparc/) to learn more."
Hyperlink: https://commonfund.nih.gov/sparc/
[Wrike](https://www.wrike.com/open.htm?id=473576238)
[Clickup](https://app.clickup.com/t/6af0b8)
1. Navigate to [About](https://sparc.science/about) page.
2. Under the `About SPARC`, the edited sentence will be displayed.
3. Click the hyperlink.
4. Redirected to https://commonfund.nih.gov/sparc/ on new tab.
> fix(about): Change the button to NIH Website to a hyperlinked sentence

- pages/datasets/_datasetId.vue
- static/images/sparc-logo.svg
The purpose of this PR is to add fixes to the following details pages:
- Remove size from Simulations Detail Page
- Have the `Description` tab be the default active tab on the Dataset Details Page
1. Navigate to a Simulations Detail Page
2. The size attribute should no longer be displayed in the header
1. Navigate to a Dataset Detail Page
2. The `Description` tab should be the active tab displayed on the page.
> Details Page Fixes #6af1mu

- components/footer/Footer.vue
The purpose of this PR is to add the SPARC Portal Status page link to the footer. 
Navigate to the SPARC Portal and scroll down to the footer. You should see a `Site Status` link under the `Learn More` section in the footer. That link should take you to the status page.
> Add Site Status Link to Footer #6af2ed

- components/footer/Footer.vue
Changed "NIH SPARC" to "NIH SPARC Program" in footer.
1. Navigate to any page across the SPARC Portal.
2. Scroll down to the footer.
3. On the right column under `Learn More`, clickable link is displayed as "NIH SPARC Program".
4. Click on it.
5. New tab will open at https://commonfund.nih.gov/Sparc/.
> fix(footer): Changed 'NIH SPARC' to 'NIH SPARC Program' in footer

- components/footer/Footer.vue
The purpose of this PR is to add the SPARC Portal Status page link to the footer. 
Navigate to the SPARC Portal and scroll down to the footer. You should see a `SPARC.science Site Status` link under the `Learn More` section in the footer. That link should take you to the status page.
> Add Site Status Link to Footer #6af2ed 

- pages/datasets/_datasetId.vue
Changed label on dataset details page to access the SPARC data structure documentation from "Dataset Format Information" to "SPARC Data Structure".
**NOTE**: The clickup ticket originally states to change it to "Learn about the SPARC data structure", but the more recent comments on the wrike ticket updated the criteria to "SPARC Data Structure". 
[Wrike](https://www.wrike.com/open.htm?id=472557178)
[Clickup](https://app.clickup.com/t/6af240)
2. Click on any dataset.
3. In the header of the dataset's detail page, next to the `GET DATASET` button, there will be a link labeled "SPARC Data Structure" that takes you to the SPARC data structure documentation page.
> Dataset details label #6af240

- components/Pagination/PaginationMenu.vue
- pages/data/index.vue
- pages/resources/index.vue
- static/icons-js/icon-arrow.js
- static/icons-js/index.js
- static/icons-svg/icon-arrow.svg
The purpose of this PR is to add pagination to the top of all result tables in SPARC. This includes all the tables in the Find Data page and Resources page.
Designs can be found [here](https://app.abstract.com/share/7fa2ddd1-8911-4517-8c3b-113cd8d81a5b?collectionId=3bba7620-56e8-47d1-87ad-177eb087a9c5&collectionLayerId=177f13f8-497a-4ad3-86ed-02d1c5b4e12f&mode=build&selected=root-B5703C95-FB1C-4118-AAC6-AA91E88A0AAE&sha=263e790f05e9614fc477588964b0f23a311e86ec). Note that the designs were altered slightly based on discussions regarding placement of the current number displayed and the dropdown count.
1. Navigate to the Find Data page on the portal.
2. You should see the pagination dropdown and ticker on both the top and bottom of the table as expected.
3. All pagination functionality …
> Add Pagination to Top of Result Tables #6af119

- components/HomepageNews/HomepageNews.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
**News & Events Page:**
- Updated Past Events event card structure to reflect that of Upcoming Events.
- Added View More button that displays up to 8 more past events on click.
**Homepage:**
- Added date & location to upcoming events event cards.
**NOTE:**
Wrike ticket says to move certain events to the Past Events tab, but they are already there except for Neurotech Investing and Partnering, which should automatically move to the Past Events tab after the end date (May 6).
[List of events that were asked to be moved](https://docs.google.com/document/d/1wXr8SXKQPlrAIavifpEIqOivCb9g7gSUNbltu-cTzLU/edit)
**Designs:**
[Past Events event cards](https://app.abstract.com/share/88fb27c6-7c6e-454a-bd1e-5ac041bb0ddc?collectionId=b9aec151-2fab-4840-bbad-c938d6291535&sha=b783c948ffd791406d4f4ebcd4386 …
> Past event cards restructure #6af2w2

- components/DatasetDetails/DatasetAboutInfo.vue
Made dataset DOI clickable.
Maintained same style as the links in the `Protocol Links` section.
**NOTE:** Originally, the ticket said to include a modal to alert the user that they are being brought to an external link. After further discussion on wrike, this was decided against.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=467396309&a=3203588&id=473707106&st=space-441356195)
[Clickup](https://app.clickup.com/t/6af1vk)
2. Click on any dataset.
3. In the About section, the DOI link should be clickable and will open a new tab to the dataset's discover page.
> Dataset doi clickable #6af1vk

- components/PageHero/PageHero.vue
- pages/index.vue
The purpose of this PR is to add support for a video in the hero of the homepage. This was originally done in #105, but needed to be. reverted. #120 tried to put the changes back in, but it didn't work.
See screenshots below for it working on all supported browsers
> feat(Homepage): Add video support  in hero

- components/HomepageNews/HomepageNews.vue
Extends this PR: [#117](https://github.com/nih-sparc/sparc-app/pull/117)
Remove past events from homepage based on whether or not they are upcoming.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=473707106&a=3203588&c=list&t=477619428&so=2&bso=10&sd=0&f=&st=space-441356195)
[Clickup](https://app.clickup.com/t/6af2w2)
2. Past events will not be displayed. 
3. Only events where the end date is still in the future will be displayed.
> fix(homepage): Remove past events from homepage

- components/SearchResults/ProjectSearchResults.vue
**Find Data Page (Projects):**
- Removed logo column.
- Expanded description column to take up the space of the removed logo column.
- Extended character count of description field.
Additionally, the required logo property in Contentful has been disabled to allow incomplete projects to be displayed on this page. 
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=479529255&a=3203588&id=441356195&st=space-441356195)
[Clickup](https://app.clickup.com/t/6af2a2)
2. Click on the Projects tab.
3. Logo column will not be displayed.
4. Description column will be wider and display more characters.
> fix(projects): Removed logo column and expanded description column

- components/SearchResults/DatasetSearchResults.vue
> Conditionally rendering 'Size' column in dataset results page

- components/SearchResults/DatasetSearchResults.vue
- components/SearchResults/OrganSearchResults.vue
- components/SearchResults/ProjectSearchResults.vue
- pages/data/index.vue
When the user is on mobile (or very small browser size) the title column in the Find Data tables is too large and does not allow for the other columns to be visible. This fix conditionally changes the size of the column based on the browser size.
[Clickup](https://app.clickup.com/t/6af36y)
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=489276548&a=3203588&id=441356195&st=space-441356195)
**Mobile**
1. In Chrome Dev Tools, click the Mobile View button on the top left, so that the browser renders the SPARC Portal in a mobile layout.
2. Navigate to the Find Data page.
3. For all the tabs, the title column should be smaller and allow for the other columns to be visible and scrollable.
**Desktop**
2. For …
> fix(Find Data): Make the Find Data table more readable on mobile

- pages/data/index.vue
- pages/organs/_organId.vue
**Find Data Page (Organs):**
- Remove organs that do not have associated datasets.
**Organ Details Page:**
- Properly hit the endpoint to retrieve all organ datasets.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=473147058&a=3203588&id=441356195&st=space-441356195)
[Clickup](https://app.clickup.com/t/6af32m)
2. Click on the Organs tab.
3. Only organs with datasets will be displayed (currently there are 7).
4. Click on any organ.
5. Organ Details page will show all datasets associated with that organ.
> Hide organs with no datasets #6af32m

- pages/datasets/_datasetId.vue
The Description tab is now the first tab in a dataset's detail page.
[Clickup](https://app.clickup.com/t/6ygpyk)
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=472085698&a=3203588&id=441356195&st=space-441356195)
2. In the Datasets tab, click on any dataset.
3. The Description tab will be before the About tab.
> fix(dataset): First tab is Description

- pages/resources/index.vue
Added conditional to hide the pager when there is only one page of results in the resources page. Fixes issue with underline not appearing.
1. Navigate to the resources page.
2. Click on the Tools tab.
3. Pager should not be displayed.
4. For both the All Resources and Platforms tab, the underline should properly display under the active page.
> fix(resources): Added conditional to hide pager for one page

- components/header/Header.vue
- pages/data/index.vue
Added a search bar with a dropdown menu to select either "Datasets" or "Support Center". User will be brought to those respective routes with query params.
[Clickup](https://app.clickup.com/t/70e8ut)
[Wrike](https://www.wrike.com/open.htm?id=467366936)
**Datasets Search**
2. On the top right, search bar dropdown should be default to "Datasets".
3. Type in "Heart".
4. Click the search button or hit enter.
5. You will be routed to the Find Data page where datasets will be filtered by "Heart".
**Support Center Search**
2. On the top right, click the dropdown and select "Support Center".
3. Type in "Help".
4. Click the search button or hit enter.
5. You will be routed to the Help page where the information will be filtered by "Help". …
> Add search bar #70e8ut

- components/PageHero/PageHero.vue
- pages/help/index.vue
- pages/index.vue
Updated the background color of the page hero to reflect that of the hero video. Removed loop property so that the video only plays once.
**Note:** The clickup ticket recommends to use `#313062`, I found that `#383671` was a better color fit with the hero video.
[Clickup](https://app.clickup.com/t/6ygpw3)
[Wrike](https://www.wrike.com/open.htm?id=487378873)
2. Background of page hero is the same as the hero video.
3. Hero video plays once.
> fix(hero): Update background of hero video

- components/header/Header.vue
- pages/news-and-events/index.vue
This PR adds Resources and News/Events to the global search bar.
NOTE: this PR is into #132 to make things easier to review.  Please review #132 first.
Select Resources from the global search bar and enter a search term.  You should be routed to the Resources page with the term in the search box and the results filtered accordingly.  The same should be true of News and Events.
> feat(global search): add resources and news to global search

- components/SearchControlsContentful/SearchControlsContentful.vue
- components/header/Header.vue
- Adjust the width of the global search control to accomodate for the longer text items e.g. "News and Events".
- Add a clear button to the `SearchControlsContentful.vue`
- Using devtools, set your responsive width to 1024px (minimum width before mobile).  Make sure everything in the header fits.  On wider viewports, the search bar should be wider.  There should always be enough room for the longest dropdown value for global search (News and Events).
- The Help Center, Resources, and Find Data pages should all have working clear buttons for their search.
> Search style updates #72fvb1

- components/EventCard/EventCard.vue
- components/HomepageNews/HomepageNews.vue
- Display only the start date if the event start and end dates are the same.
- Do not display location icon if the event has no location data.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=473707106&p=441356195&a=3203588&c=list&t=467368706&so=2&bso=10&sd=0&f=&st=space-441356195)
Test on homepage and News & Events page (test event: New SPARC Funding Opportunity):
1. Events with same start & end date will only display start date.
2. Events with no location data will not display location icon.
> fix(events): Properly display date and location on event cards

- pages/data/index.vue
Fixes the following:
- When user goes to an organs detail page from the Organs tab in Find Data and goes back, the pagination dropdown goes to 999.
2. Click on any organ.
3. Go back to the Find Data page (using the back button in your browser).
4. The pagination dropdown will be reset to 10, not 999.
> fix(organs): Pagination dropdown fix

- pages/about/index.vue
Updated about page link style per the designs.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=473707106&p=441356195&a=3203588&c=list&t=473576238&so=2&bso=10&sd=0&f=&st=space-441356195)
[Clickup](https://app.clickup.com/t/78e8qp)
1. Navigate to the about page.
2. About page link in banner will be white and underlined.
3. Hover over the link.
4. The link will become gray (#909399)
> fix(about): Updated about page link style

- components/footer/Footer.vue
Update site status link in footer from "SPARC.science Site Status" to "SPARC Systems Status".
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=473707106&p=441356195&a=3203588&c=list&t=484953340&so=2&bso=10&sd=0&f=&st=space-441356195)
[Clikup](https://app.clickup.com/t/78eb82)
1. Scroll down to the footer.
2. SPARC Systems Status will be the last option in the "Learn More" section.
3. Click on it.
4. You will be brought to http://status.sparc.science/
5. The first label will be https://sparc.science
> fix(footer): Update status link text in footer

- pages/data/index.vue
- pages/organs/_organId.vue
The purpose of this PR is to fix a bug where some organs weren't being display in the Find Data page, even though they did have datasets associated with them. This was because the Colon organ is actually "Colon and Large Intestine" and therefore the endpoint returns 0 results. To categorize these organs, there is a "Project Section" field where we assign organs to a generic category. In this example, "Colon and Large Intestine" is part of the "Colon" category. Using this field fixes the bug for the following organs:
- Colon
- Bladder/Lower Urinary Tract 
- Male Reproductive System
- Navigate to the [Find Data/Organs](http://localhost:3000/data?type=organ) page
- You should see all organs that have datasets associated with them, including the three from the list at the top.
> bugfix(Find Data): Fix some organs not returning results

- components/header/Header.vue
Fixed enter not working after first search by properly resetting the dropdown to Datasets.
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=473707106&p=441356195&a=3203588&c=list&t=467366936&so=2&bso=10&sd=0&f=&st=space-441356195)
[Clickup](https://app.clickup.com/t/78f0fw)
1. Search something in the global search bar using Enter.
2. After results display, global search bar will clear.
3. Search something again in the global search bar using Enter.
4. Results will display.
> fix(search): Fix enter not working after first search on global search bar

- components/PageHero/PageHero.vue
The purpose of this PR is to adjust the page hero background color to match the new video.
- Go to the homepage
- The background color of the hero should be the same as the video's background color.
> Adjust page hero background color to match video

- components/PageHero/PageHero.vue
The purpose of this PR is to add a hack to fix a color discrepancy in Firefox.
Tested the homepage hero background color to match the video background color in various browsers.
> Address background color on Firefox

- pages/about/index.vue
- pages/help/index.vue
- Remove hero video from about page
- Update the banner color in the help page.
1. Navigate to the About page.
2. Hero video will not display.
1. Navigate to the help page.
2. Banner color will be `#292b66`.
> remove hero video from about page, update help banner color

- pages/data/index.vue
This PR is to handle an issue where, on refresh, the datasets do not load on the Find Data page. 
**Note:** This issue only happens on refresh, not initial load.
Working on this, I discovered some strange behavior that is definitely tied to Nuxt's SSR. When running locally, if you navigate to the Find Data page and refresh, the table is rendered with duplicated content:
When refreshing in dev or prod, the content doesn't render:
I believe these are the same issue and it stems from an error in which the server-rendered and client-rendered content do not match. The specific content is the `searchData.total` on the top left of the table. Nuxt renders it as:
- "undefined Datasets | Showing"
While the client renders:
- "{some number} Datasets | Showing"
Console printout:
The only solution I …
> Hotfix: Datasets Not Rendering

- package.json
The purpose of this PR is to add the `generate` script, which is a shortcut for `yarn nuxt generate`. This will make the readme's commands match what is supported in the app.
N/A
> Add nuxt generate command

- components/DatasetDetails/DatasetAboutInfo.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
- pages/datasets/_datasetId.vue
Moved protocol links from the About tab to the Description tab.
**NOTE:** This was a little funky. Since we are fetching the entire markdown string for the description, I had to split the string where the protocol links are supposed to go. I'm not a huge fan of how I had to do this because there could be some issues when the markdown is not correctly formatted, although it works for now. I couldn't think of a better way. Let me know if there's a better/more optimized way to do this.
2. Click on any dataset.
3. Protocol links will be in description tab below primary conclusion.
4. Got to About tab.
5. Protocol links will not be displayed.
> Moved protocol links to Description tab

- components/DatasetDetails/DatasetFilesInfo.vue
- nuxt.config.js
- pages/datasets/_datasetId.vue
- Moved SPARC Dataset Structure link to files table.
- Changed link to direct to Navigating a SPARC Dataset help page.
- Changed link label to represent link target
2. Select any dataset.
3. SPARC Dataset Structure will not be next to the Get Dataset button.
4. Go to the Files tab.
5. Link labeled as "Learn more about navigating a SPARC dataset" will be above the files breadcrumb.
6. Click on the link.
7. You will be navigated to the Navigating a SPARC Dataset help page.
> Fix Style and Link Label

- components/DetailsHeader/DetailsHeader.vue
- components/SearchResults/ProjectSearchResults.vue
- pages/projects/_projectId.vue
The purpose of this PR is to remove truncation of the description on a project's page, and add support for a short description field on the projects list (find data.)
- Go to the [Find Data projects page](http://localhost:3000/data?type=sparcAward)
- The first project "Mapping the linkage between auricular vagus nerve receptors and visceral organ modulation" should be showing its short description. _This is the only project that has been updated at the moment to support the new short description field_
- Open this [project](http://localhost:3000/projects/6O6hZNUoEapRCpgztIkKEQ)
- The full description should be displayed on all viewports.
> Project detail and list truncation CU-7pg8up CU-7pg95y

- components/DatasetDetails/DatasetAboutInfo.vue
Display a formatted error message when crosscite fails.
[Clickup](https://app.clickup.com/t/5ygtye)
[Wrike](https://www.wrike.com/open.htm?id=491145983)
1. In `DatasetAboutInfo.vue` on line 257, change the crosscite endpoint url to `[...]/dontformat[...]` to simulate an error.
2. Navigate to Find Data page.
3. Select any dataset.
4. Click on the About tab.
5. Citation area will display a formatted error message.
6. Copy citation button will be disabled.
> Crosscite error message cu 5ygtye

- components/HelpCard/HelpCard.vue
- components/HelpSection/HelpSection.vue
- mixins/highlight-text/index.js
The purpose of this PR is to highlight search terms in results on the support center.
[ClickUp](https://app.clickup.com/t/7pg719)
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=488219710&a=3203588&id=441356195&st=space-441356195)
- Click on the "Need Help?" link in the header
- Enter a search term like "SPARC"
- All instances matching your search term should be bold.
> feat(Support Center): Highlight search terms in results CU-7pg719

- components/DatasetDetails/DatasetAboutInfo.vue
Quick style update for the citations area based on updated designs provided by Gazelle. Border is now light gray.
[Designs](https://share.goabstract.com/f93d41ce-bfd5-4b25-b8f6-18afd7f06036)
2. Select any dataset
3. Go to About tab.
4. Border under citation names will be light gray and not black as it was previously.
> Update citation border style

- components/DatasetDetails/DatasetAboutInfo.vue
- pages/datasets/_datasetId.vue
Add the dataset owner name and email to the About tab.
[7pg85v](https://app.clickup.com/t/7pg85v)
[Wrike](https://www.wrike.com/open.htm?id=490179111)
This cannot be tested locally for now due to CORS issues with the sparc api. When this is merged, it can be tested in staging with the following steps:
2. Select any dataset.
3. Go to the about tab.
4. Contact information of dataset owner will be displayed.
> Add Dataset Owner Contact Info

- pages/datasets/_datasetId.vue
Properly access the owner return object.
**Note:** If you want to test this locally, you will need to run the sparc-api locally and hook it up to the sparc-app as the sole portal api environment variable.
2. Select any dataset.
3. Go to the about tab.
4. Contact information of dataset owner will be displayed.
> Fix the owner email endpoint call

- components/header/Header.vue
- pages/resources/index.vue
Change nav bar link "Resources" to "Tools & Resources". Also updates the spacing to maintain the style.
Looking at the style guidelines on abstract, I believe this change keeps it consistent. Let me know if it seems off compared to the designs.
[90h7e5](https://app.clickup.com/t/90h7e5)
[Wrike](https://www.wrike.com/open.htm?id=518220477)
1. Look at the nav bar.
2. "Tools & Resources" will be the third item.
3. Resize the browser to different sizes.
4. The nav bar will adjust appropriately.
5. Click on "Tools & Resources".
6. The page hero will say "Tools & Resources".
7. The breadcrumb will say "Tools & Resources".
> Change SPARC Portal menu item Resources to Tools & Resources

- components/PageHero/PageHero.vue
- mixins/marked/index.js
- pages/about/index.vue
- pages/data/index.vue
- pages/index.vue
- pages/resources/index.vue
- test/MarkdownTest/MarkdownTest.spec.js
- test/MarkdownTest/MarkdownTest.vue
The purpose of this PR is to add markdown support for all page heros, and to have all markdown links open in a new tab.
[CU-90h6m7](https://app.clickup.com/t/90h6m7)
[CU-90h5zx](https://app.clickup.com/t/90h5zx)
[CU-90h83a](https://app.clickup.com/t/90h83a)
https://www.wrike.com/open.htm?id=511079440
https://www.wrike.com/open.htm?id=519660261
https://www.wrike.com/open.htm?id=503776942
- All page's heros should be rendering the same as non-prod
- The [about page](http://localhost:3000/about) hero should have two paragraphs and a link. This link should open in a new tab. This content is all in Contentful, which proves that the markdown parsing renders links to open in tabs.
MarkdownTest should pass
> Markdown support in page heros, and all markdown links should open in a new tab CU-90h6m7 CU-90h5zx CU-90h83a

- components/DatasetDetails/DatasetAboutInfo.vue
Firefox and Safari fail `Axios` GET request for citations endpoint. Switched to `Fetch`.
On Chrome, Safari, and Firefox:
2. Select any dataset.
3. Go to About tab.
4. Select citation styles.
5. Citations will populate properly.
> Hotfix: Use fetch instead of axios for citations

- pages/data/index.vue
The purpose of this PR is to remove the Find Data heading. This needs to go out on normal release, and not mid-sprint.
The Find Data page should have no heading in the hero.
> Remove Find Data heading

- components/DatasetDetails/DatasetAboutInfo.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
Style DOI and protocol links according to the [designs](https://app.abstract.com/projects/e709ca90-5ba9-11e9-9eaa-59df656d954a/branches/master/commits/latest/files/CD711200-A81D-447E-A416-7EC0284A48C1/layers/32510A4E-0CE5-4EF7-BCBA-69840C184F90?collectionId=d5e9f917-15c3-4c21-8e2e-f0260cd92536&collectionLayerId=ec13cb81-7eda-4fff-8bc1-d635ee2cf8a2&mode=build&selected=root-703EBC5D-4A2D-4B45-BDC8-A3A7DCFE7C66). The designs use a `font-size` of `16px` but the About tab is all `14px`, so I left the DOI link at `14px` because it would look too big compared to the rest of the text.
[90h5hh](https://app.clickup.com/t/90h5hh)
[Wrike](https://www.wrike.com/open.htm?id=491181541)
1. Navigate to a dataset with protocol links (http://localhost:3000/datasets/62?type=dataset).
2. The Description tab …
> Apply style to DOI and protocol links

- components/FeaturedData/FeaturedData.vue
Change the "Browse Data ..." heading to "Find Data ..."
The "Explore Data" button was changed in Contentful
[90h5th](https://app.clickup.com/t/90h5th)
[Wrike](https://www.wrike.com/open.htm?id=492740021)
2. Explore Data button will read Find Data.
3. Browse Data heading will read Find Data.
> Consistency in Find Data naming

- components/footer/Footer.vue
Adds "SPARC Publications" link to the footer. This will probably need to be updated later to build the url dynamically, but for now, this is what was asked for.
[90h8d9](https://app.clickup.com/t/90h8d9)
[Wrike](https://www.wrike.com/open.htm?id=518224242)
1. Scroll down to the footer.
2. Click on SPARC Publications link.
3. New tab will open directing to Pubmed with the relevant grant numbers as the query.
> Add SPARC Publications link in footer

- pages/about/index.vue
Adds support for "Future Plans" section in the About page, which will be filled with relevant information once it's added in Contentful.
1. Navigate to the About page.
2. At the bottom is a clearly defined area for the Future Plans information.
3. For now, it just renders "Lorem Ipsum".
> Add support for Future Plans section in about page

- components/EventCard/EventCard.vue
- components/HomepageNews/HomepageNews.vue
When checking if an event is upcoming, default to start date if there is no end date. End date is not a required field in Contentful so this needs to be accounted for. Additionally, only display the start date if there is no end date. 
[Wrike](https://www.wrike.com/workspace.htm?acc=3203588#path=folder&t=530654681&a=3203588&id=441356195&st=space-441356195)
2. Open chrome dev tools.
3. Find SparcHomepage/HomepageNews.
4. The `news` prop will be an array of all the events.
5. There will be a computed property named `upcomingNews` that is properly filtered based on end date or start date.
> Fix event date logic

- pages/about/index.vue
The purpose of this PR is to only show the future plans section if there is content.
- I removed content for the future plans section in Contentful, and the section no longer appears.
- Using vue devtools, find the `AboutPage` component
- Change `futurePlans` to `# foo` and the section should render an `h1` with `foo` as its text.
> Only show the future plans section if there is content

- mixins/request-download-file/index.js
Clicking on a file to download it does not work. The call to sparc-api to request the presigned URL works but then the call to _downloadFile function fails. This PR fixes the issue by ensuring that the function is in scope when called.
This was tested by running a local instance of the portal and ensuring that downloads work once the fix is in place.
> Cu b4qv16 download issue

- components/SearchResults/ProjectSearchResults.vue
Link the project award id to its NIH RePORT url.
[ayqv4w](https://app.clickup.com/t/ayqv4w)
[wrike](https://www.wrike.com/open.htm?id=494581806)
Navigate to the project listing page.
Scroll over to the NIH award column.
All of the award ids will be a link to the project's respective NIH RePORT url.
> fix(project): Hyperlink project award id to its nih report link

- components/DatasetDetails/DatasetAboutInfo.vue
- pages/datasets/_datasetId.vue
Acceptance Criteria:
- Add "Cite Dataset" button next to "Get Dataset" and link to bottom of About Page
- Display the whole the contributor list (remove ellipsis)
**Draft**
The threshold for the number of contributors to display before applying the ellipsis is still being decided on, but most probably will be 15 (refer to wrike comment thread). However, the code for this story is complete so in the meantime it can be reviewed and once the threshold number is confirmed, changed if needed and opened.
[ayqvwm](https://app.clickup.com/t/ayqvwm)
[wrike](https://www.wrike.com/open.htm?id=495964822)
1. Navigate to any dataset.
2. The list of contributors will not be shortened if there are 15 or less contributors.
3. Click the Cite Dataset button next to the Get Dataset button.
4. The tab will be …
> feat(overview): Citation button in dataset details and increase contributor threshold

- components/footer/Footer.vue
While working on [ayqvtz](https://app.clickup.com/t/ayqvtz), I noticed that the ToS link underline extended past the end of the word and included the space before the divider character. This PR is a quick fix for the styling.
On all screen sizes and devices
1. Scroll to the bottom of any page.
2. ToS is styled properly.
This:
Instead of:
> fix(footer): ToS link underline

- components/footer/Footer.vue
The purpose of this PR is to add the SPARC Glossary link under the `Learn More` section in the footer.
Navigate to the homepage and scroll down to the footer. You should see the SPARC Glossary link under the `Learn More` header and it should navigate to the glossary page as expected.
> Add SPARC Glossary Link to Footer

- components/footer/Footer.vue
The purpose of this PR is to make the Materials Sharing Policy more visible for users on the SPARC Portal. The following has been done to achieve this:
- Add Materials Sharing Policy to link in footer
- Add paragraph about Materials Sharing Policy on About Page
- Add link to policy in the help section
1. Navigate to the portal and scroll to the footer. You should see `Material Sharing Policy` link underneath the `Learn More` section on the footer.
2. Navigate to the `About` page. You should see a paragraph on the Materials Sharing Policy underneath the goal section.
3. Navigate to the help section. An article to the policy with a PDF link should be found underneath the `SPARC For Investigators Only` section. Clicking on the link should open the policy in a PDF as expected.
> Make Materials Sharing Policy Visible for SPARC Users CU-ayqv82

- components/SearchResults/ProjectSearchResults.vue
This PR fixes a font resizing issue on mobile (specifically iOS). Ref: #186 
Thanks Cameron for debugging this one!
[ayquj5](https://app.clickup.com/t/ayquj5)
1. Use Browserstack or something similar to simulate a mobile environment.
2. Navigate to the Find Data page.
3. Click on the Projects tab.
4. The description font-size will be correct.
> fix(projects): Fix font resizing in projects table on mobile

- components/PageHero/PageHero.vue
- pages/index.vue
The purpose of this PR is to replace the video on the homepage hero with an image. I also made this image transparent so we don't have a color issue like the video had. 
This has been tested on all supported browsers and OS.
> feat(Homepage Hero): Image and proper brand color

- components/MapApp/MapApp.js
- package.json
- pages/datasets/scaffoldviewer/_id.vue
- pages/maps/index.vue
- yarn.lock
Update to use the latest version of MapApp and Scaffoldvuer which greatly reduces the components size. Javascript on the Maps page goes down from ~1.4MB to ~800KB. The components are now registered locally. 
Hosted on https://mapcore-demo.org/current/sparc-app for user testing.
Yarn test runs sucessfully.
> Greatly reduce size of MAP related components

- mixins/marked/index.js
- nuxt.config.js
- test/MarkdownTest/MarkdownTest.spec.js
- test/MarkdownTest/MarkdownTest.vue
The purpose of this PR is to change the logic for rendering links with markdown to only open external links in new tabs. This will fix a bug with anchor tags not linking to items on the same page.
- Go to the [SPARC Glossary](http://localhost:3000/help/3vcLloyvrvmnK3Nopddrka)
- External links should open in a new tab
- Scroll to the DAT-Core section and click the `SIM-Core` link at the end of the paragraph.
- You should be taken down to that anchor tag
> fix(Markdown): Only make external links open in new tab

- components/FilesTable/FilesTable.vue
- pages/file/_datasetId/_datasetVersion/index.vue
The purpose of this PR is to fix an issue with some files when direct linking to them. Native file types were 
- Navigate to [a dataset with an image](http://localhost:3000/datasets/64)
- In the Files tab, navigate to the image and click on its name to open it. If using the above dataset, the path is: `files/derivative/sub-9/sam-3/sub-9sam-3P9-3Slide2p3MT10x.jp2`
- Refresh the page. File details page should load.
> fix(Files): Fix URL to allow linking to some file types - CU-cuj73d

- pages/datasets/_datasetId.vue
The purpose of this PR is to remove the `Get Dataset` link from the Simulations page. 
Navigate to a simulation page. The `Get Dataset` link should no longer be displayed next to the `Run Simulation` button on the page.
> Remove Get Dataset link from Simulations Page

- components/SparcCard/SparcCard.vue
The purpose of this PR is to change the homepage news and events images to be full height of the content. 
https://www.wrike.com/open.htm?id=510367560
https://app.clickup.com/t/cuhzqx
- Inspect `SparcHomepage` component, and add a `summary`  key to the first object of the `newsAndEvents` list with long  content: `newsAndEvents[0].fields.summary = 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum`
- Look at the news item on all viewports.
> feat(Homepage news): Allow image to be same height as content

- components/CookieNotice/CookieNotice.vue
The purpose of this PR is to fix an issue with the close button overlapping the Accept button.
https://app.clickup.com/t/cuj1qt
https://www.wrike.com/workspace.htm?acc=3203588&wr=14#path=folder&t=516884661&a=3203588&id=441356195&st=space-441356195
See screens above for all viewports
> fix(Cookie banner): Prevent close button overlap

- pages/datasets/_datasetId.vue
The purpose of this PR is to set the description tab as the default tab on the simulations page.
[Wrike Ticket](https://www.wrike.com/workspace.htm?acc=3203588&wr=14#path=folder&t=502019661&a=3203588&id=441356195&st=space-441356195)
[Clickup Ticket](https://app.clickup.com/t/cuj6u5)
Navigate to a simulations page. The `description` tab should be the selected by default.
> Set description tab to be the default on Simulations page - CU-cuj6u5

- .eslintrc.js
- components/BfDownloadFile/BfDownloadFile.spec.js
- components/BfDownloadFile/BfDownloadFile.vue
- components/DownloadDataset/DownloadDataset.vue
- components/FilesTable/FilesTable.vue
- components/MetadataTable/MetadataTable.vue
- nuxt.config.js
- package.json
The purpose of this PR is the add the feature to download multiple files on a dataset. This work was largely bringing over the `BfDownloadFile` component that does this same functionality on Discover.
- Open a data
- Go to the Files tab
- Select multiple files over 5GB
- Click on download button above the table
- A dialog should appear notifying you the download size is too big
- In the dialog, remove some packages to go under the download size
- Change the file's name
- Click the download button to download
- Download should begin, with the file's name you input
- Select one file that is under 5GB
- Click on download button above the table
- Download should begin
> feat(Dataset): Download multiple files - CU-cuj5j9

- components/SearchResults/DatasetSearchResults.vue
The purpose of this PR is to fix an issue with ordering on the datasets search results. It was being ordered by date properly, but we were not display the correct date in the search results. This also includes some formatting issues.
- Go to the find data/datasets page
- Datasets should be ordered newest to oldest
- Click on the "Last Published" column header to sort by date
- The datasets should be ordered oldest to newest
> fix(Datasets): Display proper date in results

- pages/resources/index.vue
- pages/resources/model.ts
The purpose of this PR is to update the tabs on the Tools and Resources page to match the design system, and the tabs on the News and Events page.
- Go to the [Tools & Resources](http://localhost:3000/resources?type=sparcPartners) page
- Utilizing the tabs should show the proper tab and results
- Utilizing the search bar in the page's hero should show results for the search term
- Utilizing the search bar in the site's hero, and selecting "Resources" from the dropdown should show results for the search term (especially from another page.)
> feat(Resources): Update tabs to match design system

- pages/resources/index.vue
The purpose of this PR is to fix the tabs on the resources page.
- Go to the Tools and Resources page
- The tabs should be above the results, but below the hero
> Fix resources tabs

- components/DownloadDataset/DownloadDataset.vue
This PR aims to pass 'SPARC' as the value for the optional query parameter `downloadOrigin` when downloading a dataset directly from the back-end of `discover`
Went to download a Dataset and verified in the database that the download is labeled 'SPARC'
> passing new query param to indicate downloadOrigin

- components/Resources/ResourcesSearchResults.vue
The purpose of this PR is to add the owner and contact info to tools and resources. In addition, I fixed a bug where each resource may be too small for the content. This was due to the height specified when it shouldn't have been.
- Go to the tools and resources page
- The owner should be listed, if available, and it should link to the email, if available. If there is no email, it should be plain text.
> Add owner contact info to tools and resources

- components/DatasetDetails/DatasetDescriptionInfo.vue
The purpose of this PR is to make the protocol links appear on their own line.
[This dataset](http://localhost:3000/datasets/32?type=dataset) should have its protocol links on separate lines.
> feat(Dataset): Protocol links on separate lines

- components/Resources/ResourcesSearchResults.vue
The purpose of this PR is to remove the `updatedDate` field and replace with a `developedBySparc` category for tools and resources.
[Clickup Ticket](https://app.clickup.com/t/guungw)
[Clickup Ticket](https://app.clickup.com/t/guvutf)
Navigate to the Tools and Resources page. You should no longer see a date underneath the title and now should see a purple SPARC pill if the resource was developed by SPARC.
> Resource Page Modifications

- components/SearchResults/DatasetSearchResults.vue
- pages/organs/_organId.vue
- utils/toQueryParams.js
The purpose of this PR is to fix the sorting for datasets on an organ's page, and allow the user to sort the datasets table.
- Go to the [Bladder/Lower Urinary Tract](http://localhost:3000/organs/54xPL40EaKrarCqBkAFExU) organ
- The datasets should be ordered by date
- Clicking on the Title or Date column headings should refetch the datasets and sort properly
> Fix date sorting on organs page for datasets - CU-guvtwh

- components/DatasetDetails/DatasetAboutInfo.vue
- pages/datasets/_datasetId.vue
The purpose of this PR is to used the `revisedAt` date for datasets, and default to the `versionPublishedAt` date.
Go to a dataset. The date should be the same in the following places
- About tab
- Last updated
- Cite this dataset
- Dataset details header
> fix(Datasets): Use revised at date

- mixins/request-download-file/index.js
This PR aims to change the way we download individual files. By using the ZipIt endoint, we allow the file download to be counted in the Download Metrics
1/ Run a local instance of ZipIt `npm run start:prod`
2/ set the environment variable ZIPIT_API_HOST="localhost:8080"
3/ run the sparc-app server
4/ navigate to a file browser in a dataset
5/ click on the "..." at the end of the line and click download
Alternate ending:
5/ click on the file to go to the file details page
6/ click on "Download"
In both cases, the download works and is done via ZipIt.
> using ZipIt for downloading files

- mixins/request-download-file/index.js
- package.json
- yarn.lock
This PR aims to change the way we download individual files. By using the ZipIt endoint, we allow the file download to be counted in the Download Metrics
1/ run `export ZIPIT_API_HOST="https://cors-anywhere.herokuapp.com/https://api.blackfynn.io/zipit/discover"` to avoid CORS issue due to the sparc-app running as localhost (blocked by ZipIt)
2/ run the sparc-app server
3/ navigate to a file browser in a dataset
4/ click on the "..." at the end of the line and click download
Alternate ending:
4/ click on the file to go to the file details page
5/ click on "Download"
In both cases, the download works and is done via ZipIt.
> proper way to create the downloaded file

- assets/components/_el-table.scss
- mixins/marked/index.js
The purpose of this PR is to add styles for markdown tables, which would be added in Contentful. This does not yet use the [SPARC Design System components](https://github.com/nih-sparc/sparc-design-system-components) directly, as that a much larger ticket, but it is the same styles from that library.
- Navigate to [this help article](http://localhost:3000/help/6QBSfoJRRLo1BmaKMuQUYO)
- The table should render properly on all viewports, scrolling horizontally if necessary.
> feat(Tables): Add support for markdown tables

- components/Resources/ResourcesSearchResults.vue
The purpose of this PR is to address feedback to update "Owner" to "Support Contact" and only show this section if the email is available.
- Go to the Tools and Resources page
- "Support Contact" should only be shown if there is an email, which SODA has.
> fix(Resources): Update to support contact

- pages/index.vue
- utils/homepageFields.js
- utils/homepageFields.spec.js
The purpose of this PR is to fix a bug where the site would should be error message for the homepage if there was no news. This bug was a result in Contentful not returning empty fields (which is a standard REST practice) and which would then result in the component being passed `undefined`. For the case with the news, you can't run `filter()` on `undefined`, which would then crash the page.
https://app.clickup.com/t/jjvfbf
- Unit test was written to test empty response as well as missing fields from the response.
- Homepage renders correctly
> fix(Homepage): Fix bug where site will crash if no news

- components/DatasetDetails/DatasetAboutInfo.vue
- components/ExternalPublicationListItem/ExternalPublicationListItem.vue
- pages/datasets/_datasetId.vue
The purpose of this PR is to show the references in the about tab for a dataset, if available. This is using the same `ExternalPublicationListItem` component from Discover.
- Open [a dataset with references](http://localhost:3000/datasets/97?type=dataset) and go to the about tab
- References should be listed at the bottom of this tab
- Open [a dataset without references](http://localhost:3000/datasets/94?type=dataset) and go to the about tab
- The references section, including the heading, should not be shown
> feat(Datasets): Show references in about tab

- components/EventCard/EventCard.vue
- components/HomepageNews/HomepageNews.vue
- components/NewsEventsPage/NewsEventsPage.vue
- components/NewsListItem/NewsListItem.vue
- mixins/marked/index.js
- nuxt.config.js
- package.json
- pages/news-and-events/events/_id.vue
- pages/news-and-events/news/_id.vue
- yarn.lock
The purpose of this PR is to add pages for news and events items, rather than having them link out. I have a few questions out to them on Wrike, specifically about the share button icons and author, and some decisions need to be made. In addition for the news, there's a new `copy` field that isn't filled out for any of the news items.
- On the homepage, scroll to the bottom and click on one of the events
- You should be taken to the event's page
- Go to the news and events page
- Click on an event's title, you should be taken to the event's page
- Go to the news and events page
- Find the news item "New NIH Funding Opportunity Announcement (RFA-DK-20-020)"
- You should be taken  to the news' page, and it should have placeholder copy rendered from markdown
> Feat news and events pages cu jjvd87

- components/AccessibilityDialog/AccessibilityDialog.vue
- components/HelpCard/HelpCard.vue
- pages/help/_helpId.vue
The purpose of this PR is to add a slug to help articles in contentful, and support querying them by the URL. This will allow users to link to the URL with the slug instead of the ID.
- Go to the "Need Help?" page
- Click on  "Getting Started"
- Help article should load
- Go to the "Need Help?" page
- Click on "Knowledge Management and Curation Core (K-Core) Information"
- Help article should load, and the URL  should have the slug in it
-
> feat(Help Articles): slug support - cu-jjvc2p

- pages/data/index.vue
The purpose of this PR is to add browser history for the find data page.
[CU-jjvc2p](https://app.clickup.com/t/jjvc2p)
[579582035](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=579582035&pid=441356195&cid=441356195)
- Go to the find data page
- Add a search term
- Adjust results per page
- Go to a new page
- Open a dataset
- Use the browser's back button, and you should be taken back to the find data page with the same search term, page and results per page
> Find data history for search CU-jjvc2p

- components/SearchResults/ProjectSearchResults.vue
- pages/organs/_organId.vue
The purpose of this PR is to fix the sorting functionality of the projects table on an organ's page.
https://app.clickup.com/t/fryx0p
- Go to [an organ](http://localhost:3000/organs/54xPL40EaKrarCqBkAFExU)
- Projects table should be an option if the organ has projects
- Go to the projects tab, and projects should be shown
- Clicking on the heading of the title, NIH Award or principal investigator should sort the table
> Fix projects table sorting on organ page

- components/DatasetDetails/DatasetAboutInfo.vue
- pages/help/_helpId.vue
The purpose of this PR is to address feedback for sprint 8 for the following: 
- Change heading in Dataset's About tab to "Corresponding Author"
- Add a redirect for help pages that have a slug when going to that page using the ID
- Go to [a dataset](http://localhost:3000/datasets/104?type=dataset) and open its About tab
- The heading about the author's name and email should be "Corresponding Author"
- Go to [a help entry that does not have a slug](http://localhost:3000/help/9JZsVzj2xZUMQuzx4RuU7)
- The page should load as normal
- Go to a help entry that does have a slug, but with the ID in the URL: http://localhost:3000/help/46cO5KyU0TwwM6vRo806mJ
- You should be redirected to the URL with the slug, and the page should load normally.
> Sprint 8 feedback cu-kmz5pr

- components/footer/Footer.vue
- mixins/marked/index.js
- store/index.js
The purpose of this PR is to load the footer links from Contentful.
I added some sections to the entry in Contentful that we were using for the footer copy. Here, we can select what Footer Links we want to have in the footer, and in what order they should appear.
https://app.contentful.com/spaces/6bya4tyw8399/entries/wpik0A2sDOy9IQEoKpkKG
- The links in the footer should match the links in production
- Go to [this help article](http://localhost:3000/help/3vcLloyvrvmnK3Nopddrka)
- External links should open in new tabs
- Anchor links (Like the link for MAP-CORE) should function normally
> Footer links from Contentful

- pages/maps/index.vue
The purpose of this PR is to update the hero style for the Maps page.
- Go to the maps page
- The hero copy should be font-size 15 and appear under the heading.
> Update hero copy style

- pages/maps/index.vue
Use fetch hook to fetch the data if permalink id is provided on maps page.
It is running on mapcore-demo.org/current/maps. I do not observe any problem when creating/loading a permalink.
It passes the unit test.
> Use fetch hook for loading state if a permalink id is provided on maps page

- components/VersionHistory/VersionHistory.vue
- nuxt.config.js
- pages/datasets/_datasetId.vue
The purpose of this PR is to add the ability to see different versions of a dataset.
https://app.clickup.com/t/m130t1
https://www.wrike.com/open.htm?id=603833242
- Go  to [this dataset](http://localhost:3000/datasets/43?type=dataset)
- You should see the latest version, version 5
- Note the files and description of the dataset
- Click on "Version 5" in the header 
- Version dialog should open up
- Click on "Version 1"
- You should be taken to version 1 of that dataset, and the description and files should show the data from version 1
- A simulation should not have the version shown.
> Dataset versions - cu-m130t1

- components/SearchResults/ProjectSearchResults.vue
The purpose of this PR is to show the image for the lead institution on the projects page.
https://app.clickup.com/t/m12z79
https://www.wrike.com/open.htm?id=489589055
- Go to the [projects page](http://localhost:3000/data?type=sparcAward)
- Images should be listed for institutions in the Lead Institution column
> Show image for lead institution

- components/FilesTable/FilesTable.vue
The purpose of this PR is to allow users to open native files in a browser.
https://app.clickup.com/t/m1339z
https://www.wrike.com/open.htm?id=550853064
Go to the following datasets and the path in the files tab to test each file type.
- jpg: http://localhost:3000/datasets/12?type=dataset - files / source / Dorsal
- text: http://localhost:3000/datasets/12?type=dataset - files
- pdf: http://localhost:3000/datasets/86?type=dataset - files/primary
- mp4: http://localhost:3000/datasets/54?type=dataset - files /derivative /sam-P21 BAT /ses-B3tub
- png: http://localhost:3000/datasets/12?type=dataset - files /docs /Interactive map /Images
> Allow native files to open in browser

- components/HelpCard/HelpCard.vue
The purpose of this PR is to fix a bug when draft help documents don't have data, the page would crash.
- Go to the [help page](http://localhost:3000/help)
- Scroll down to the last item of the General section
- Click on "Other SPARC Policies"
- You should see a page for Other SPARC Policies
> Account for draft help documents that may not have data

- components/DatasetVersionMessage/DatasetVersionMessage.vue
- pages/datasets/_datasetId.vue
The purpose of this PR is to add a banner image when viewing an older version of a dataset.
- Go to [an older version of a dataset](http://localhost:3000/datasets/43/version/2?type=dataset)
- The banner should be visible at the top
- Click on  "more recent version" link in this banner
- You should be taken to the most recent version of the dataset
- Banner should not be visible
> feat(Datasets): Add banner when viewing older version

- components/ContactUsForms/NewsletterMixin.js
The purpose of this PR is to account for email already existing in Mailchimp. Before, the form would not submit and display an error.
- Go to the [Contact form](http://localhost:3000/contact-us?type=general)
- Enter information, including your first, last, email and checking "newsletter" check
- Open network tab to see the `/mailchimp` response
- If your email was already added to the list, you will see this data in the response and the form should be in the submitted state
- If your email was not in that list, submit it again to test
> Contact form - Account for email already existing in Mailchimp

- components/HelpCard/HelpCard.vue
The purpose of this PR is to fix the help page links for entries that do not have slugs. In addition, I removed the Typescript definition for this component as it was not working adding the simplest things (that do work on other components.)
- Go to the [help page](http://localhost:3000/help)
- Clicking on "Getting started" should take you to that page
- Clicking on "Other SPARC Policies" should take you to that page
> Fix help page links

- components/SearchResults/DatasetSearchResults.vue
- components/SparcPill/SparcPill.vue
- pages/data/index.vue
- pages/datasets/_datasetId.vue
The purpose of this PR is to add the ability to see embargoed datasets on the SPARC Portal.
- Go directly to [an embargoed dataset](http://localhost:3000/datasets/87?type=dataset)
- You should only see the following: Dataset metadata and release date (i.e. title, subtitle, contributors, authors, summary, etc.) and no files or scientific metadata
- Go to [a published dataset](http://localhost:3000/datasets/109?type=dataset) and you should see all data
- Go to [a simulation](http://localhost:3000/datasets/84?type=simulation) and you should see all the data
- Open  `/pages/data/index.vue` and change line 297 from `: 'organization=SPARC%20Consortium'` to `: ''`. This will allow embargoed datasets to be returned (there are no embargoed datasets in the SPARC Consortium)
- Checking "Embargoed" …
> Embargoed datasets - cu-q10rjt

- components/EventCard/EventCard.vue
- components/FeaturedEvent/FeaturedEvent.vue
- components/NewsListItem/NewsListItem.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
The purpose of this PR is to do the following with the news and events page
- Redesign
- Only show 2 news and 2 events, and linking to their landing pages
- Add Featured Event at the top
- Only link to a news or event details page if there is content. If there isn't, link to the external URL.
- Go to the [news and events page](http://localhost:3000/news-and-events)
- Featured news should be at the top and its links should go to the details page
- Latest news and Events should be in two columns beside each other, and the events tabs should work
- The featured event should not be listed in the Events
- News or events should only go to the details page if there is content. If there isn't, link to the external URL.
- Clicking on "View all news" doesn't work yet, as there is no News landing …
> News and events page redesign - cu-qn19eu

- components/EventCard/EventCard.vue
- components/FeaturedEvent/FeaturedEvent.vue
- pages/news-and-events/events/index.vue
The purpose of this PR is to:
- Add logic to support the new `requiresADetailsPage` field in Contentful. This will be used to determine if an event should look to its detail page or its URL
- Fix featured event on Events landing page. This was currently not being displayed because the Contentful query was incorrect.
- Go to the [events landing page](http://localhost:3000/news-and-events/events)
- The featured event should be at the top
- Clicking on the featured events name or "Learn More" button should take you to the event's URL in a new tab
- Clicking on an event's name should take you to the event's URL in a new tab
> Conditional events details page and Featured Event fix -  cu-qn19eu

- pages/news-and-events/index.vue
The purpose of this PR is to add support to parse markdown in hero of the news and events page. This will be used to link to the Submit News form.
- Go to the [news and events page](http://localhost:3000/news-and-events)
- The hero copy should be above the search bar in the hero, and the word "request" should be linked to the Wrike form.
> Add support to parse markdown in hero

- pages/news-and-events/events/index.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
The purpose of this PR is to address the following feedback:
News and events page
- Add "Show (X) past events" button
- This button should lead directly to the past events tab on the past events page
Events page
- Past events tab should have a "Show all" button to show all events after four
General
- Past events older than two years should not be shown
- Go to the [news and events page](http://localhost:3000/news-and-events)
- Click on the Past events tab
- Click on the "Show All (18) Past Events" button
- This should take you to the past tabs on the events page, showing four events
- Click on the "Show All (18) Past Events" button
- This should show all past events
> QA news events - cu-q10kg4

- pages/news-and-events/events/index.vue
- pages/news-and-events/news/index.vue
The purpose of this PR is to Cap "Portal" in hero for news and events landing pages.
Go to each news and events landing pages and "SPARC Portal" should appear in the hero.
> Cap "Portal" in hero for news and events landing pages

- components/FilesTable/FilesTable.vue
The purpose of this PR is to add the feature that allows the user to copy the file URL to their clipboard.
- Go to the [files tab of a dataset](http://localhost:3000/datasets/109?type=dataset)
- Open the menu for a file
- Click on "Copy URL to Clipboard"
- Toast should appear, and the S3 URL should be in your clipboard
> feat(Files): Copy File URL to clipboard

- pages/resources/index.vue
- pages/resources/model.ts
The purpose of this PR is to add Databases and Information Services category for Resources.
- Go to the [Database](http://localhost:3000/resources?type=Databases) tab on the Resources page
- You should see the resources tagged Database
- Go to the [Information Services](http://localhost:3000/resources?type=Information%20Services) tab on the Resources page
- You should see the resources tagged Information Services
> feat(Resources): Add Databases and Information Services category

- components/NewsEventsPage/NewsEventsPage.vue
- components/Resources/ResourcesSearchResults.vue
- pages/news-and-events/events/_id.vue
- pages/news-and-events/news/_id.vue
- pages/resources/_resourceId.vue
The purpose of this PR is to add a detail page for resources
- Go to the tools and resources page
- Click on a name of a resource to be taken to its detail page
- For a more complete page, visit [Blackfynn Data Management Platform](http://localhost:3000/resources/56y6lcUnJGdIUbo2btPzxk)
- Visit an [event page](http://localhost:3000/news-and-events/events/5i2AUXJ0JU57vDgaVpCqcz) to verify everything still works
- Visit a [news page](http://localhost:3000/news-and-events/news/1IAtotegXUlp6JziLsULtn) to verify everything still works
> feat(Resources): Add detail page

- components/Resources/ResourcesSearchResults.vue
The purpose of this PR is to add support for the "requires details page" from Contentful.
- Go to the [tools and resources page](http://localhost:3000/resources?type=sparcPartners)
- Clicking on all but "Blackfynn Data Management Platform" names should take you to their external site
- Clicking on "Blackfynn Data Management Platform" should take you to its details page
> Add support for Contentful "requires details page"

- components/SparcPill/SparcPill.vue
- pages/data/index.vue
The purpose of this PR is to an issue with find data search with dataset filters (embargo) where pagination always showed first page results. In addition, it fixes an issue with the "Embargoed" pill on Safari.
- Go to the [dataset search page](http://localhost:3000/data?type=dataset)
- Go to page 2, and you should see page 2 results
- Check the "Embargo" status on the left
- You should be taken back to page 1
- Uncheck "Public"
- You should only see Embargoed datasets
- The "Embargoed" pill over a dataset's image should not be truncated on Safari
- Check "Public"
- You should see all datasets
- Click on page 4
- You should see page 4
- Refresh the browser
- You should see page 4 results for all datasets
> Fix issue with dataset filters and pagination

- components/EventCard/EventCard.vue
- components/FeaturedEvent/FeaturedEvent.vue
- components/HomepageNews/HomepageNews.vue
- components/SparcCard/SparcCard.vue
- pages/news-and-events/news/_id.vue
The purpose of this PR is to make event images links.
- Go to the homepage and scroll down to the News and Upcoming Events section
- The images should link to the same link as the title of the item (internal or external, depending on the entry)
- Go to the News and Events page
- The featured event's image should link to the same link as the title of the item
- The two upcoming and two past event's image should link to the same link as the title of the item
- Click on "Show all events" to go to the events landing page
- The images should link to the same link as the title of the item (internal or external, depending on the entry)
> Make event images links

- components/HomepageNews/HomepageNews.vue
The purpose of this PR is to Fix homepage news image link. Previously, this link wasn't using the `nuxtLink()` which computes the link based on the entry type.
You will need to update your `CTF_CDA_ACCESS_TOKEN` environment variable if you haven't yet already. This can be found on Heroku.
- Go to the homepage
- Scroll down to the "Request for project proposals for the 2021 SPARC FAIR Codeathon" event
- Click on its image
- You should be taken to that event's detail page
> Fix homepage news image link

- components/NewsEventsPage/NewsEventsPage.vue
Display message after clicking on "Share link" icon on the News and Events page. This is the same pop up used on the dataset page after clicking on the "Copy citation".
Ticket can be found [here](https://www.wrike.com/open.htm?id=681288214).
Manually tested and can be tested [here](https://alan-wu-sparc-app.herokuapp.com/news-and-events/events/460HOij0sXC0MDUzJ0c899).
> Notify user when share link button on News and Events page is pressed.

- pages/resources/index.vue
1) Always show total number of resources indicator
2) Reset pagination when switching tabs
Deployed locally
1) Go to resources page and selected multiple pages. Verfiy that indicator always shows total nr results
2) Switch tabs from various pages and verify that first page of results is shown.
> fix total nr resources

- components/SearchResults/DatasetSearchResults.vue
- pages/data/index.vue
Updated the dataset search results table view to match the wireframes for faceted browse, found here: https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403?collectionId=aac5183e-7ed8-469a-9d73-7e39036ce2ef&sha=deb221da2686562e2063344b84eaa2807aba5346
I tried to use an element ui table for displaying the list of properties but element ui makes it impossible to customize it how we wanted so I used an HTML table instead. 
I still have not updated the endpoint to point at algolia. That will be part of my next changeset. 
I created a constant array that maps what properties we want to display along with what the actual name of the property on the object is. I wasn't sure of a better way to do this. Feel free to suggest alternatives.
I left the sorting logic for the results table …
> Faceted browse UI v785th search results UI

- package.json
- yarn.lock
ZoomIn button in the scaffold viewer is not working correctly. This commit install the latest version of map viewer and scaffold viewer which address the issue. The ticket is here - https://www.wrike.com/open.htm?id=713253900
The bug fix can be tested here https://mapcore-demo.org/current/sparc-app/maps/?id=9f2d9299 and here
https://mapcore-demo.org/current/sparc-app/datasets/scaffoldviewer?scaffold=99%2F3%2Ffiles%2Fderivative%2FScaffold%2FratHeart_metadata.json
> Fix the ZoomIn funciton in scaffoldviewer

- components/header/Header.vue
- nuxt.config.js
- package.json
- pages/data/index.vue
- plugins/algolia.js
- yarn.lock
Populated the datasets and simulations data from the algolia index, while maintaining filtering for embargoed and public datasets. Also hid second search bar. TODO: Reimplement sorting for the data based off date or title, add additional facets and properties metadata, and update the tabs to reflect the wireframes.
I ran the changes locally and verified functionality. Datasets and Simulations tabs should work the same as before as should the emargoed and public filters. Additionally, the second search bar should now be hidden
> Accessed Algolia Pennseive index

- pages/news-and-events/community-spotlight/success-stories/_id.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
Gazelle pointed out a few points that don't match the design and had a few design changes since the wireframes were created.
They are:
- Only two success stories to be shown in news-and-events
- Publication date was unformatted
- Breadcrumbs for story detail to be changed to > news-and-events > community-spotlight > story-id
- Story end now links out to community-spotlight, not success-stories
Changes of this branch can be viewed at:
https://sparc-succcess-stories.herokuapp.com/news-and-events/
Discussion can be viewed on wrike at:
https://www.wrike.com/open.htm?id=660279044
Run locally and on a heroku clone
> A few requested changes from gazelle

- components/header/Header.vue
- pages/news-and-events/index.vue
- typo in mobileSearchOpen
- Fix for 90% zoom at Asher's request https://www.wrike.com/open.htm?id=678414135
On https://sparc.science/news-and-events. If you are on a large external screen and at 90% zoom (which sometimes seems to be the default), the events cards will stack vertically as opposed to horizontally. 
I've adding a bigger buffer in the width calculation to keep this from happening until we get to 33% zoom/
While implementing this I noticed a typo in the mobile search.
Ran locally and confirmed the bug on sparc.science.
Zoom at 90% after this change:
> 90% zoom fix

- components/SearchResults/EventSearchResults.vue
- components/SearchResults/NewsSearchResults.vue
- pages/data/index.vue
In the browse data page I added 3 new tabs 'News', 'Events', and 'Resources' tabs. This is for the time being as I work on faceted browse for the other tabs. Once faceted browse is implemented for the other tabs I will be able to condense the tabs to match the final wireframes, but since that is planned for next sprint I want to get these changes out for the time being so that a user still has the ability to search for news, events, and resources using the browse functionality.
My tab changes:
Final wireframe changes:
Navigate to the added tabs and verify content is there. Performed queries on the results as well as clicked on their hyperlinks to navigate to their details pages
> faceted-browse-v785th-add-tools-and-resources-and-news-and-events-tabs

- assets/components/_el-tooltip.scss
- components/FacetMenu/DatasetFacetMenu.vue
- components/FacetMenu/FacetMenu.vue
- components/FacetMenu/SparcInfoFacetMenu.vue
- components/FacetMenu/TagsContainer.vue
- components/SearchResults/DatasetSearchResults.vue
- pages/data/index.vue
- pages/data/utils.ts
Implemented faceted browse for datasets tab. Dataset search results can now be narrowed down based off facet selections. Selections are persisted between tab changes and results are displayed in publication date order:
Wireframes can be found here:
https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403?collectionId=aac5183e-7ed8-469a-9d73-7e39036ce2ef&collectionLayerId=77147cf9-0a22-4770-af6f-cdd93e0cb131&present=true&preview=false&sha=deb221da2686562e2063344b84eaa2807aba5346&showComments=false
In regards to the show all checkbox functionality, that has been diregarded as an anti-pattern and the deselect button has been added in its place
Pulled down changes and:
-entered a search query and verified that only relevant facets were shown
-selected …
> faceted-browse-v785th-update-and-show-facet-menu

- package.json
- pages/datasets/biolucidaviewer/_id.vue
- yarn.lock
Upgrade to version 0.2.0 of @abi-software/gallery.  This version only loads the visible cards onto the DOM.  This also hides the permalink button on Biolucida viewer, which is not working.
Tested with dataset 137 which contains 10000+ image files.
> Update to version 0.2.1 of @abi-software/gallery

- components/FacetMenu/FacetCategory.vue
- components/FacetMenu/FacetLabel.vue
- components/FacetMenu/NewsAndEventsFacetMenu.vue
- components/FacetMenu/ToolsAndResourcesFacetMenu.vue
- pages/data/index.vue
Added the Tools and Resources Facet Menu as shown below:
Wireframes can be viewed here:
https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403?collectionId=aac5183e-7ed8-469a-9d73-7e39036ce2ef&collectionLayerId=e925ad79-4536-412f-91fe-c2e0782102b9&present=true&preview=false&sha=9b4c7ac502cad094b352d225a16389b3d526ff0d
Filtered results based of different selections. Tested select/deselect functionality. Tested persisting through page refreshes and tab changes
> Add tools and resources facet menu

- nuxt.config.js
- pages/data/index.vue
Updated code to use an env var for deciding what index in algolia to pull from now that we have a prod algolia index
Tested locally and added the env var in Heroku so once changes are merged then staging automatic re-deploy should be fine
> added env variable for algolia index

- pages/datasets/_datasetId.vue
Responding to https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=467396116&pid=416152743&cid=415614298 now contributors list always shows in its full length. Before, if the list had more than 15 contributors, only the first and last were shown, together with button to show all of them.
Manually tested
> Contributors list always visible

- components/FacetMenu/ToolsAndResourcesFacetMenu.vue
Bug fix for tools and resources facet menu. Not displaying devices results bc I forgot the 's'
Verified locally
- [] I have added unit tests that prove my fix is effective or that my feature works
> Fixed typo in devices id

- components/FacetMenu/NewsAndEventsFacetMenu.vue
- components/SearchResults/NewsAndEventsSearchResults.vue
- pages/data/index.vue
Added the community spotlight option to the news and events facet menu as shown in the wireframes:
https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403?collectionId=aac5183e-7ed8-469a-9d73-7e39036ce2ef&collectionLayerId=2ec2f953-7a67-4690-8417-994b7d9b7e3d&present=true&preview=false&sha=deb221da2686562e2063344b84eaa2807aba5346
I realized that I forgot to add this option when first implementing this facet menu
Verified locally that the one published listing is shown
> Added Community Spotlight to News Facet Menu

- components/VersionHistory/VersionHistory.vue
- pages/datasets/_datasetId.vue
Wrike ticket for this sprint 14 ticket can be found here:
https://www.wrike.com/open.htm?id=579586850
Details of changes:
View at: https://sparc-pub-date-fix.herokuapp.com/datasets/29?type=dataset
View at: https://sparc-pub-date-fix.herokuapp.com/datasets/32?type=dataset
Tested locally and can be viewed at:
https://sparc-pub-date-fix.herokuapp.com/
> Fix first published date using the wrong date

- package.json
- yarn.lock
This is to fix a bug which was discovered after Team Red has raised a question about the validity of older permalinks on the newer interface.
Details:
Split screen button not active with older permalinks. 
Please test it on this [link](https://mapcore-demo.org/current/sparc-app/maps/?id=112fc346), it was used for testing when permalink was first implemented and introduced to the SPARC app.
> Better support for permalinks of the map page

- Procfile
Set max_old_space_size when running nuxt start for heroku.
Deployed and tested here - https://alan-wu-sparc-app.herokuapp.com/datasets/imageviewer?dataset_id=20&dataset_version=3&file_path=source%2FDSC_0039.jpg&mimetype=image%2Fjpeg
The image previously crashing the site is working and the built was working as well.
> Set max_old_space_size in Procfile.

- components/Resources/FeaturedResource.vue
- pages/datasets/_datasetId.vue
Corrected small but critical bug impeding the front end to display a simulation dataset detail with no corresponding simulation template.
> IMPORTANT: Fix for computational model dataset detail pages

- pages/resources/_resourceId.vue
closes https://www.wrike.com/open.htm?id=651174399
Manual test
> Truncated URL in Tools&Resources detail page

- components/FacetMenu/ToolsAndResourcesFacetMenu.vue
- pages/resources/model.ts
closes https://www.wrike.com/open.htm?id=773974064
**IMPORTANT**: All changed ``SPARC Resource``s will need to be published for this to work in production. They must be published in Contentful once this is merged to production. The affected ones are all the Resource that previously had "Databases" among their ``resourceType``s
This PR merges the changes in the frontend code to use the changes made in Contentful.
The changes is in Contentful:
* All ``resourceType``s were migrated to include "Data and Models" instead of Databases.
```javascript
module.exports = function (migration) {
migration.transformEntries({
contentType: 'sparcPartners',
from: ['resourceType'],
to: ['resourceType'],
transformEntryForLocale: async (from, locale) => {
if (from.resourceType) {
const before = …
```
> Modified "Databases" to "Data and Models" in SPARC Resource contentType

- package.json
- pages/maps/index.vue
- yarn.lock
This is a fix for a bug causing the permalinks to stop working on the map page.
This also changes the endpoint used by the sidebar, the endpoint used now uses DOI instead of dataset ID to lookup for information.
I have ran some tests and it seems to work fine with the fix.
The fix can be tested using this link here - https://mapcore-demo.org/current/sparc-app/maps/?id=ad42b477
> Fix incorrect sparc api used by generating permalink in the maps page.

- components/ImagesGallery/ImagesGallery.vue
The path to the segmentation file is not the full path on AWS this fix corrects that.
Tested manually with dataset 43.
> Segmentation viewer path correction

- services/discover.js
The parameter to getSegmentationInfo now includes the `files` part of the path.  This PR removes `files` from the formulation of the dataset_path value.
Manually test with dataset 43.
> Correction for getting segmentation metadata.

- components/DatasetDetails/SimilarDatasetsInfoBox.vue
- components/FacetMenu/FacetCategory.vue
- components/ImagesGallery/ImagesGallery.vue
- mixins/format-string/index.js
- pages/datasets/_datasetId.vue
- pages/datasets/flatmapviewer/_id.vue
- services/scicrunch.js
This pull request address the issue specified here - https://www.wrike.com/open.htm?id=745347248/
Uberon and taxon are now displayed as organ and species. The uberon id on the image gallery is now displayed as organ name.
I have added a mixin and services to support the required feature.
This has been tested manually.
This can also be tested in the following page - https://mapcore-demo.org/current/sparc-app/datasets/169?type=dataset&datasetDetailsTab=images
The uberon id should now be organ name on the image gallery.
Click on the flatmap image to go to the Flatmap viewer -> the uberon id and taxon should now be organ and species respecitvely.
> Replace uberon and taxon with organ and species

- components/DatasetDetails/DatasetActionBox.vue
Added 'View Scaffold' button to action box which will direct a user to the gallery tab to view the scaffold in the scaffold viewer
Locally
> added view scaffold button

- components/DatasetDetails/DatasetAboutInfo.vue
The NIH award number now becomes a link to the funding project's page.
New feature (non-breaking change which adds functionality)
Manual
> Award number links to the project's page

- middleware/mailchimp.js
- pages/signup/index.vue
Named middleware was not executing redirect to an external url correctly In development environment eventhough it worked locally. I updated it to use an anonymous middleware instead.
Locally, not sure why the named middleware was not working
> changed to use anonymous middleware redirect

- pages/news-and-events/community-spotlight/index.vue
This is a quick fix for the fact that pagination should not be on the `community-spotlight` page.
Details are on this wrike ticket:
https://www.wrike.com/open.htm?id=678413958
A heroku instance of this change is available here:
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight
Tested locally and available at:
https://sparc-succcess-stories.herokuapp.com/news-and-events/community-spotlight
> Remove pagination from community spotlight

- components/ContactUsForms/BugForm/BugForm.vue
Attempts to close https://www.wrike.com/open.htm?id=656177298
An email should be sent to the user also when he requires to follow up in the second form (issue reporting)
Here the front end code is modified so the form's payload includes a field with the user's email.
- Bug fix (non-breaking change which fixes an issue)
Manual testing
> Mail to user from issue reporting form

- pages/resources/index.vue
When a user on the resource page clicks on more resources,
then the "SPARC resource" facet is checked by default.
Locally run, 
Select the button --> verify that facet is checked.
> default to sparc resources on resource page

- components/FacetMenu/ToolsAndResourcesFacetMenu.vue
- pages/data/index.vue
- pages/resources/index.vue
Made changes to always select developed by sparc facet by default when navigating to tools & resources tab. This change will be deployed as a hotfix upon sign off of correct behavior in staging
Locally
> navigation now always selects sparc resource by default

- pages/resources/index.vue
I thought we no longer needed the params defined in the nuxt link, but Asher found an issue when navigating back and forth between find data > tools and resources and the header tools and resources
Locally
> added back query params into nuxt link

- components/header/Header.vue
Hotfix to take users to /data from the header search.
Previously users were taken to the 'Tools and Resources' page.
Wrike ticket defining this can be found here:
https://www.wrike.com/open.htm?id=869259065
Tested locally. 
Seeing as it is quite a small change I did not create an instance for testing. The lines changed here should hopefully be self explanatory
> Hotfix: 'resources' searched in header now takes user to 'data' page

- components/header/Header.vue
Need to take into account checking sparc resource by default when navigating from search bar now that Jesse's changes got merged in
Locally
> check by default

- pages/datasets/scaffoldviewer/_id.vue
- Scaffold page now supports both the new and old routes
- old route was being used from the /dataset page before this change.
This commit does not change that
- Route parameters are added on mounted
This fixes the issue where scaffolds were not opening from file browser
This issue happend because the scaffold page's input has been changed from using `@route.query.scaffold` to
`@route.query.dataset_id` , `@route.query.dataset_id`  , and `@route.querey.file_path`
Can see this in this screenshot:
The page would still work from the 'filesTable' if these new route queries had been added to the 'filesTables' output, but they don't seem to be there yet. It is still outputing the `scaffold` query parameter as before.
This change allows the old urls to continue working (as they are still in use), …
> Scaffold routes hotfix:

- components/FilesTable/FilesTable.vue
- components/ImagesGallery/ImagesGallery.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Updated what pennsieve endpoint is used to retrieve a file from pennsieve for the files/_index route. Running into an issue getting file containing multiple extensions.
Also contains a patch for discrepancy between file paths that contain spaces and/or commas and their corresponding s3 uri
Locally
> Patch for how file is retrieved

- components/FilesTable/FilesTable.vue
Updated the scaffold link that gets generated in the files table to include the correct query params in the updated route.
Locally, you can test it by navigating to /datasets/125?datasetDetailsTab=files&path=files%2Fderivative%2FScaffolds%2F and clicking the scaffoldMap_metadata.json file to view it
> fixed scaffold link generated from files table

- mixins/fetch-pennsieve-file/index.js
- pages/datasets/biolucidaviewer/_id.vue
- pages/datasets/imageviewer/_id.vue
- pages/datasets/plotviewer/_id.vue
- pages/datasets/scaffoldviewer/_id.vue
- pages/datasets/segmentationviewer/_id.vue
- pages/datasets/videoviewer/_id.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Same fix for accessing file from pennsieve is now being made to the biolucida viewer route accessed via the gallery tab as was made to the route accessed via the files table.
Locally. You can verify the fix by navigating to dataset 221 and using the gallery to view images
> similar fix to retrieve file as made to file table

- components/header/Header.vue
- pages/datasets/scaffoldviewer/_id.vue
This is a pull request on the master branch for the hot fix for backward compatibility for the older scaffoldviewer url format.
The current production site is using this hot-fix.
> Hot fix scaffold urls

- components/DatasetDetails/DatasetFilesInfo.vue
- components/FilesTable/FilesTable.vue
- pages/datasets/_datasetId.vue
1. Add ability to open scaffold views, This is defined as a milestone in this wrike ticket: https://www.wrike.com/open.htm?id=546448956
2. Fix for the files table not opening scaffolds
This is a rework of the scaffold hotfix to reduce the number of requests to sparc-api.
It passes the scicrunch data from the /data page into the filesTable.vue to check if files are scaffolds or scaffold views.
Tested locally and this branch can be viewed at:
https://hot-fix-scaffolds.herokuapp.com/datasets/76?datasetDetailsTab=files&path=files%2Fderivative
> Add ability to open scaffold views from the files table

- pages/datasets/biolucidaviewer/_id.vue
Datasets containing biolucida viewer images in the gallery that do not have biolucida objects, do not contain file path info. In this case we cannot show the images file path.
Locally. You can verify with the two datasets below:
https://sparc.science/datasets/225?type=dataset&datasetDetailsTab=images 
https://staging.sparc.science/datasets/226?type=dataset&datasetDetailsTab=images
> fix for image_info not containing file path info

- mixins/fetch-pennsieve-file/index.js
Some files paths letter casing does not match their s3 uri path and it is causing errors when finding the file
Locally. You can verify with:
localhost:3000/datasets/biolucidaviewer/1989?view=MTk4OS1jb2wtMTI3&dataset_version=3&dataset_id=77&item_id=N%3Apackage%3A4988880f-edf3-4b4d-b630-abaf5389b02a
> applied case sensitivity fix

- components/FilesTable/FilesTable.vue
Scaffold views broke when scicrunch switched to using an array for 'isDerivedFrom.path'
This PR fixes the scaffold views in the filesTable
> Fix for scicrunch now using an array on 'isDerivedFrom.path'. (Previously broke scaffold views in FilesTable)

- components/ContactUsForms/BugForm/BugForm.vue
Users can now provide with the problematic URL if they selected "Other" in the "Is this about a specific page or resource?" section. The field is mandatory if displayed.
- New feature (non-breaking change which adds functionality)
Manually
> Bug reporting form - Added URL input

- package.json
- yarn.lock
Added context cards for scaffolds
This is to meet this milestone:
[M1.3.3 Display scaffold map contextual information on the SPARC Portal](https://www.wrike.com/open.htm?id=688989109)
To test go to:
https://jesse-sprint-19.herokuapp.com/maps
and open up the 'Generic mouse colon scaffold' from the sidebar
Tested by myself and @alan-wu in mapintegratedvuer in the mapintegratedvuer standalone app. 
Also can be viewed for further testing here:
https://jesse-sprint-19.herokuapp.com/maps
> Update mapintegratedveur: Update adds context cards for scaffolds

- components/header/Header.vue
I have no idea what difference this change will make since it worked locally before, but this is how we were determining the feature flag for showing the facet menu before. I'm giving it a try since I have no other ideas. Heroku simply appears to not be listening to env var changes
Locally
> last ditch effort

- components/DatasetDetails/DatasetHeader.vue
- components/DatasetDetails/DatasetReferences.vue
- pages/datasets/_datasetId.vue
Rename the 'citation-info' Vue component to 'references'
This is done to have consistency with the fact that this tab now relates
to references, not citations.
It also changes the url route required to get to the 'references' tab.
(Previously this url route was 'citations'). In example: 
https://staging.sparc.science/datasets/231?type=dataset&datasetDetailsTab=citations
Can test this branch at:
https://jesse-sprint-19.herokuapp.com/datasets/231?type=dataset&datasetDetailsTab=references
> Rename the 'citation-info' component to 'references'

- components/Resources/FeaturedResource.vue
- pages/resources/index.vue
This pull request address the issue reported here - https://www.wrike.com/open.htm?id=689977061
Clicking on the thumbnails / titles now take users  directly to the external resources without going through the details page.
This has been tested manually and here - https://mapcore-demo.org/staging/sparc-integrated-features/resources
Please note that the "View resource" button above will not work on the link above but it should not be a problem on staging and production site.
> Click on thumbnails/titles bring users to external links on T/R page.

- components/CitationDetails/CitationDetails.vue
- components/ImagesGallery/ImagesGallery.vue
- pages/datasets/_datasetId.vue
- pages/datasets/flatmapviewer/_id.vue
- Now use rat flatmap if the species of flatmap does not exist
- A message is given to the user letting them know this has happened
This has been requested for the sprint 19 QA in this ticket:
https://www.wrike.com/open.htm?id=844804093
This PR also implements a small citation text change from this ticket:
https://www.wrike.com/open.htm?id=830385307
Tested locally and can be tested here:
https://jesse-sprint-19.herokuapp.com/datasets/flatmapviewer?dataset_version=2&dataset_id=142&taxo=NCBITaxon%3A10114&uberonid=UBERON%3A0001155&for_species=dog&organ=colon
https://jesse-sprint-19.herokuapp.com/datasets/142?type=dataset&datasetDetailsTab=images
> Imagine Gallery: Use rat flatmap when other flatmaps are not available

- pages/datasets/_datasetId.vue
Fix empty image gallery on some datasets including the following page - https://staging.sparc.science/datasets/237?type=dataset
This has been fixed manually and deployed here - https://mapcore-demo.org/current/sparc-app/datasets/237?type=dataset
> Fix empty image gallery

- package.json
- pages/datasets/flatmapviewer/_id.vue
- yarn.lock
This fixes an issue with flatmap styling currently found on [staging.sparc.science](https://staging.sparc.science/datasets/flatmapviewer?dataset_version=2&dataset_id=223&taxo=NCBITaxon%3A10114&uberonid=UBERON%3A0000945&for_species=undefined&organ=stomach)
This also address a problem with loading flatmapvuer and scaffoldvuer may overwrite some global css (Take a look at the top right search icon after loading up the flatmap page).
This has been tested manually and deployed here - https://mapcore-demo.org/current/sparc-app/datasets/flatmapviewer?dataset_version=2&dataset_id=223&taxo=NCBITaxon%3A10114&uberonid=UBERON%3A0000945&for_species=undefined&organ=stomach
> Fix flatmap viewer styles and side effect from it.

- components/BiolucidaViewer/BiolucidaViewer.vue
Permalink icon was not being shown in staging: https://staging.sparc.science/datasets/biolucidaviewer/850?view=ODUwLWNvbC05NQ%3D%3D&dataset_version=4&dataset_id=31&item_id=N%3Apackage%3Ab35bbe09-2fcc-496c-be8b-7c0ee43f1395
I believe it has something to do with the biolucida iframe that gets loaded overriding the css. I think making it client-only will fix the problem
Locally, although we won't know for sure if this working until pushing to staging
> stop imported biolucida viewer from hiding icon

- middleware/documentationHubRedirects.js
- nuxt.config.js
- plugins/documentation-hub-redirects.js
Implemented logic for pulling in a list of redirect urls from contentful that we use to redirect a user to the documentation hub if they are using a legacy sparc documentation url
Locally, by attempting to navigate to: /help/2022-sparc-fair-codeathon
> Implemented redirect logic for documentation hub

- components/SetupNewUser/SetupNewUser.vue
Add password to body of merge accounts request so that the user does not have to request the password for their Pennsieve account after linking
Locally via pennsieve.net, localhost, and orcid sandbox
> Add Password to merge accounts request

- components/ContributorItem/ContributorItem.vue
- nuxt.config.js
In order to show https://www.wrike.com/workspace.htm?acc=3203588#/inbox/task/830482705 is working, I created an env var  to Orcid api to mock a failed request
Locally
> Make orcid api url an env var

- components/DatasetDetails/DatasetHeader.vue
- components/DatasetDetails/SimilarDatasetsInfoBox.vue
- components/FilesTable/FilesTable.vue
- package.json
- yarn.lock
Hide tooltips if they are erroneous. In order to do so I listen for a mouseenter event and use the targets scrollable width and offset width to programmatically hide/show the tooltip using the system design's sparc-tooltip's newly added hide() function.
*Note that I also removed the number of citations displayed in the header for the time being to knock out this wrike ticket: https://www.wrike.com/workspace.htm?acc=3203588#path=folder&id=824490095&c=list&vid=64376648&p=589157244&a=3203588&t=895002281&so=2&bso=10&sd=0&f=&st=space-441356195
Locally
> Hide tooltips if not necessary

- components/DatasetDetails/SimilarDatasetsInfoBox.vue
- components/FilesTable/FilesTable.vue
- package.json
- yarn.lock
Moved logic to dynamically show/hide tooltips to the system design component itself so that it is more reusable and consistent. This should make it easier for other cores to use and implement
Locally
> Moved hiding tooltips logic to sparc tooltip

- package.json
- yarn.lock
This update uses the latest version of mapvuer. It contains the following changes:
Upstream downstream pop ups - https://github.com/ABI-Software/flatmapvuer/pull/64
Dynamic flatmap markers - https://github.com/ABI-Software/mapintegratedvuer/pull/102
Manually tested and deploy here - https://alan-wu-sparc-app.herokuapp.com/maps
The map vuer itself passes the e2e testing - https://autotest.bioeng.auckland.ac.nz/jenkins/job/mapintegratedvuer/304/
> Update mapintegratedvuer dependencies.

- components/VersionHistory/VersionHistory.vue
- pages/datasets/_datasetId.vue
added a changelog column to the versions tab on the dataset details page as per https://www.wrike.com/open.htm?id=795603064 allowing a user to download that dataset version's changelog if one is present.
Locally via dataset 270
> Added ability to download dataset changelog

- mixins/fetch-pennsieve-file/index.js
- nuxt.config.js
There currently is an issue where the files page crashes when a directory is included in the 'files' object returned from pennsieve.
This PR adds more checks to keep this from crashing the app. 
You can see an example of it crashing here:
https://sparc.science/file/34/5?path=files%2Fderivative%2Fstim_proximal-colon_manometry.csv
ran locally, clone this branch to test
> Fix issue where fetchPennsieve file crashes the app on the /files page

- package.json
- yarn.lock
Fix issue where no context cards annotated would crash a scaffold on the maps page. (This can be reproduced with dataset 77 by opening a scaffold from the sidebar)
Can be tested at:
https://context-cards-demo.herokuapp.com/maps
(will be available 10minutes after this PR)
> Fix where no context card was breaking scaffolds

- components/DatasetDetails/DatasetActionBox.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
- components/FilesTable/FilesTable.vue
- mixins/fetch-pennsieve-file/index.js
- pages/datasets/_datasetId.vue
- utils/constants.js
Added the ability for a  logged in user to request access to an embargoed dataset
Locally via test dataset 275. However cannot verify %100 until in staging for now since we do not have a pennsieve.net test dataset yet and localhost is not whitelisted in pennsieve.io
> add request embargoed data button

- components/DatasetDetails/DatasetActionBox.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
- components/DatasetDetails/DatasetFilesInfo.vue
Added the user token to the pennsieve discover api requests in order to account for viewing embargoed data that users that have granted permission for
Locally via Postman, but cannot fully test until on staging
> Added user token to pennsieve files requests

- components/DatasetDetails/DatasetFilesInfo.vue
- components/DatasetDetails/DatasetInformationBox.vue
- pages/datasets/_datasetId.vue
Files were never getting shown for embargoed datasets even if the user had been granted permission
Locally
> Updated hasFiles to include embargoed datasets

- nuxt.config.js
- package.json
- plugins/vue-gtag.client.js
- yarn.lock
Add GA4 tracking. The tracking id should now be set using the environment variables - GOOGLE_ANALYTICS_GA4 and GOOGLE_ANALYTICS_UA .
The variables have been setup for both staging and production instances already. There are now four properties setup on Google Analytics, one GA4 and one UA tracking properties for each of the staging and production sites.
This has been tested locally and I can confirm that the dual tracking is working currently.
> Add GA4 tracking. GA4 and UA tracking id to be set from environment variable.

- components/DatasetDetails/DatasetActionBox.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
- components/DatasetDetails/DatasetInformationBox.vue
- components/FilesTable/FilesTable.vue
There were some inconsistencies when attempting to view files for embargoed test dataset 275 which I believe were a result of nested properties not triggering re-renders. I have created computed properties/watchers to deal with the issues
Locally via dataset 275
> Addressed intermittent bugs with viewing embargoed data

- components/CommunitySpotlight/CommunitySpotlightItem.vue
- components/CommunitySpotlight/CommunitySpotlightListings.vue
- components/EventListItem/EventListItem.vue
- components/FacetMenu/CommunitySpotlightFacetMenu.vue
- components/FacetMenu/EventsFacetMenu.vue
- components/FacetMenu/NewsFacetMenu.vue
- components/NewsListItem/NewsListItem.vue
- pages/news-and-events/community-spotlight/index.vue
- pages/news-and-events/events/index.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
- pages/news-and-events/news/index.vue
Addressed the following feedback from Dominic:
-Images on the News & Events landing page for Community Spotlight are very tall (Tested on Safari)
-Images on the Community Spotlight FB for Community Spotlight are very tall (Tested on Safari)
-Images on the News & Events landing page for News articles are missing
-Images on the News FB for News articles are missing
-Can we also include sorting “Z - A”
-Ability to tag News content types as either “News Article” or “Funding opportunity” (and adding this into the facets on News FB)
-Ability to tag Community Spotlight content types with Anatomical Structure (and adding this into the facets on Community Spotlight FB)
Locally
> Addressed Gazelle Feedback for news and events page refactor

- components/DatasetDetails/DatasetHeader.vue
- pages/datasets/timeseriesviewer/index.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Added a timeseries viewer page and redirected to it when a user attempts to view a timeseries file. This was done in order to follow the pattern already established by other viewers and to maintain a consistent view
Locally
> timeseries page refactor

- nuxt.config.js
- pages/datasets/_datasetId.vue
- pages/datasets/timeseriesviewer/index.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Added an env var flag for showing/hiding the timeseries viewer while we work on getting its implementation compliant with the requirements hugh outlined here: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=644373841&pid=416152743&cid=415614298
Locally
> hide timeseries viewer behind a flag

- pages/news-and-events/community-spotlight/fireside-chats/index.vue
- pages/news-and-events/community-spotlight/success-stories/index.vue
I had updated the param selectedSpotlightTypeOptions to selectedSpotlightTypes and forgot to update the redirect links
Locally
- [ X] I have performed a self-review of my own code
> Fixed param name typos

- components/ToolAndResourcesPage/ToolsAndResourcesPage.vue
- components/header/Header.vue
- pages/about/about-sparc/index.vue
- pages/about/policies-and-standards/index.vue
- pages/news-and-events/community-spotlight/success-stories/_id.vue
- pages/projects/_projectId.vue
Add associated datasets to projects details page as outlined in the wireframes here: https://app.abstract.com/share/80fd63dd-eee3-4bb6-9578-284f19eb868b
Updated styling for success stories details page
Locally
> Add associated projects to project details page

- components/Resources/ResourcesSearchResults.vue
When searching for Resources, it was asked that Markdown was shown for the description field of each result (Resource).
See https://www.wrike.com/open.htm?id=952119114
Manually
> Showing markdown for field 'description' in Resources search results page

- components/DatasetDetails/DatasetFilesInfo.vue
As per: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=970450584&pid=415614298&cid=415614298
Added disabled download button for datasets over 5GB
Locally
> Added disabled button for datasets over 5GB

- components/DatasetDetails/DatasetActionBox.vue
- components/DatasetDetails/DatasetFilesInfo.vue
- pages/datasets/_datasetId.vue
As per Dominic's recommendation in the comments here: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=963704786&pid=825399023&cid=441356195  
Moved the embargoed dataset tooltip text to be inside the files tab
Locally
> Add embargoed tooltip to files tab

- package.json
- yarn.lock
Previously, scaffold context cards on the sidebar always used the dataset's banner. 
This caused some confusion so some methods of controlling the context card's banner have been added
https://jesse-sprint-23.herokuapp.com/maps
context cards now take context banners in the following order:
1. Look for a banner field on the top level of scaffold_context_info.json. The sidebar expects this to be a file path to the banner
2. Use the first view's thumbnail image
3. Use the dataset's banner image
This can be checked with dataset 259
Run and tested with a few people at abi. This code can also be tested on a sparc-app clone here:
https://jesse-sprint-23.herokuapp.com/maps
> Update mapintegratedvuer to latest version

- components/DatasetDetails/DatasetFilesInfo.vue
Make it clear that the dataset will be compressed upon direct download. This is to address the issue reported in the ticket [here](https://www.wrike.com/open.htm?id=912390744).
The added statement can be found on this page - https://alan-wu-sparc-app.herokuapp.com/datasets/86?type=dataset&datasetDetailsTab=files
> Make it clear that the dataset will be compressed upon direct download.

- components/VersionHistory/VersionHistory.vue
- mixins/request-download-file/index.js
[Add logic to change log display](https://www.wrike.com/open.htm?id=947150591)
> Acceptance Criteria:
add logic to the change log display so that it shows what is available without downloading the file, utilizing UI/UX best practices
potentially showing full change log without downloading, or showing first 120 characters of changelog
Display text as-is for first version. 
use icons (download and view) in the changelog column
- Uses the `large-modal` for display
- Added a function to 'request-download-file to obtain file contents
- Added icons for downloading and viewing the changelogs (requested in acceptance criteria)
- run eslint on `VersionHistory.vue`
This pr can be tested with the link below
https://jesse-sprint-23.herokuapp.com/datasets/76?type=dataset&datasetDetailsTab=versions …
> Jesses Sprint 23 - Add logic to change log display

- package.json
- yarn.lock
If you open this scaffold on https://staging.sparc.science/maps , the context card currently crashes
This is because there is an issue where the version of marked used on the sidebar seems to not get used.
This PR fixes this issue by whitelisting marked in map-side-bar's node eternals (thank you Alan for the idea)
Tested locally and this code can be viewed at:
https://jesse-sprint-23.herokuapp.com/maps
> Fix issue where marked versions were clashing

- pages/news-and-events/index.vue
The [news and events page](https://sparc.science/news-and-events) does not load properly on refresh or on new visit causing some of the items on the page to not render properly such as the no item is loaded onto the Current Newsletter. The issue is reported in this [wrike ticket](https://www.wrike.com/open.htm?id=981940590). The solution is to disable server side rednering on the components causing the issue and is implemented with this pull request
The fix has been deployed this page - https://alan-wu-sparc-app.herokuapp.com/news-and-events
The Current NewsLetter item should load on refresh.
> Fix an issue with reloading the news-and-events page.

- nuxt.config.js
I accidentally changed this a while back, I think we should change it back to what the default staging.sparc.science sparc-api: `https://sparc-api.herokuapp.com/` 
Also, there is a space that snuck in here, so even if you were using a development server on `https://localhost:5000`, it still would not work...
Ran locally
> Fix default 'PORTAL_API_HOST' throwing an error

- components/LoginModal/LoginModal.vue
- components/header/Header.vue
- middleware/signOutRedirect.js
- nuxt.config.js
- pages/index.vue
Sped up logout by using a middleware. I attempted to also use this middleware for sign in, but I could not get federated sign in to allow dynamic routing since the callback was not going through the middleware or asyncData (It was only happening client-side so we have to wait for mount)
Locally
> Added middleware for sign out

- package.json
- yarn.lock
This update fixes an issue with the map viewer not being able to get the latest update maps.
This has been tested locally, it should now display the latest flatmap and this can also be tested on https://mapcore-demo.org/staging/flatmap-update-sparc-app/maps/
> QA fix for map viewer not displaying the latest flatmaps

- package.json
- yarn.lock
This update address a problem with the sensory neurons control and add support of the other type neurons toggle.
UUID of a flatmap will now be stored with the permalink which will be used to identify flatmap in the future.
I have deployed it on https://mapcore-demo.org/staging/flatmap-update-sparc-app/maps for testing
> QA Second fixes for map viewer not displaying the latest flatmaps

- components/SearchResults/DatasetSearchResults.vue
Fix for: https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=1023323110&pid=416152743&cid=415614298 Datasets can have undefined descriptions and created at/updated at dates when they are unpublished. Adding in checks for these scenarios
Locally
> Hot fix for search bug

- components/EventListItem/EventListItem.vue
- components/NewsListItem/NewsListItem.vue
- components/StayConnected/StayConnected.vue
- components/ToolAndResourcesPage/ToolsAndResourcesPage.vue
- components/footer/FooterLink.vue
- mixins/marked/index.js
- pages/projects/_projectId.vue
We are now treating docs.sparc.science as an internal link that gets opened in a new tab as per: https://www.wrike.com/open.htm?id=1014556904
Also updated 'Site Feedback' footer link to include the current url when navigating to the contact-us page so that we can automatically capture the page that the user navigated there from
Locally
> Remove external link icon

- components/FacetMenu/EventsFacetMenu.vue
- components/FacetMenu/NewsFacetMenu.vue
- pages/index.vue
Updated default values to match the current year/month as requested per: https://www.wrike.com/open.htm?id=1015155108
I also added the og:image header to the index page in case setting the header property in the nuxt config did not work
Locally
> updated default values for news/events facet menus

- package.json
- yarn.lock
Legacy maps from permalink are now supported with the update on the latest map viewer updates. 
This can be tested using the following links:
https://mapcore-demo.org/current/sparc-app/maps/?id=b6f5315e
https://mapcore-demo.org/current/sparc-app/maps/?id=e2125092
Clicking on "Click here for the latest map" on the left to view the latest map.
> Permalink on maps now supported legacy maps

- package.json
- yarn.lock
Previous release has caused the human female flatmap loaded from permalink to display as Legacy map as always. This update fixes the issue.
Human Female flatmap should load as normal (non-legacy) map with this permalink - https://mapcore-demo.org/current/sparc-app/maps/?id=b3966b57
> Fix a bug with female human map displayed as legacy when loading from state

- components/FacetMenu/FacetRadioButtonDateCategory.vue
- pages/index.vue
- utils/homepageFields.js
Getting the featured dataset id from the sparc-api instead of contentful field in order to randomize the homepage dataset as per: https://www.wrike.com/open.htm?id=1024003575 and https://www.wrike.com/open.htm?id=1024003176
Also fixed bug for filtering events by date 
Locally
> Pulling featured dataset id from sparc-api

- mixins/marked/index.js
- package.json
- yarn.lock
Markdown library ``marked`` was sanitizing out harmless tags like ``<sup>`` or ``<sub>`` not allowing the use of them in Contentful. By following the recommendation in the ``marked`` Github issues page, I added different library for sanitation (``dompurify``)
Manually
> New library for Markdown sanitation

- package.json
- pages/maps/index.vue
- yarn.lock
This pull request fix bugs regarding the map viewer. It includes changes from this pull request - https://github.com/ABI-Software/mapintegratedvuer/pull/149 and https://github.com/ABI-Software/flatmapvuer/pull/95
It also fixes a bug where dataset may not display correctly when going from the gallery / file browser to the map page.
The latest map viewer can be tested on this page - https://mapcore-demo.org/current/sparc-app/maps/
> Gallery to maps

- package.json
- yarn.lock
Fix an issue introduced in the previous pull request causing clicking on the markers to not open the sidebar with facet filter correctly on the map viewer.
This has been deployed here for testing - mapcore-demo.org/current/sparc-app/maps
> Fix an issue with clicking on marker on the map-viewer.

- pages/maps/index.vue
This pull request addressed the feedback from the wrike ticket here - https://www.wrike.com/open.htm?id=970444593
It makes sure body proper is not highlighted when going from the gallery to the map viewer.
Test locally. Going from the [gallery](https://mapcore-demo.org/current/sparc-app/datasets/134?type=dataset&datasetDetailsTab=images) to the map viewer should ignore the body proper highlight.
> QA fix: Make sure body proper is ignored when opening the flatmap.

- components/BiolucidaViewer/BiolucidaViewer.vue
- nuxt.config.js
- package.json
- pages/datasets/biolucidaviewer/_id.vue
- services/biolucida.js
- yarn.lock
Changed the BiolucidaViewer 'View in 3D' button to open an image in the MBF Neurolucida 360 cloud application instead of the current web-based Biolucidaviewer.
Tested by going to Biolucida images like:
datasets/biolucidaviewer/1649?view=MTY0OS1jb2wtMTI3&dataset_version=3&dataset_id=77&item_id=N%3Apackage%3Aaa916348-d306-4bc2-8370-94048adb1bf0
and clicking on the 'View in 3d' button.  This opens the MBF Neurolucida 360 cloud application in a separate tab with the 3D image from the SPARC portal visible.
> Set BiolucidaViewer 'View in 3D' button to open a Neurolucida 360 Cloud instance

- components/BiolucidaViewer/BiolucidaViewer.vue
Adding a new button to launch Neurolucida 360 cloud and keep the 'View in 3D' button launching the local Biolucida desktop application.
Tested by going to Biolucida images like:
datasets/biolucidaviewer/1649?view=MTY0OS1jb2wtMTI3&dataset_version=3&dataset_id=77&item_id=N%3Apackage%3Aaa916348-d306-4bc2-8370-94048adb1bf0
and clicking on the 'View in 3d' button and clicking on the 'View in NL360C' button. This opens the Biolucida desktop application (if present on the system) and MBF Neurolucida 360 cloud application in a separate tab respectively, with the 3D image from the SPARC portal visible.
> Separate buttons for Biolucida image viewer

- pages/data/index.vue
Return alternative search options to user when there are 0 search results
This new feature is requested in the wrike ticket:
https://www.wrike.com/open.htm?id=1014464589
This code can be checked at:
https://jesse-sprint-27.herokuapp.com/data?type=simulation&search=A%20New%20Paradigm
Tested locally and others can test here:
https://jesse-sprint-27.herokuapp.com/data?type=simulation&search=A%20New%20Paradigm
> Add alternative search when there are 0 results

- components/CommunitySpotlight/CommunitySpotlightItem.vue
- components/CommunitySpotlight/CommunitySpotlightListings.vue
- components/DatasetDetails/DatasetDescriptionInfo.vue
- pages/news-and-events/community-spotlight/index.vue
https://www.wrike.com/open.htm?id=1043784426
Changes wording of "Anatomical structure(s)" to "Focus" in News & Events page and solves bug with "n/a" display of data in News & Events page
Manually
> Community Spotlights - Wording + Bug

- components/DatasetDetails/SimilarDatasetsInfoBox.vue
Update dataset page to link to scaffold search and fix authors link on dataset page.
The wrike tickets can be found here: 
https://www.wrike.com/open.htm?id=1037491649
https://www.wrike.com/open.htm?id=1044425213
This has been tested locally and can be check on the following pages
Clicking on the Scaffold pill on the left https://alan-wu-sparc-app.herokuapp.com/datasets/174?type=dataset should bring user to the Anatomical search page.
Clicking on the author name on the left panel should perform the search correctly https://alan-wu-sparc-app.herokuapp.com/datasets/295?type=dataset&datasetDetailsTab=about
> Update dataset page to link to scaffold search correctly. 

- components/ImagesGallery/ImagesGallery.vue
Thumbnails for segmentation files are not getting set correctly in the gallery.
Tested manually going to https://staging.sparc.science/datasets/230?type=dataset&datasetDetailsTab=images
at the end all the segmentation thumbnails should be images, not the default SPARC logo.
> Fix segmentation thumbnails

- pages/datasets/segmentationviewer/_id.vue
- pages/datasets/videoviewer/_id.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Fix issue from previous s3 bucket fix pull request where app is not defined in asyncData methods but is required for getDatasetInfo methods.
The following link should work once deployed - https://alan-wu-sparc-app.herokuapp.com/datasets/segmentationviewer?dataset_id=230&dataset_version=1&file_path=files%2Fprimary%2Fsub-dorsal-4%2Fsam-CGRP-Mouse-Dorsal-4%2F3D_scaffold_-_CGRP-Mice-Dorsal-4.xml
> Fix missing app in asynData.

- components/AlternativeSearchResults/AlternativeSearchResults.vue
- components/AlternativeSearchResults/AlternativeSearchResultsNews.vue
- components/AlternativeSearchResults/AlternativeSearchResultsResources.vue
- pages/data/index.vue
- pages/news-and-events/community-spotlight/index.vue
- pages/news-and-events/events/index.vue
- pages/news-and-events/news/index.vue
- pages/resources/biological/index.vue
- pages/resources/databases/index.vue
- pages/resources/devices/index.vue
- pages/resources/information-services/index.vue
- pages/resources/software/index.vue
Added alternative search results for Resources and News and Events pages
Can preview these changes here:
https://jesse-sprint-27.herokuapp.com/resources
It is requested from the comments in this ticket:
https://www.wrike.com/open.htm?id=1014464589
Tested locally and can be tested on the sparc-app clone of this branch here:
https://jesse-sprint-27.herokuapp.com/resources
> Alternative search results for `/resources` and `/news-and-events`

- pages/about/about-sparc/index.vue
- pages/about/policies-and-standards/index.vue
- pages/contact-us/index.vue
- pages/data/index.vue
- pages/news-and-events/community-spotlight/index.vue
- pages/news-and-events/events/index.vue
- pages/news-and-events/news/index.vue
- pages/resources/biological/index.vue
- pages/resources/databases/index.vue
- pages/resources/devices/index.vue
- pages/resources/information-services/index.vue
- pages/resources/software/index.vue
Fixed search tabs bug where you could have multiple tabs shown as selected by down clicking on a non-active tab and dragging it instead of actually selecting it
Locally
> removed focus style

- components/DatasetDetails/DatasetFilesInfo.vue
- components/ImagesGallery/ImagesGallery.vue
- components/VersionHistory/VersionHistory.vue
- pages/datasets/_datasetId.vue
In order to reduce load time on the initial dataset details page rendering I moved all logic possible from the pages asyncData() to each respective component's fetch(). This allow the page to work on updating the components in the tabs while the page is shown instead of having to wait for everything to load before displaying the page as requested in: 
https://www.wrike.com/open.htm?id=1091588655
Locally. Drastically reduced load time from a couple seconds to ~100 milliseconds
> moved logic out of dataset details asyncData into respective component's fetch

- middleware/authenticated.js
- mixins/authenticated/index.js
- pages/user/profile/index.vue
- pages/welcome/index.vue
moved authentication middleware navigation guard login logic into route hook for pages. The middleware was not getting fired on client side at points.
Locally. Try logging into staging and then navigating directly to the guarded route user/profile. You are re-directed back to the homepage bc the auth middleware logic is not running
> Fixed authentication bug

- components/header/Header.vue
Changing default search of the header's search bar when searching Tools & Resources from Biological to Databases
https://www.wrike.com/open.htm?id=1050960119
Manually
> Default search tab from Tools&Resources header search bar

- components/FeaturedEvent/FeaturedEvent.vue
- components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
- components/ToolAndResourcesPage/ToolsAndResourcesPage.vue
- pages/news-and-events/community-spotlight/success-stories/_id.vue
- pages/news-and-events/events/_eventId/event-details/index.vue
- pages/news-and-events/index.vue
- pages/resources/index.vue
According to this ticket, https://www.wrike.com/open.htm?id=1057888212
I believe that we want to allow the 'sup' html tag through on the community spotlight, news events and resources pages where there are html fields on contentful.
Every field which could potentially use 'sup' should now allow it with these code changes
Run locally, but I can't find any entries from contentful that use 'sup' tags
> Allow 'sup' tags in most html parsing

- package.json
- yarn.lock
Currently on stagin.sparc.science, tooltips on the AC maps are missing their pubmed resources. 
This mapintegratedvuer update is an update to the logic in flatmapvuer which was previously incorrect causing this issue.
Can test this by going to https://jesse-sprint-27.herokuapp.com/maps?type=ac and clicking on one of the neuron paths
Ran on each viewer and sparc-app locally.
A live preview of this code is also available at:
https://jesse-sprint-27.herokuapp.com/maps?type=ac
> Update mapintegratedvuer to fix small logic issue in popups

- components/Breadcrumb/Breadcrumb.vue
- components/FeaturedEvent/FeaturedEvent.vue
- components/NewsEventsResourcesPage/NewsEventsResourcesPage.vue
- components/ToolAndResourcesPage/ToolsAndResourcesPage.vue
- pages/news-and-events/community-spotlight/success-stories/_id.vue
- pages/news-and-events/events/_eventId/event-details/index.vue
- pages/news-and-events/index.vue
- pages/resources/index.vue
- plugins/bootstrap.js
The 'ALLOWED_TAGS' is actualy an extensive list of what html tags will be allowed. It overides the default list from DOMPurify meaning that only the sup tag will be allowed to pass through.
This reverts those changes (as they break a big chunk of the markdown on the site)
I have added the sup tag to bootstrap.js allowed tags, for where DOMPurify is not being used
This was noticed in this ticket:
https://www.wrike.com/open.htm?id=1057888212
And it reverts the changes from #665 
Please see my comments in the wrike ticket for evidence that 'sup' tags are already supported
example:
Live view of this code at:
https://jesse-sprint-27.herokuapp.com/resources/4LkLiH5s4FV0LVJd3htsvH
Ran locally, and tested all fields using:
`<h1 v-html="parseMarkdown('<p>This text …
> Hot Fix: Remove all 'sup' tags being passed to DOMPurify

- pages/maps/index.vue
Previous release unintentionally uses anatomical name when starting a flatmap with an uberon. This pull request addresses the issue.
Only the Pelvic splanchnic nerve should be highlighted.
Bug: https://sparc.science/maps?type=flatmap&dataset_version=1&dataset_id=206&taxo=NCBITaxon%3A10114&uberonid=UBERON%3A0018675&for_species=rat
Fixed: https://alan-wu-sparc-app.herokuapp.com/maps?type=flatmap&dataset_version=1&dataset_id=206&taxo=NCBITaxon%3A10114&uberonid=UBERON%3A0018675&for_species=rat
> Fix a bug causing uberon id to not be used.

- components/header/Header.vue
Hide Top Search Bar from Homepage
https://jesse-sprint-preview.herokuapp.com/
This was requested from this ticket:
https://www.wrike.com/open.htm?id=1073758737
Note that this ticket asked to keep the code around, as it is likely coming back.
I suggest we either take note of this PR or make a branch that store the search as there is a good chance we will bring it back.
(I didn't want to comment it out as it was nested somewhat deep and would look a little nasty)
> Add a option in data to show or hide search bar, set it to hide the search in header

- package.json
- yarn.lock
Uee build in marked for mapintegratedvuer which resolves an issue with context card not displayed on the sidebar.
This can be tested here on - https://alan-wu-sparc-app.herokuapp.com/maps?type=ac
> Use build in marked for mapvuer.

- components/FilesTable/FilesTable.vue
Fixed the path to point to the s3 path in order to address: https://www.wrike.com/open.htm?id=1131485745
Locally
> Fixed calculated s3 path

- layouts/default.vue
- store/layouts/default.js
Added the ability to set a stop date for which to stop showing the portal notification as requested by Sue in addition to when to clear the browser cookie for the has seen
Locally
> Added portal notification settings

- components/Gallery/Gallery.vue
Yomi found an issue where the news item component wasn't rendering item correctly and this was due to the fact that the key was not changing, which is what triggers it to re-render. Updated the keys to actually be unique
Locally
> Bug fix for gallery rendering

- components/EventCard/EventCard.vue
- components/EventListItem/EventListItem.vue
- pages/news-and-events/index.vue
- pages/news-and-events/model.ts
Past events and its control have been removed as request in this ticket - https://www.wrike.com/open.htm?id=1161697934
This has been tested locally and it can be checked here - https://alan-wu-sparc-app.herokuapp.com/news-and-events
> Remove past events in the news & events page.

- mixins/recaptcha/index.js
- pages/contact-us/index.vue
This change is requested here:
https://www.wrike.com/open.htm?id=1174694935
This change utilises the nuxt loading page for loading while the form requests are made.
The Sparc loading gif was requested specifically, so I thought the sparc loading page was appropriate here
Changes can be viewed here:
https://jesse-sprint-preview.herokuapp.com/
Change requested here:
https://www.wrike.com/open.htm?id=1161701403
The form selector is now hidden after submission, navigating to a new form resets the form
Tested locally and changes will be viewable here shortly:
https://jesse-sprint-preview.herokuapp.com/
> Open the nuxt loading page while form is loading, remove form selector after submission, reset form on new form selection

- components/ConfirmationModal/ConfirmationModal.vue
- pages/user/profile/index.vue
There is an issue with the v-on click handlers when deploying to heroku for some reason. I believe it has to do with the use of single quotes over double so I updated the syntax
Locally, although it worked fine locally before. Will test on Heroku
> Fixed bug with click handlers

- components/ImagesGallery/ImagesGallery.vue
Fix a bug causing the gallery not to able to display any item https://www.wrike.com/open.htm?id=1232091081.  
The broken image gallery can be found here - https://sparc.science/datasets/26?datasetDetailsTab=images
The fixed gallery can be found here - https://alan-wu-sparc-app.herokuapp.com/datasets/26?datasetDetailsTab=images
> Fix an issue in image gallery with plot.

- components/FilesTable/FilesTable.vue
- pages/file/_datasetId/_datasetVersion/index.vue
Remove action button to open in browser viewer for CSV as the viewer is only supported by Safari and causing undesired behaviour for other browsers, details of the issue can be viewed in this [ticket](https://www.wrike.com/open.htm?id=1204588950).
This has been tested locally and on this [heroku](https://alan-wu-sparc-app.herokuapp.com/datasets/26?type=dataset&datasetDetailsTab=files&path=files%2Fderivative%2Fsub-Pig-013) instance.
> Remove action button for CSV

- package.json
- yarn.lock
This change was requested by Dominic so that users can see the new context cards (which are hidden behind the sidebar currently)
Requested here:
https://www.wrike.com/open.htm?id=1127382486
> Update mapintegratedvuer - now close sidebar when opening scaffold

- pages/data/utils.ts
Solved [identified bug](https://www.wrike.com/open.htm?id=1214691760)
Results highlighter was also wrapping anchors' `href` properties with `<b></b>`, breaking the link.
Manually
> [bugfix] search result anchor highlighting

- components/ImagesGallery/ImagesGallery.vue
- pages/maps/index.vue
Improve query parameters on the maps page to make the link constructable manually. Please check here for the details: https://docs.google.com/document/d/1N4Z2h2XJad4ReskSb8eTtWyNLJ9NZoJK4MNtIzAt_sA/edit#heading=h.p6kg75rdm3u0
I have tested this manually and it should not break any backward compatibility.
I have also deployed the sample links:
New query parameters with AC maps:
https://alan-wu-sparc-app.herokuapp.com/maps?type=ac&dataset_version=5&dataset_id=102&taxon=NCBITaxon%3A9823&anatomy=UBERON%3A0000948&for_species=pig
The old query parameters with type=flatmap, taxo and uberonid still works:
https://alan-wu-sparc-app.herokuapp.com/maps?type=flatmap&dataset_version=5&dataset_id=102&taxo=NCBITaxon%3A9823&uberonid=UBERON%3A0000948&for_species=pig
Features …
> Update paremeter queries in maps page to make it constructable.

- test/cypress/e2e/mapviewer.cy.js
Added a recursive function to fix the provenance card not showing issue caused by clicking on the wrong neuron coordinates for e2e testing.
Modified test is run locally using the Ubuntu system and the Electron browser. Passed as expected.
> fixed e2e testing provenance card not showing issue

- pages/datasets/file/_datasetId/_datasetVersion/index.vue
Addressed discrepancy some files pennsieve file source package id and biolucida image data source package id
Locally via the gallery items in: https://sparc.science/datasets/268?datasetDetailsTab=images
> Fixed Biolucida Viewer issue

- test/cypress/e2e/mapviewer.cy.js
Disabled the element animation waiting time during the click testing. Try to avoid the timeout due to Cypress Cloud performance.
The issue cannot be reproduced locally. Hence, need to create the PR to trigger the GitHub action to run in Cypress Cloud.
Tests are passed in Cypress Cloud.
> Updated the testing click action failed case

- pages/datasets/file/_datasetId/_datasetVersion/index.vue
Updated segmentation viewer to pull its data the same way as before by using the sparc-api endpoint (instead of pulling from the scicrunch['mbf-segmentation'] property
Locally using /datasets/file/37/3?path=files%2Fderivative%2Fsub-54-5%2FTJU_3Scan_ratheart54-5_updated_06_11_19_Fiducials.xml
> update segmentation data to come from sparc-api endpoint

- components/FilesTable/FilesTable.vue
- components/ViewersMetadata/BiolucidaViewerMetadata.vue
- components/ViewersMetadata/PlotViewerMetadata.vue
- components/ViewersMetadata/SegmentationViewerMetadata.vue
- components/ViewersMetadata/VideoViewerMetadata.vue
- mixins/dataset-info/index.js
Included version in call to method since file info no longer contains dataset version after migration.
Locally
> Fixed call to download file mixin to include version

- mixins/dataset-info/index.js
isEmpty does not check for null so added this check
Locally
> add null check to userToken

- pages/about/index.vue
- utils/common.js
Fixed the calculated month in the metrics request, we were off by one
Locally
> Reformatted metrics request

- components/FilesTable/FilesTable.vue
Added viewer action icons in the files table for the remaining viewers as requested in: https://www.wrike.com/open.htm?id=1279141781
Locally
> Added action icons for viewers

- components/FacetMenu/TagsContainer.vue
- package.json
- pages/user/profile/index.vue
- yarn.lock
Fixed reset all bug outlined here: https://www.wrike.com/open.htm?id=1288216402
The issue was in the design system, so had to bump the version to include it
Locally
> Fix reset all bug

- pages/datasets/_datasetId.vue
Bug fix when viewing older versions of computational models. We were missing a check which was resulting in only the most recent version being shown
Locally
> Fix viewing older versions

- components/BiolucidaViewer/BiolucidaViewer.vue
- components/ViewersMetadata/BiolucidaViewerMetadata.vue
This fixes a problem with neurolucida as described in this ticket - https://www.wrike.com/open.htm?id=1324988860
Once this deployed, the neurolucida 360 button should work in the following route:
datasets/file/367/1?path=files/derivative/sub-rat01/sam-01/sub-rat01-sam-section2-ses-massons+trichrome.jp2
Test this locally.
> Fix an issue with neurolucida 360.

- components/Gallery/GalleryItems/FileViewerCard.vue
- components/ImagesGallery/ImagesGallery.vue
All the changes are focused on fixing the unending spinning issue mentioned in ticket [Investigate unending spinning of dataset images for all datasets](https://www.wrike.com/open.htm?id=1321938755)
I have done manual testing. Accessed all the dataset galleries and checked whether all spinning icons were gone.
> Unending spinning of dataset images
